/* Изменение процедуры расчета */

CREATE OR REPLACE PROCEDURE CONFIRM_HND_DRAFT_BEGIN (
   JOURNAL_FIELD_ID IN INTEGER,
   ALGORITHM_ID IN INTEGER
)
AS
   APOINT_ID INTEGER;
   APARAM_ID INTEGER;
   AMEASURE_TYPE_ID INTEGER;
BEGIN
   SELECT POINT_ID,
          PARAM_ID,
		  MEASURE_TYPE_ID
     INTO APOINT_ID,
          APARAM_ID,
		  AMEASURE_TYPE_ID
     FROM JOURNAL_FIELDS
    WHERE JOURNAL_FIELD_ID = CONFIRM_HND_DRAFT_BEGIN.JOURNAL_FIELD_ID;

   IF (APARAM_ID = 50008)
   THEN   /* Отсчет (ход обратно) */

     IF (AMEASURE_TYPE_ID IN (70021, 70022))
     THEN   /* Галерея 1,2 */
       CONFIRM_HND_DRAFT_BEGIN_1_2 (JOURNAL_FIELD_ID, ALGORITHM_ID);
     ELSE
       CONFIRM_HND_DRAFT_BEGIN_OTHER (JOURNAL_FIELD_ID, ALGORITHM_ID);
     END IF;
   END IF;
END;

--

/* Фиксация изменения */

COMMIT