/* Обновление */

BEGIN
  DELETE FROM MEASURE_TYPE_ROUTES
   WHERE MEASURE_TYPE_ID=49984;
   
  DELETE FROM MEASURE_TYPE_PARAMS
   WHERE MEASURE_TYPE_ID=49984;

  DELETE FROM MEASURE_TYPE_ALGORITHMS
   WHERE MEASURE_TYPE_ID=49984;

   COMMIT; 
END;