/*  Создание процедуры получения пути и имени объекта */

CREATE OR REPLACE PROCEDURE G_OBJECT_PATHS
( 
  OBJECT_ID IN INTEGER, 
  PATHS IN OUT VARCHAR2, 
  NAME IN OUT VARCHAR2 
) 
AS 
BEGIN 
  PATHS:=GET_OBJECT_PATHS(OBJECT_ID); 
  PATHS:=TRIM(CHR(13) FROM PATHS); 
  PATHS:=TRIM(CHR(10) FROM PATHS); 
  SELECT NAME INTO G_OBJECT_PATHS.NAME  
    FROM OBJECTS 
   WHERE OBJECT_ID=G_OBJECT_PATHS.OBJECT_ID;  
END;

--

/* Фиксация изменений */

COMMIT

