/* Создание таблицы просмотра суммарных фильтрационных расходов */

CREATE OR REPLACE VIEW S_FLT_OBJECT_EXPENSE 
AS
SELECT TC.CYCLE_NUM, 
       TC.DATE_OBSERVATION, 
       OT2.OBJECT_ID, 
       O.SHORT_NAME AS OBJECT_NAME, 
       GO.GROUP_ID, 
       GO.PRIORITY,
       TC.RASXOD AS EXPENSE
  FROM S_FLT_TOTAL_CHARGES TC, 
       OBJECT_TREES OT1, OBJECT_TREES OT2, OBJECTS O,
       GROUP_OBJECTS GO  
 WHERE TC.OBJECT_ID=OT1.OBJECT_ID   
   AND OT1.PARENT_ID=OT2.OBJECT_TREE_ID
   AND OT2.OBJECT_ID=O.OBJECT_ID
   AND GO.OBJECT_ID=OT2.OBJECT_ID  
   AND TC.MEASURE_TYPE_ID IN (2582,2583)

--

/* Фиксация изменений БД */

COMMIT
