/* Создание просмотра паспортов преобразователей для Настенных щелемеров */

CREATE OR REPLACE VIEW S_SLW_CONVERTER_PASSPORTS
AS
SELECT MT.MEASURE_TYPE_ID,
       MT.NAME AS MEASURE_TYPE_NAME,
	   R.ROUTE_ID,
	   R.NAME AS ROUTE_NAME,
       P.POINT_ID,
       P.NAME AS POINT_NAME,
	   TRIM(CHR(10) FROM TRIM(CHR(13) FROM GET_OBJECT_PATHS(P.OBJECT_ID))) AS OBJECT_PATHS,
	   P.COORDINATE_Z,
	   C.NAME AS CONVERTER_NAME,
	   C.DATE_ENTER,
	   CP.*
  FROM CONVERTERS C, POINTS P, ROUTE_POINTS RP, ROUTES R, MEASURE_TYPE_ROUTES MTR, MEASURE_TYPES MT,
       (SELECT CONVERTER_ID,
               DATE_BEGIN,
               DATE_END,
               MIN(DECODE(PARAM_ID,30006,TO_NUMBER(REPLACE(VALUE,',','.'),'FM99999.9999'),NULL)) AS BASE_COUNTING_OUT_X,
               MIN(DECODE(PARAM_ID,30008,TO_NUMBER(REPLACE(VALUE,',','.'),'FM99999.9999'),NULL)) AS BASE_COUNTING_OUT_Y,
               MIN(DECODE(PARAM_ID,30009,TO_NUMBER(REPLACE(VALUE,',','.'),'FM99999.9999'),NULL)) AS BASE_COUNTING_OUT_Z,
               MIN(DECODE(PARAM_ID,30010,TO_NUMBER(REPLACE(VALUE,',','.'),'FM99999.9999'),NULL)) AS BASE_OPENING_X,
               MIN(DECODE(PARAM_ID,30011,TO_NUMBER(REPLACE(VALUE,',','.'),'FM99999.9999'),NULL)) AS BASE_OPENING_Y,
               MIN(DECODE(PARAM_ID,30012,TO_NUMBER(REPLACE(VALUE,',','.'),'FM99999.9999'),NULL)) AS BASE_OPENING_Z,
               MIN(DECODE(PARAM_ID,30013,VALUE,NULL)) AS DESCRIPTION
          FROM (SELECT C.CONVERTER_ID, CP.DATE_BEGIN, CP.DATE_END, C.PARAM_ID, CP.VALUE 
                  FROM CONVERTER_PASSPORTS CP, COMPONENTS C
                 WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                   AND C.PARAM_ID IN (30006,30008,30009,30010,30011,30012,30013)
                 ORDER BY C.CONVERTER_ID, CP.DATE_BEGIN) CPC
         GROUP BY CONVERTER_ID, DATE_BEGIN, DATE_END) CP
 WHERE C.CONVERTER_ID=P.POINT_ID
   AND C.CONVERTER_ID=CP.CONVERTER_ID
   AND P.POINT_ID=RP.POINT_ID
   AND RP.ROUTE_ID=R.ROUTE_ID
   AND R.ROUTE_ID=MTR.ROUTE_ID
   AND MTR.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
   AND MT.MEASURE_TYPE_ID IN (30006,30007)
 ORDER BY MT.PRIORITY, MTR.PRIORITY, RP.PRIORITY, P.NAME, CP.DATE_BEGIN DESC

--

/* Фиксация изменений */ 

COMMIT