/* Создание просмотра Суммарных фильтрационных расходов в разрезе видов измерения */

CREATE OR REPLACE VIEW S_FLT_MEASURE_TYPE_EXPENSE
AS
SELECT JO.DATE_OBSERVATION,
       C.CYCLE_NUM,
	   C.CYCLE_YEAR,
       JO.MEASURE_TYPE_ID,
	   MT.NAME AS MEASURE_TYPE_NAME,
       JO.VALUE AS EXPENSE
  FROM JOURNAL_OBSERVATIONS JO, MEASURE_TYPES MT, CYCLES C
 WHERE JO.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
   AND JO.CYCLE_ID=C.CYCLE_ID
   AND MT.MEASURE_TYPE_ID IN (2581,2626,2582,2583,2584,2585)
   AND JO.PARAM_ID=3042 /* Расход */
 ORDER BY C.CYCLE_NUM, JO.DATE_OBSERVATION

--

/* Фиксация изменений БД */

COMMIT
