/* Создание последовательности для таблицы журнала действий */

CREATE SEQUENCE SEQ_JOURNAL_ACTIONS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора таблицы журнала действий */

CREATE OR REPLACE FUNCTION GET_JOURNAL_ACTION_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_JOURNAL_ACTIONS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы журнала действий */

CREATE TABLE JOURNAL_ACTIONS
(
  JOURNAL_ACTION_ID INTEGER NOT NULL,
  PERSONNEL_ID INTEGER NOT NULL,
  DATE_ACTION DATE NOT NULL,
  OBJECT VARCHAR2(100) NOT NULL,
  METHOD VARCHAR2(100),
  PARAM VARCHAR2(100),
  VALUE CLOB,
  PRIMARY KEY (JOURNAL_ACTION_ID),
  FOREIGN KEY (PERSONNEL_ID) REFERENCES PERSONNELS (PERSONNEL_ID)
)

--

/* Создание просмотра таблицы журнала действий */

CREATE OR REPLACE VIEW S_JOURNAL_ACTIONS
AS
  SELECT JA.*, 
         P.FNAME||' '||P.NAME||' '||P.SNAME AS PERSONNEL_NAME
    FROM JOURNAL_ACTIONS JA, PERSONNELS P
   WHERE JA.PERSONNEL_ID=P.PERSONNEL_ID

--

/* Создание процедуры создания записи в журнале действий */

CREATE OR REPLACE PROCEDURE I_JOURNAL_ACTION
(
  JOURNAL_ACTION_ID IN INTEGER,
  PERSONNEL_ID IN INTEGER,
  DATE_ACTION IN DATE, 
  OBJECT IN VARCHAR2,
  METHOD IN VARCHAR2,
  PARAM IN VARCHAR2,
  VALUE IN CLOB
)
AS
  AJOURNAL_ACTION_ID INTEGER;
BEGIN
  AJOURNAL_ACTION_ID:=JOURNAL_ACTION_ID;
  IF (AJOURNAL_ACTION_ID IS NULL) THEN
    AJOURNAL_ACTION_ID:=GET_JOURNAL_ACTION_ID;
  END IF;
  INSERT INTO JOURNAL_ACTIONS (JOURNAL_ACTION_ID,DATE_ACTION,PERSONNEL_ID,OBJECT,METHOD,PARAM,VALUE)
       VALUES (AJOURNAL_ACTION_ID,DATE_ACTION,PERSONNEL_ID,OBJECT,METHOD,PARAM,VALUE);
  COMMIT;
END;

--

/* Создание процедуры изменения записи в журнале действий */

CREATE OR REPLACE PROCEDURE U_JOURNAL_ACTION
(
  JOURNAL_ACTION_ID IN INTEGER,
  PERSONNEL_ID IN INTEGER,
  DATE_ACTION IN DATE,
  OBJECT IN VARCHAR2,
  METHOD IN VARCHAR2,
  PARAM IN VARCHAR2,
  VALUE IN CLOB,
  OLD_JOURNAL_ACTION_ID IN INTEGER
)
AS
BEGIN
  UPDATE JOURNAL_ACTIONS 
     SET JOURNAL_ACTION_ID=U_JOURNAL_ACTION.JOURNAL_ACTION_ID,
         PERSONNEL_ID=U_JOURNAL_ACTION.PERSONNEL_ID,
		 DATE_ACTION=U_JOURNAL_ACTION.DATE_ACTION,
         OBJECT=U_JOURNAL_ACTION.OBJECT,
         METHOD=U_JOURNAL_ACTION.METHOD,
         PARAM=U_JOURNAL_ACTION.PARAM,
         VALUE=U_JOURNAL_ACTION.VALUE
   WHERE JOURNAL_ACTION_ID=OLD_JOURNAL_ACTION_ID;
  COMMIT;
END;

--

/* Создание процедуры удаления записи в журнале действий */

CREATE OR REPLACE PROCEDURE D_JOURNAL_ACTION
(
  OLD_JOURNAL_ACTION_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM JOURNAL_ACTIONS
        WHERE JOURNAL_ACTION_ID=OLD_JOURNAL_ACTION_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT