/* Создание последовательности для таблицы прав */

CREATE SEQUENCE SEQ_PERMISSIONS
INCREMENT BY 1 
START WITH 3100
MAXVALUE 1.0E28 
MINVALUE 3100
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы прав */

CREATE FUNCTION GET_PERMISSION_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_PERMISSIONS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы прав */


CREATE TABLE PERMISSIONS
(
PERMISSION_ID INTEGER NOT NULL, 
ACCOUNT_ID INTEGER NOT NULL, 
INTERFACE VARCHAR2(250) NOT NULL,
PERMISSION VARCHAR2(250) NOT NULL,
PERMISSION_VALUE VARCHAR2(250) NOT NULL,
PRIMARY KEY (PERMISSION_ID),
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
)  

--

/* Создание просмотра таблицы прав */

CREATE VIEW S_PERMISSIONS
AS
 SELECT P.*, A.NAME AS ACCOUNT_NAME
   FROM PERMISSIONS P, ACCOUNTS A 
  WHERE  A.ACCOUNT_ID=P.ACCOUNT_ID

--

/* Создание процедуры создания права */

CREATE PROCEDURE I_PERMISSION
(
  PERMISSION_ID IN INTEGER,
  ACCOUNT_ID IN INTEGER, 
  INTERFACE IN VARCHAR2,
  PERMISSION IN VARCHAR2,
  PERMISSION_VALUE IN VARCHAR2
)
AS
BEGIN
  INSERT INTO PERMISSIONS (PERMISSION_ID,ACCOUNT_ID,INTERFACE,PERMISSION,PERMISSION_VALUE)
       VALUES (PERMISSION_ID,ACCOUNT_ID,INTERFACE,PERMISSION,PERMISSION_VALUE);
  COMMIT;
END;

--

/* Создание процедуры изменения права */


CREATE PROCEDURE U_PERMISSION
(
  PERMISSION_ID IN INTEGER,
  ACCOUNT_ID IN INTEGER, 
  INTERFACE IN VARCHAR2,
  PERMISSION IN VARCHAR2,
  PERMISSION_VALUE IN VARCHAR2,
  OLD_PERMISSION_ID IN INTEGER
)
AS
BEGIN
  UPDATE PERMISSIONS 
     SET PERMISSION_ID=U_PERMISSION.PERMISSION_ID,
         ACCOUNT_ID=U_PERMISSION.ACCOUNT_ID,
         INTERFACE=U_PERMISSION.INTERFACE,
         PERMISSION=U_PERMISSION.PERMISSION,
         PERMISSION_VALUE=U_PERMISSION.PERMISSION_VALUE
   WHERE PERMISSION_ID=OLD_PERMISSION_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления права */

CREATE PROCEDURE D_PERMISSION
(
  OLD_PERMISSION_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM PERMISSIONS
        WHERE PERMISSION_ID=OLD_PERMISSION_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT
