/* Создание последовательности для таблицы видов измерений */

CREATE SEQUENCE SEQ_MEASURE_TYPES
INCREMENT BY 1 
START WITH 2500
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы видов измерений */

CREATE FUNCTION GET_MEASURE_TYPE_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_MEASURE_TYPES.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы видов измерений */

CREATE TABLE MEASURE_TYPES
(
  MEASURE_TYPE_ID INTEGER NOT NULL, 
  PARENT_ID INTEGER,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DATE_BEGIN DATE NOT NULL,
  IS_ACTIVE INTEGER NOT NULL,
  PRIORITY INTEGER NOT NULL,
  IS_VISUAL INTEGER NOT NULL,
  IS_BASE INTEGER NOT NULL,
  PRIMARY KEY (MEASURE_TYPE_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID) ON DELETE CASCADE
)  

--

/*  Создание значение по умолчанию для поля визуальный */

ALTER TABLE MEASURE_TYPES
MODIFY IS_VISUAL DEFAULT 0

--

/*  Создание значение по умолчанию для поля базовый по умолчанию */

ALTER TABLE MEASURE_TYPES
MODIFY IS_BASE DEFAULT 0

--

/* Создание просмотра таблицы видов измерений */

CREATE OR REPLACE VIEW S_MEASURE_TYPES
AS
    SELECT MT1.*, MT2.NAME AS PARENT_NAME, LEVEL AS "LEVEL"
      FROM MEASURE_TYPES MT1, MEASURE_TYPES MT2 
     WHERE MT1.PARENT_ID=MT2.MEASURE_TYPE_ID (+)  
START WITH MT1.PARENT_ID IS NULL
CONNECT BY MT1.PARENT_ID=PRIOR MT1.MEASURE_TYPE_ID
  ORDER BY LEVEL, MT1.PRIORITY

--

/* Создание процедуры создания вида измерения */

CREATE OR REPLACE PROCEDURE I_MEASURE_TYPE
(
  MEASURE_TYPE_ID IN INTEGER,
  PARENT_ID IN INTEGER, 
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DATE_BEGIN IN DATE,
  IS_ACTIVE IN INTEGER,
  PRIORITY IN INTEGER,
  IS_VISUAL IN INTEGER,
  IS_BASE IN INTEGER
)
AS
BEGIN
  INSERT INTO MEASURE_TYPES (MEASURE_TYPE_ID,PARENT_ID,NAME,DESCRIPTION,
                             DATE_BEGIN,IS_ACTIVE,PRIORITY,IS_VISUAL,IS_BASE)
       VALUES (MEASURE_TYPE_ID,PARENT_ID,NAME,DESCRIPTION,
	           DATE_BEGIN,IS_ACTIVE,PRIORITY,IS_VISUAL,IS_BASE);
  COMMIT;
END;

--

/* Создание процедуры проверки родительского вида измерения */

CREATE OR REPLACE PROCEDURE A_MEASURE_TYPE_PARENT_ID
(
  MEASURE_TYPE_ID IN INTEGER,
  PARENT_ID IN INTEGER
)
AS
  CNT INTEGER;
  E EXCEPTION;
  ERROR VARCHAR2(500);
BEGIN
  IF (MEASURE_TYPE_ID=PARENT_ID) THEN
    ERROR:='Вид измерения не может ссылаться сам на себя.';
    RAISE E;
  END IF;
  
  SELECT COUNT(*) INTO CNT FROM DUAL
   WHERE PARENT_ID IN (SELECT MT1.MEASURE_TYPE_ID
                         FROM MEASURE_TYPES MT1, MEASURE_TYPES MT2 
                        WHERE MT1.PARENT_ID=MT2.MEASURE_TYPE_ID (+)  
                   START WITH MT1.MEASURE_TYPE_ID=A_MEASURE_TYPE_PARENT_ID.MEASURE_TYPE_ID
                   CONNECT BY MT1.PARENT_ID=PRIOR MT1.MEASURE_TYPE_ID);
		
  IF (CNT>0) THEN
    ERROR:='Вид измерения не может ссылаться на дочерние виды измерения.';
    RAISE E;
  END IF;
  
EXCEPTION
  WHEN E THEN 
       RAISE_APPLICATION_ERROR(-20100,ERROR);
END;

-- 

/* Создание процедуры изменения вида измерения */

CREATE OR REPLACE PROCEDURE U_MEASURE_TYPE
(
  MEASURE_TYPE_ID IN INTEGER,
  PARENT_ID IN INTEGER, 
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DATE_BEGIN IN DATE,
  IS_ACTIVE IN INTEGER,
  PRIORITY IN INTEGER,
  IS_VISUAL IN INTEGER,
  IS_BASE IN INTEGER,
  OLD_MEASURE_TYPE_ID IN INTEGER
)
AS
BEGIN
  A_MEASURE_TYPE_PARENT_ID (MEASURE_TYPE_ID,PARENT_ID);
  UPDATE MEASURE_TYPES 
     SET MEASURE_TYPE_ID=U_MEASURE_TYPE.MEASURE_TYPE_ID,
         PARENT_ID=U_MEASURE_TYPE.PARENT_ID, 
         NAME=U_MEASURE_TYPE.NAME, 
         DESCRIPTION=U_MEASURE_TYPE.DESCRIPTION,
		 DATE_BEGIN=U_MEASURE_TYPE.DATE_BEGIN,
		 IS_ACTIVE=U_MEASURE_TYPE.IS_ACTIVE, 
         PRIORITY=U_MEASURE_TYPE.PRIORITY,
		 IS_VISUAL=U_MEASURE_TYPE.IS_VISUAL,
		 IS_BASE=U_MEASURE_TYPE.IS_BASE
   WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления вида измерения */

CREATE OR REPLACE PROCEDURE D_MEASURE_TYPE
(
  OLD_MEASURE_TYPE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM MEASURE_TYPES
        WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT
