/* Обновление таблицы персонала */

ALTER TABLE PERSONNELS
ADD DATE_ACCEPT DATE

--

/* Изменение таблицы персонала */

UPDATE PERSONNELS
SET DATE_ACCEPT='01.01.2006'

-- 

/* Обновление таблицы персонала */

ALTER TABLE PERSONNELS
MODIFY DATE_ACCEPT DATE NOT NULL

--

/* Обновление таблицы персонала */

ALTER TABLE PERSONNELS
ADD DATE_SACK DATE

--

/* Обновление таблицы просмотра персонала */

CREATE OR REPLACE VIEW S_PERSONNELS
AS
  SELECT P.*, D.NAME AS DIVISION_NAME
    FROM PERSONNELS P, DIVISIONS D 
   WHERE D.DIVISION_ID=P.DIVISION_ID

--

/* Обновление таблицы просмотра персонала только исполнителей */

CREATE OR REPLACE VIEW S_PERSONNEL_ONLY_PERFORMERS
AS
  SELECT P.*, D.NAME AS DIVISION_NAME
    FROM PERSONNELS P, DIVISIONS D, ACCOUNTS A1, ACCOUNTS_ROLES AR, ACCOUNTS A2 
   WHERE D.DIVISION_ID=P.DIVISION_ID
     AND A1.PERSONNEL_ID=P.PERSONNEL_ID
	 AND AR.ACCOUNT_ID=A1.ACCOUNT_ID
	 AND A2.ACCOUNT_ID=AR.ROLE_ID
	 AND A2.NAME LIKE '%Исполнители%'

--

/* Обновление процедуры создания персоны */


CREATE OR REPLACE PROCEDURE I_PERSONNEL
(
  PERSONNEL_ID IN INTEGER,
  DIVISION_ID IN INTEGER,
  FNAME IN VARCHAR2,
  NAME IN VARCHAR2,
  SNAME IN VARCHAR2,
  DATE_ACCEPT IN DATE,
  DATE_SACK IN DATE
)  
AS
BEGIN
  INSERT INTO PERSONNELS (PERSONNEL_ID,DIVISION_ID,FNAME,NAME,SNAME,DATE_ACCEPT,DATE_SACK) 
       VALUES (PERSONNEL_ID,DIVISION_ID,FNAME,NAME,SNAME,DATE_ACCEPT,DATE_SACK);
  COMMIT;
END;

--

/* Обновление процедуры изменения персоны */

CREATE OR REPLACE PROCEDURE U_PERSONNEL
(
  PERSONNEL_ID IN INTEGER,
  DIVISION_ID IN INTEGER,
  FNAME IN VARCHAR2, 
  NAME IN VARCHAR2, 
  SNAME IN VARCHAR2,
  DATE_ACCEPT IN DATE,
  DATE_SACK IN DATE,
  OLD_PERSONNEL_ID IN INTEGER
)
AS
BEGIN
  UPDATE PERSONNELS 
     SET PERSONNEL_ID=U_PERSONNEL.PERSONNEL_ID,
         DIVISION_ID=U_PERSONNEL.DIVISION_ID,
         FNAME=U_PERSONNEL.FNAME,
         NAME=U_PERSONNEL.NAME,
         SNAME=U_PERSONNEL.SNAME,
         DATE_ACCEPT=U_PERSONNEL.DATE_ACCEPT,
         DATE_SACK=U_PERSONNEL.DATE_SACK
   WHERE PERSONNEL_ID=OLD_PERSONNEL_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT