/* Создание последовательности для таблицы типов точек */

CREATE SEQUENCE SEQ_POINT_TYPES
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы типов точек */


CREATE OR REPLACE FUNCTION GET_POINT_TYPE_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_POINT_TYPES.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы типов точек */

CREATE TABLE POINT_TYPES
(
  POINT_TYPE_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PRIMARY KEY (POINT_TYPE_ID)
)

--

/* Создание просмотра таблицы типов точек */

CREATE VIEW S_POINT_TYPES
AS
  SELECT PT.*
    FROM POINT_TYPES PT

--

/* Создание процедуры создания типа точки */

CREATE OR REPLACE PROCEDURE I_POINT_TYPE
(
  POINT_TYPE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2
)
AS
BEGIN
  INSERT INTO POINT_TYPES (POINT_TYPE_ID,NAME,DESCRIPTION)
       VALUES (POINT_TYPE_ID,NAME,DESCRIPTION);
  COMMIT;
END;

--

/* Создание процедуры изменения типа точки */

CREATE PROCEDURE U_POINT_TYPE
(
  POINT_TYPE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  OLD_POINT_TYPE_ID IN INTEGER
)
AS
BEGIN
  UPDATE POINT_TYPES 
     SET POINT_TYPE_ID=U_POINT_TYPE.POINT_TYPE_ID,
         NAME=U_POINT_TYPE.NAME, 
         DESCRIPTION=U_POINT_TYPE.DESCRIPTION 
   WHERE POINT_TYPE_ID=OLD_POINT_TYPE_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления типа точки */

CREATE PROCEDURE D_POINT_TYPE
(
  OLD_POINT_TYPE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM POINT_TYPES
        WHERE POINT_TYPE_ID=OLD_POINT_TYPE_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT