/* Создание последовательности для таблицы точек */

CREATE SEQUENCE SEQ_POINTS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы точек */

CREATE OR REPLACE FUNCTION GET_POINT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_POINTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы точек */


CREATE TABLE POINTS
(
  POINT_ID INTEGER NOT NULL, 
  POINT_TYPE_ID INTEGER NOT NULL,
  OBJECT_ID INTEGER NOT NULL, 
  NAME INTEGER NOT NULL,
  DESCRIPTION VARCHAR2(250),
  COORDINATE_X FLOAT, 
  COORDINATE_Y FLOAT, 
  COORDINATE_Z FLOAT, 
  DATE_ENTER DATE NOT NULL,
  PRIMARY KEY (POINT_ID),
  FOREIGN KEY (POINT_TYPE_ID) REFERENCES POINT_TYPES (POINT_TYPE_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID)
)

--

/* Создание просмотра таблицы точек */


CREATE OR REPLACE VIEW S_POINTS
AS
  SELECT P.*, PT.NAME AS POINT_TYPE_NAME, O.NAME AS OBJECT_NAME
    FROM POINTS P, POINT_TYPES PT, OBJECTS O
   WHERE P.POINT_TYPE_ID=PT.POINT_TYPE_ID
     AND P.OBJECT_ID=O.OBJECT_ID

--

/* Создание процедуры создания точки */

CREATE OR REPLACE PROCEDURE I_POINT
(
  POINT_ID IN INTEGER,
  POINT_TYPE_ID IN INTEGER,
  OBJECT_ID IN INTEGER,
  NAME IN INTEGER,
  DESCRIPTION IN VARCHAR2,
  COORDINATE_X IN FLOAT,
  COORDINATE_Y IN FLOAT,
  COORDINATE_Z IN FLOAT,
  DATE_ENTER IN DATE
)
AS
BEGIN
  INSERT INTO POINTS (POINT_ID,POINT_TYPE_ID,OBJECT_ID,NAME,DESCRIPTION,
                      COORDINATE_X,COORDINATE_Y,COORDINATE_Z,DATE_ENTER)
       VALUES (POINT_ID,POINT_TYPE_ID,OBJECT_ID,NAME,DESCRIPTION,
            COORDINATE_X,COORDINATE_Y,COORDINATE_Z,DATE_ENTER);
  COMMIT;
END;

--

/* Создание процедуры изменения точки */

CREATE OR REPLACE PROCEDURE U_POINT
(
  POINT_ID IN INTEGER,
  POINT_TYPE_ID IN INTEGER,
  OBJECT_ID IN INTEGER,
  NAME IN INTEGER,
  DESCRIPTION IN VARCHAR2,
  COORDINATE_X IN FLOAT,
  COORDINATE_Y IN FLOAT,
  COORDINATE_Z IN FLOAT,
  DATE_ENTER IN DATE,
  OLD_POINT_ID IN INTEGER
)
AS
BEGIN
  UPDATE POINTS 
     SET POINT_ID=U_POINT.POINT_ID,
	     POINT_TYPE_ID=U_POINT.POINT_TYPE_ID,
	     OBJECT_ID=U_POINT.OBJECT_ID,
         NAME=U_POINT.NAME, 
         DESCRIPTION=U_POINT.DESCRIPTION, 
         COORDINATE_X=U_POINT.COORDINATE_X, 
         COORDINATE_Y=U_POINT.COORDINATE_Y,
		 COORDINATE_Z=U_POINT.COORDINATE_Z,
		 DATE_ENTER=U_POINT.DATE_ENTER
   WHERE POINT_ID=OLD_POINT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления точки */

CREATE OR REPLACE PROCEDURE D_POINT
(
  OLD_POINT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM POINTS
        WHERE POINT_ID=OLD_POINT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT