/* Создание последовательности для таблицы маршрутов */

CREATE SEQUENCE SEQ_ROUTES
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы маршрутов */


CREATE OR REPLACE FUNCTION GET_ROUTE_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_ROUTES.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы маршрутов */

CREATE TABLE ROUTES
(
  ROUTE_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DATE_ROUTE DATE NOT NULL, 
  IS_ACTIVE INTEGER NOT NULL,
  PRIMARY KEY (ROUTE_ID)
)

--

/* Создание просмотра таблицы маршрутов */

CREATE VIEW S_ROUTES
AS
  SELECT R.*
    FROM ROUTES R

--

/* Создание процедуры создания маршрута */

CREATE OR REPLACE PROCEDURE I_ROUTE
(
  ROUTE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DATE_ROUTE IN DATE,
  IS_ACTIVE IN INTEGER
)
AS
BEGIN
  INSERT INTO ROUTES (ROUTE_ID,NAME,DESCRIPTION,DATE_ROUTE,IS_ACTIVE)
       VALUES (ROUTE_ID,NAME,DESCRIPTION,DATE_ROUTE,IS_ACTIVE);
  COMMIT;
END;

--

/* Создание процедуры изменения маршрута */

CREATE OR REPLACE PROCEDURE U_ROUTE
(
  ROUTE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DATE_ROUTE IN DATE,
  IS_ACTIVE IN INTEGER,
  OLD_ROUTE_ID IN INTEGER
)
AS
BEGIN
  UPDATE ROUTES 
     SET ROUTE_ID=U_ROUTE.ROUTE_ID,
         NAME=U_ROUTE.NAME, 
         DESCRIPTION=U_ROUTE.DESCRIPTION,
		 DATE_ROUTE=U_ROUTE.DATE_ROUTE,
		 IS_ACTIVE=U_ROUTE.IS_ACTIVE 
   WHERE ROUTE_ID=OLD_ROUTE_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления маршрута */

CREATE PROCEDURE D_ROUTE
(
  OLD_ROUTE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM ROUTES
        WHERE ROUTE_ID=OLD_ROUTE_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT