/* Создание последовательности для таблицы паспортов точек */

CREATE SEQUENCE SEQ_POINT_PASSPORTS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы паспортов точек */

CREATE OR REPLACE FUNCTION GET_POINT_PASSPORT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_POINT_PASSPORTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы паспортов точек */


CREATE TABLE POINT_PASSPORTS
(
  POINT_PASSPORT_ID INTEGER NOT NULL, 
  POINT_ID INTEGER NOT NULL,
  DATE_CHECKUP DATE NOT NULL,  
  DESCRIPTION VARCHAR2(250),
  PRIMARY KEY (POINT_PASSPORT_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID)
)

--

/* Создание просмотра таблицы паспортов точек */

CREATE OR REPLACE VIEW S_POINT_PASSPORTS
AS
  SELECT PP.*, 
         P.NAME AS POINT_NAME
    FROM POINT_PASSPORTS PP, POINTS P
   WHERE PP.POINT_ID=P.POINT_ID

--

/* Создание процедуры создания паспортов точки */

CREATE OR REPLACE PROCEDURE I_POINT_PASSPORT
(
  POINT_PASSPORT_ID IN INTEGER,
  POINT_ID IN INTEGER,
  DATE_CHECKUP IN DATE,
  DESCRIPTION IN VARCHAR2
)
AS
BEGIN
  INSERT INTO POINT_PASSPORTS (POINT_PASSPORT_ID,POINT_ID,DATE_CHECKUP,DESCRIPTION)
       VALUES (POINT_PASSPORT_ID,POINT_ID,DATE_CHECKUP,DESCRIPTION);
  COMMIT;
END;

--

/* Создание процедуры изменения паспорта точки */

CREATE OR REPLACE PROCEDURE U_POINT_PASSPORT
(
  POINT_PASSPORT_ID IN INTEGER,
  POINT_ID IN INTEGER,
  DATE_CHECKUP IN DATE,
  DESCRIPTION IN VARCHAR2,
  OLD_POINT_PASSPORT_ID IN INTEGER
)
AS
BEGIN
  UPDATE POINT_PASSPORTS 
     SET POINT_PASSPORT_ID=U_POINT_PASSPORT.POINT_PASSPORT_ID,
	     POINT_ID=U_POINT_PASSPORT.POINT_ID,
		 DATE_CHECKUP=U_POINT_PASSPORT.DATE_CHECKUP,
         DESCRIPTION=U_POINT_PASSPORT.DESCRIPTION 
   WHERE POINT_PASSPORT_ID=OLD_POINT_PASSPORT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления точки */

CREATE OR REPLACE PROCEDURE D_POINT_PASSPORT
(
  OLD_POINT_PASSPORT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM POINT_PASSPORTS
        WHERE POINT_PASSPORT_ID=OLD_POINT_PASSPORT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT