/* Создание последовательности для таблицы типов приборов */

CREATE SEQUENCE SEQ_INSTRUMENT_TYPES
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы типов приборов */

CREATE OR REPLACE FUNCTION GET_INSTRUMENT_TYPE_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_INSTRUMENT_TYPES.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы типов приборов */

CREATE TABLE INSTRUMENT_TYPES
(
  INSTRUMENT_TYPE_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PRIMARY KEY (INSTRUMENT_TYPE_ID)
)

--

/* Создание просмотра таблицы типов приборов */

CREATE VIEW S_INSTRUMENT_TYPES
AS
  SELECT IT.*
    FROM INSTRUMENT_TYPES IT

--

/* Создание процедуры создания типа прибора */

CREATE OR REPLACE PROCEDURE I_INSTRUMENT_TYPE
(
  INSTRUMENT_TYPE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2
)
AS
BEGIN
  INSERT INTO INSTRUMENT_TYPES (INSTRUMENT_TYPE_ID,NAME,DESCRIPTION)
       VALUES (INSTRUMENT_TYPE_ID,NAME,DESCRIPTION);
  COMMIT;
END;

--

/* Создание процедуры изменения типа прибора */

CREATE PROCEDURE U_INSTRUMENT_TYPE
(
  INSTRUMENT_TYPE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  OLD_INSTRUMENT_TYPE_ID IN INTEGER
)
AS
BEGIN
  UPDATE INSTRUMENT_TYPES 
     SET INSTRUMENT_TYPE_ID=U_INSTRUMENT_TYPE.INSTRUMENT_TYPE_ID,
         NAME=U_INSTRUMENT_TYPE.NAME, 
         DESCRIPTION=U_INSTRUMENT_TYPE.DESCRIPTION 
   WHERE INSTRUMENT_TYPE_ID=OLD_INSTRUMENT_TYPE_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления типа прибора */

CREATE PROCEDURE D_INSTRUMENT_TYPE
(
  OLD_INSTRUMENT_TYPE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM INSTRUMENT_TYPES
        WHERE INSTRUMENT_TYPE_ID=OLD_INSTRUMENT_TYPE_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT