/* Создание последовательности для таблицы приборов */

CREATE SEQUENCE SEQ_INSTRUMENTS
INCREMENT BY 1 
START WITH 2900 
MAXVALUE 1.0E28 
MINVALUE 2900
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы приборов */

CREATE OR REPLACE FUNCTION GET_INSTRUMENT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_INSTRUMENTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы типов приборов */

CREATE TABLE INSTRUMENTS
(
  INSTRUMENT_ID INTEGER NOT NULL, 
  INSTRUMENT_TYPE_ID INTEGER NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DATE_ENTER DATE NOT NULL,
  SERIAL_NUMBER VARCHAR2(100),
  INVENTORY_NUMBER VARCHAR2(100),
  FREQUENCY_TEST VARCHAR2(250),
  DATE_END DATE,
  CLASS_ACCURACY FLOAT,
  RANGE_MEASURE VARCHAR2(100),  
  PRIMARY KEY (INSTRUMENT_ID),
  FOREIGN KEY (INSTRUMENT_TYPE_ID) REFERENCES INSTRUMENT_TYPES (INSTRUMENT_TYPE_ID)
)

--

/* Создание просмотра таблицы приборов */

CREATE OR REPLACE VIEW S_INSTRUMENTS
AS
  SELECT I.*, IT.NAME AS INSTRUMENT_TYPE_NAME
    FROM INSTRUMENTS I, INSTRUMENT_TYPES IT
   WHERE I.INSTRUMENT_TYPE_ID=IT.INSTRUMENT_TYPE_ID

--

/* Создание процедуры создания прибора */

CREATE OR REPLACE PROCEDURE I_INSTRUMENT
(
  INSTRUMENT_ID IN INTEGER,
  INSTRUMENT_TYPE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DATE_ENTER IN DATE,
  SERIAL_NUMBER IN VARCHAR2,
  INVENTORY_NUMBER IN VARCHAR2,
  FREQUENCY_TEST IN VARCHAR2,
  DATE_END IN DATE,
  CLASS_ACCURACY IN FLOAT,
  RANGE_MEASURE IN VARCHAR2
)
AS
BEGIN
  INSERT INTO INSTRUMENTS (INSTRUMENT_ID,INSTRUMENT_TYPE_ID,NAME,DESCRIPTION,
                           DATE_ENTER,SERIAL_NUMBER,INVENTORY_NUMBER,FREQUENCY_TEST,DATE_END,CLASS_ACCURACY,RANGE_MEASURE)
       VALUES (INSTRUMENT_ID,INSTRUMENT_TYPE_ID,NAME,DESCRIPTION,
               DATE_ENTER,SERIAL_NUMBER,INVENTORY_NUMBER,FREQUENCY_TEST,DATE_END,CLASS_ACCURACY,RANGE_MEASURE);
  COMMIT;
END;

--

/* Создание процедуры изменения прибора */

CREATE OR REPLACE PROCEDURE U_INSTRUMENT
(
  INSTRUMENT_ID IN INTEGER,
  INSTRUMENT_TYPE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DATE_ENTER IN DATE,
  SERIAL_NUMBER IN VARCHAR2,
  INVENTORY_NUMBER IN VARCHAR2,
  FREQUENCY_TEST IN VARCHAR2,
  DATE_END IN DATE,
  CLASS_ACCURACY IN FLOAT,
  RANGE_MEASURE IN VARCHAR2,
  OLD_INSTRUMENT_ID IN INTEGER
)
AS
BEGIN
  UPDATE INSTRUMENTS 
     SET INSTRUMENT_ID=U_INSTRUMENT.INSTRUMENT_ID,
         INSTRUMENT_TYPE_ID=U_INSTRUMENT.INSTRUMENT_TYPE_ID,
         NAME=U_INSTRUMENT.NAME, 
         DESCRIPTION=U_INSTRUMENT.DESCRIPTION, 
         DATE_ENTER=U_INSTRUMENT.DATE_ENTER, 
         SERIAL_NUMBER=U_INSTRUMENT.SERIAL_NUMBER,
		 INVENTORY_NUMBER=U_INSTRUMENT.INVENTORY_NUMBER,
		 FREQUENCY_TEST=U_INSTRUMENT.FREQUENCY_TEST,
		 DATE_END=U_INSTRUMENT.DATE_END,
		 CLASS_ACCURACY=U_INSTRUMENT.CLASS_ACCURACY,
		 RANGE_MEASURE=U_INSTRUMENT.RANGE_MEASURE 
   WHERE INSTRUMENT_ID=OLD_INSTRUMENT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления прибора */

CREATE OR REPLACE PROCEDURE D_INSTRUMENT
(
  OLD_INSTRUMENT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM INSTRUMENTS
        WHERE INSTRUMENT_ID=OLD_INSTRUMENT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT