/* Создание таблицы единицы приборов */

CREATE TABLE INSTRUMENT_UNITS 
(
  INSTRUMENT_ID INTEGER NOT NULL, 
  MEASURE_UNIT_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (INSTRUMENT_ID,MEASURE_UNIT_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID),
  FOREIGN KEY (MEASURE_UNIT_ID) REFERENCES MEASURE_UNITS (MEASURE_UNIT_ID)
)


--

/* Создание просмотра таблицы единицы приборов */

CREATE OR REPLACE VIEW S_INSTRUMENT_UNITS
AS
  SELECT IU.*, I.NAME AS INSTRUMENT_NAME, MU.NAME AS MEASURE_UNIT_NAME
    FROM INSTRUMENT_UNITS IU, INSTRUMENTS I, MEASURE_UNITS MU
   WHERE I.INSTRUMENT_ID=IU.INSTRUMENT_ID AND MU.MEASURE_UNIT_ID=IU.MEASURE_UNIT_ID

--

/* Создание процедуры добавления единицы прибору */

CREATE OR REPLACE PROCEDURE I_INSTRUMENT_UNIT
(
  INSTRUMENT_ID IN INTEGER,
  MEASURE_UNIT_ID IN INTEGER,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO INSTRUMENT_UNITS (INSTRUMENT_ID,MEASURE_UNIT_ID,PRIORITY)
       VALUES (INSTRUMENT_ID,MEASURE_UNIT_ID,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения единицы прибора */

CREATE OR REPLACE PROCEDURE U_INSTRUMENT_UNIT
(
  INSTRUMENT_ID IN INTEGER,
  MEASURE_UNIT_ID IN INTEGER,
  PRIORITY IN INTEGER,
  OLD_INSTRUMENT_ID IN INTEGER,
  OLD_MEASURE_UNIT_ID IN INTEGER
)
AS
BEGIN
  UPDATE INSTRUMENT_UNITS 
     SET INSTRUMENT_ID=U_INSTRUMENT_UNIT.INSTRUMENT_ID,
         MEASURE_UNIT_ID=U_INSTRUMENT_UNIT.MEASURE_UNIT_ID,
		 PRIORITY=U_INSTRUMENT_UNIT.PRIORITY
   WHERE INSTRUMENT_ID=OLD_INSTRUMENT_ID 
     AND MEASURE_UNIT_ID=OLD_MEASURE_UNIT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления единицы прибора */

CREATE PROCEDURE D_INSTRUMENT_UNIT
(
  OLD_INSTRUMENT_ID IN INTEGER,
  OLD_MEASURE_UNIT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM INSTRUMENT_UNITS
        WHERE INSTRUMENT_ID=OLD_INSTRUMENT_ID
          AND MEASURE_UNIT_ID=OLD_MEASURE_UNIT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT