/* Создание таблицы точек маршрутов */

CREATE TABLE ROUTE_POINTS 
(
ROUTE_ID INTEGER NOT NULL, 
POINT_ID INTEGER NOT NULL, 
PRIORITY INTEGER NOT NULL,
PRIMARY KEY (ROUTE_ID,POINT_ID),
FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES (ROUTE_ID),
FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID)
)


--

/* Создание просмотра таблицы точек маршрутов */

CREATE OR REPLACE VIEW S_ROUTE_POINTS
AS
  SELECT RP.*, 
         R.NAME AS ROUTE_NAME, 
		 P.NAME AS POINT_NAME,
		 P.DESCRIPTION AS POINT_DESCRIPTION,
		 O.OBJECT_ID,
		 O.NAME AS OBJECT_NAME
    FROM ROUTE_POINTS RP, ROUTES R, POINTS P, OBJECTS O
   WHERE R.ROUTE_ID=RP.ROUTE_ID 
     AND P.POINT_ID=RP.POINT_ID
	 AND P.OBJECT_ID=O.OBJECT_ID

--

/* Создание процедуры добавления точки маршруту */

CREATE PROCEDURE I_ROUTE_POINT
(
  ROUTE_ID IN INTEGER,
  POINT_ID IN INTEGER,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO ROUTE_POINTS (ROUTE_ID,POINT_ID,PRIORITY)
       VALUES (ROUTE_ID,POINT_ID,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения точки маршрута */

CREATE OR REPLACE PROCEDURE U_ROUTE_POINT
(
  ROUTE_ID IN INTEGER,
  POINT_ID IN INTEGER,
  PRIORITY IN INTEGER,
  OLD_ROUTE_ID IN INTEGER,
  OLD_POINT_ID IN INTEGER
)
AS
BEGIN
  UPDATE ROUTE_POINTS 
     SET ROUTE_ID=U_ROUTE_POINT.ROUTE_ID,
         POINT_ID=U_ROUTE_POINT.POINT_ID,
         PRIORITY=U_ROUTE_POINT.PRIORITY
   WHERE ROUTE_ID=OLD_ROUTE_ID 
     AND POINT_ID=OLD_POINT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления точки маршрута */

CREATE PROCEDURE D_ROUTE_POINT
(
  OLD_ROUTE_ID IN INTEGER,
  OLD_POINT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM ROUTE_POINTS
        WHERE ROUTE_ID=OLD_ROUTE_ID
          AND POINT_ID=OLD_POINT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT