/* Создание таблицы видов измерений маршрутов */

CREATE TABLE MEASURE_TYPE_ROUTES 
(
MEASURE_TYPE_ID INTEGER NOT NULL, 
ROUTE_ID INTEGER NOT NULL, 
PRIORITY INTEGER NOT NULL,
PRIMARY KEY (MEASURE_TYPE_ID,ROUTE_ID),
FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES (ROUTE_ID)
)


--

/* Создание просмотра таблицы видов измерений маршрутов */

CREATE OR REPLACE VIEW S_MEASURE_TYPE_ROUTES
AS
  SELECT MTR.*, 
         MT.NAME AS MEASURE_TYPE_NAME,
		 MT.IS_BASE, 
		 R.NAME AS ROUTE_NAME,
		 R.DESCRIPTION AS ROUTE_DESCRIPTION
    FROM MEASURE_TYPE_ROUTES MTR, MEASURE_TYPES MT, ROUTES R
   WHERE MT.MEASURE_TYPE_ID=MTR.MEASURE_TYPE_ID AND R.ROUTE_ID=MTR.ROUTE_ID

--

/* Создание процедуры добавления вида измерения маршруту */

CREATE PROCEDURE I_MEASURE_TYPE_ROUTE
(
  MEASURE_TYPE_ID IN INTEGER,
  ROUTE_ID IN INTEGER,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO MEASURE_TYPE_ROUTES (MEASURE_TYPE_ID,ROUTE_ID,PRIORITY)
       VALUES (MEASURE_TYPE_ID,ROUTE_ID,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения вида измерения маршрута */

CREATE OR REPLACE PROCEDURE U_MEASURE_TYPE_ROUTE
(
  MEASURE_TYPE_ID IN INTEGER,
  ROUTE_ID IN INTEGER,
  PRIORITY IN INTEGER,
  OLD_MEASURE_TYPE_ID IN INTEGER,
  OLD_ROUTE_ID IN INTEGER
)
AS
BEGIN
  UPDATE MEASURE_TYPE_ROUTES 
     SET MEASURE_TYPE_ID=U_MEASURE_TYPE_ROUTE.MEASURE_TYPE_ID,
         ROUTE_ID=U_MEASURE_TYPE_ROUTE.ROUTE_ID,
         PRIORITY=U_MEASURE_TYPE_ROUTE.PRIORITY
   WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID 
     AND ROUTE_ID=OLD_ROUTE_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления вида измерения маршрута */

CREATE PROCEDURE D_MEASURE_TYPE_ROUTE
(
  OLD_MEASURE_TYPE_ID IN INTEGER,
  OLD_ROUTE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM MEASURE_TYPE_ROUTES
        WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID
          AND ROUTE_ID=OLD_ROUTE_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT