/* Создание таблицы плана */

CREATE TABLE PLANS 
(
  MEASURE_TYPE_ID INTEGER NOT NULL, 
  CYCLE_ID INTEGER NOT NULL, 
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE,
  PRIMARY KEY (MEASURE_TYPE_ID,CYCLE_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (CYCLE_ID) REFERENCES CYCLES (CYCLE_ID)
)

--

/* Создание просмотра таблицы плана */

CREATE OR REPLACE VIEW S_PLANS
AS
  SELECT P.*, 
         MT.NAME AS MEASURE_TYPE_NAME,
		 MT.IS_VISUAL, 
         C.CYCLE_NUM,
		 C.CYCLE_YEAR,
		 C.CYCLE_MONTH,
		 C.DESCRIPTION AS CYCLE_DESCRIPTION,
		 C.IS_CLOSE
    FROM PLANS P, MEASURE_TYPES MT, CYCLES C
   WHERE MT.MEASURE_TYPE_ID=P.MEASURE_TYPE_ID 
     AND C.CYCLE_ID=P.CYCLE_ID

--

/* Создание процедуры создания плана */

CREATE PROCEDURE I_PLAN
(
  MEASURE_TYPE_ID IN INTEGER,
  CYCLE_ID IN INTEGER,
  DATE_BEGIN IN DATE,
  DATE_END IN DATE
)
AS
BEGIN
  INSERT INTO PLANS (MEASURE_TYPE_ID,CYCLE_ID,DATE_BEGIN,DATE_END)
       VALUES (MEASURE_TYPE_ID,CYCLE_ID,DATE_BEGIN,DATE_END);
  COMMIT;
END;

--

/* Создание процедуры изменения плана */

CREATE OR REPLACE PROCEDURE U_PLAN
(
  MEASURE_TYPE_ID IN INTEGER,
  CYCLE_ID IN INTEGER,
  DATE_BEGIN IN DATE,
  DATE_END IN DATE,
  OLD_MEASURE_TYPE_ID IN INTEGER,
  OLD_CYCLE_ID IN INTEGER
)
AS
BEGIN
  UPDATE PLANS 
     SET MEASURE_TYPE_ID=U_PLAN.MEASURE_TYPE_ID,
         CYCLE_ID=U_PLAN.CYCLE_ID,
         DATE_BEGIN=U_PLAN.DATE_BEGIN,
         DATE_END=U_PLAN.DATE_END
   WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID 
     AND CYCLE_ID=OLD_CYCLE_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления плана */

CREATE PROCEDURE D_PLAN
(
  OLD_MEASURE_TYPE_ID IN INTEGER,
  OLD_CYCLE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM PLANS
        WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID
          AND CYCLE_ID=OLD_CYCLE_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT