/* Создание таблицы графиков */

CREATE TABLE GRAPHS
(
  GRAPH_ID INTEGER NOT NULL, 
  JANUARY INTEGER NOT NULL,
  FEBRUARY INTEGER NOT NULL,
  MARCH INTEGER NOT NULL,
  APRIL INTEGER NOT NULL,
  MAY INTEGER NOT NULL,
  JUNE INTEGER NOT NULL,
  JULY INTEGER NOT NULL,
  AUGUST INTEGER NOT NULL,
  SEPTEMBER INTEGER NOT NULL,
  OCTOBER INTEGER NOT NULL,
  NOVEMBER INTEGER NOT NULL,
  DECEMBER INTEGER NOT NULL,
  PRIMARY KEY (GRAPH_ID),
  FOREIGN KEY (GRAPH_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID)
)

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY JANUARY DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY FEBRUARY DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY MARCH DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY APRIL DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY MAY DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY JUNE DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY JULY DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY AUGUST DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY SEPTEMBER DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY OCTOBER DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY NOVEMBER DEFAULT 1

--

/* Обновление поля графиков */

ALTER TABLE GRAPHS
MODIFY DECEMBER DEFAULT 1

--

/* Создание просмотра таблицы графиков */

CREATE VIEW S_GRAPHS
AS
  SELECT G.*, MT.NAME AS MEASURE_TYPE_NAME
    FROM GRAPHS G, MEASURE_TYPES MT
   WHERE G.GRAPH_ID=MT.MEASURE_TYPE_ID

--

/* Создание процедуры создания графика */

CREATE OR REPLACE PROCEDURE I_GRAPH
(
  GRAPH_ID IN INTEGER,
  JANUARY IN INTEGER,
  FEBRUARY IN INTEGER,
  MARCH IN INTEGER,
  APRIL IN INTEGER,
  MAY IN INTEGER,
  JUNE IN INTEGER,
  JULY IN INTEGER,
  AUGUST IN INTEGER,
  SEPTEMBER IN INTEGER,
  OCTOBER IN INTEGER,
  NOVEMBER IN INTEGER,
  DECEMBER IN INTEGER
)
AS
  CNT INTEGER;
  GRAPH_E EXCEPTION;
  ERROR VARCHAR(500);
BEGIN

 SELECT COUNT(*) INTO CNT FROM GRAPHS WHERE GRAPH_ID=I_GRAPH.GRAPH_ID;
  IF (CNT>0) THEN
    ERROR:='Вид измерения уже имеет один график.';
    RAISE GRAPH_E;
  END IF;

  INSERT INTO GRAPHS (GRAPH_ID,
                      JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,
                      JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER)
       VALUES (GRAPH_ID,
               JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,
               JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER);
  COMMIT;
  
EXCEPTION 
  WHEN GRAPH_E THEN 
       RAISE_APPLICATION_ERROR(-20100,ERROR);
END;

--

/* Создание процедуры изменения графика */

CREATE OR REPLACE PROCEDURE U_GRAPH
(
  GRAPH_ID IN INTEGER,
  JANUARY IN INTEGER,
  FEBRUARY IN INTEGER,
  MARCH IN INTEGER,
  APRIL IN INTEGER,
  MAY IN INTEGER,
  JUNE IN INTEGER,
  JULY IN INTEGER,
  AUGUST IN INTEGER,
  SEPTEMBER IN INTEGER,
  OCTOBER IN INTEGER,
  NOVEMBER IN INTEGER,
  DECEMBER IN INTEGER,
  OLD_GRAPH_ID IN INTEGER
)
AS
BEGIN
  UPDATE GRAPHS 
     SET GRAPH_ID=U_GRAPH.GRAPH_ID,
    	  JANUARY=U_GRAPH.JANUARY, 
         FEBRUARY=U_GRAPH.FEBRUARY, 
    	    MARCH=U_GRAPH.MARCH, 
    	    APRIL=U_GRAPH.APRIL, 
    	      MAY=U_GRAPH.MAY, 
    	     JUNE=U_GRAPH.JUNE, 
    	     JULY=U_GRAPH.JULY, 
    	   AUGUST=U_GRAPH.AUGUST, 
    	SEPTEMBER=U_GRAPH.SEPTEMBER, 
    	  OCTOBER=U_GRAPH.OCTOBER, 
    	 NOVEMBER=U_GRAPH.NOVEMBER, 
    	 DECEMBER=U_GRAPH.DECEMBER 
   WHERE GRAPH_ID=OLD_GRAPH_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления графика */

CREATE PROCEDURE D_GRAPH
(
  OLD_GRAPH_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM GRAPHS
        WHERE GRAPH_ID=OLD_GRAPH_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT