/* Создание последовательности для таблицы параметров */

CREATE SEQUENCE SEQ_PARAMS
INCREMENT BY 1 
START WITH 2900 
MAXVALUE 1.0E28 
MINVALUE 2900
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы параметров */

CREATE OR REPLACE FUNCTION GET_PARAM_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_PARAMS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы параметров */

CREATE TABLE PARAMS
(
  PARAM_ID INTEGER NOT NULL, 
  ALGORITHM_ID INTEGER,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PARAM_TYPE INTEGER NOT NULL,
  FORMAT VARCHAR2(100),
  PRIMARY KEY (PARAM_ID),
  FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHMS (ALGORITHM_ID)
)

--

/* Создание просмотра таблицы параметров */

CREATE OR REPLACE VIEW S_PARAMS
AS
  SELECT P.*, 
         A.NAME AS ALGORITHM_NAME
    FROM PARAMS P, ALGORITHMS A 
   WHERE P.ALGORITHM_ID=A.ALGORITHM_ID (+)


--

/* Создание процедуры создания параметра */

CREATE OR REPLACE PROCEDURE I_PARAM
(
  PARAM_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PARAM_TYPE IN INTEGER,
  FORMAT IN VARCHAR2
)
AS
BEGIN
  INSERT INTO PARAMS (PARAM_ID,ALGORITHM_ID,NAME,DESCRIPTION,PARAM_TYPE,FORMAT)
       VALUES (PARAM_ID,ALGORITHM_ID,NAME,DESCRIPTION,PARAM_TYPE,FORMAT);
  COMMIT;
END;

--

/* Создание процедуры изменения параметра */


CREATE OR REPLACE PROCEDURE U_PARAM
(
  PARAM_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PARAM_TYPE IN INTEGER,
  FORMAT IN VARCHAR2,
  OLD_PARAM_ID IN INTEGER
)
AS
BEGIN
  UPDATE PARAMS 
     SET PARAM_ID=U_PARAM.PARAM_ID,
         ALGORITHM_ID=U_PARAM.ALGORITHM_ID,
         NAME=U_PARAM.NAME,
         DESCRIPTION=U_PARAM.DESCRIPTION,
         PARAM_TYPE=U_PARAM.PARAM_TYPE,
		 FORMAT=U_PARAM.FORMAT
   WHERE PARAM_ID=OLD_PARAM_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления параметра */

CREATE PROCEDURE D_PARAM
(
  OLD_PARAM_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM PARAMS
        WHERE PARAM_ID=OLD_PARAM_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT