/* Создание последовательности для таблицы компонентов преобразователей */

CREATE SEQUENCE SEQ_COMPONENTS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы компонентов преобразователей */

CREATE OR REPLACE FUNCTION GET_COMPONENT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_COMPONENTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы компонентов преобразователей */

CREATE TABLE COMPONENTS
(
  COMPONENT_ID INTEGER NOT NULL,
  CONVERTER_ID INTEGER NOT NULL,
  PARAM_ID INTEGER NOT NULL,   
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PRIMARY KEY (COMPONENT_ID),
  FOREIGN KEY (CONVERTER_ID) REFERENCES CONVERTERS (CONVERTER_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID)
)

--

/* Создание просмотра таблицы компонентов преобразователей */

CREATE OR REPLACE VIEW S_COMPONENTS
AS
  SELECT D.*,
         C.NAME AS CONVERTER_NAME,
		 P.NAME AS PARAM_NAME
    FROM COMPONENTS D, CONVERTERS C, PARAMS P
   WHERE D.CONVERTER_ID=C.CONVERTER_ID
     AND D.PARAM_ID=P.PARAM_ID
ORDER BY D.NAME	

--

/* Создание процедуры создания компонента преобразователя */

CREATE OR REPLACE PROCEDURE I_COMPONENT
(
  COMPONENT_ID IN INTEGER,
  CONVERTER_ID IN INTEGER,
  PARAM_ID IN INTEGER,   
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2
)
AS
BEGIN
  INSERT INTO COMPONENTS (COMPONENT_ID,CONVERTER_ID,PARAM_ID,NAME,DESCRIPTION)
       VALUES (COMPONENT_ID,CONVERTER_ID,PARAM_ID,NAME,DESCRIPTION);
  COMMIT;
END;

--

/* Создание процедуры изменения компонента преобразователя */


CREATE OR REPLACE PROCEDURE U_COMPONENT
(
  COMPONENT_ID IN INTEGER,
  CONVERTER_ID IN INTEGER,
  PARAM_ID IN INTEGER,   
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  OLD_COMPONENT_ID IN INTEGER
)
AS
BEGIN
  UPDATE COMPONENTS 
     SET COMPONENT_ID=U_COMPONENT.COMPONENT_ID,
         CONVERTER_ID=U_COMPONENT.CONVERTER_ID,
         PARAM_ID=U_COMPONENT.PARAM_ID,
         NAME=U_COMPONENT.NAME,
         DESCRIPTION=U_COMPONENT.DESCRIPTION
   WHERE COMPONENT_ID=OLD_COMPONENT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления компонента преобразователя */

CREATE PROCEDURE D_COMPONENT
(
  OLD_COMPONENT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM COMPONENTS
        WHERE COMPONENT_ID=OLD_COMPONENT_ID;
  COMMIT;        
END;

--

/* Создание индекса на преобразователь компонента преобразователя */

CREATE INDEX IDX_COMPONENTS_1
 ON COMPONENTS(CONVERTER_ID)

--

/* Создание индекса на параметр компонента преобразователя */

CREATE INDEX IDX_COMPONENTS_2
 ON COMPONENTS(PARAM_ID)

--

/* Фиксация изменений БД */

COMMIT