/* Создание последовательности для таблицы полевого журнала */

CREATE SEQUENCE SEQ_JOURNAL_FIELDS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора таблицы полевого журнала */

CREATE OR REPLACE FUNCTION GET_JOURNAL_FIELD_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_JOURNAL_FIELDS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы полевого журнала */

CREATE TABLE JOURNAL_FIELDS
(
  JOURNAL_FIELD_ID INTEGER NOT NULL,
  CYCLE_ID INTEGER NOT NULL,
  POINT_ID INTEGER NOT NULL,
  PARAM_ID INTEGER NOT NULL,
  INSTRUMENT_ID INTEGER,
  MEASURE_UNIT_ID INTEGER,
  VALUE FLOAT NOT NULL,
  WHO_ENTER INTEGER NOT NULL,
  DATE_ENTER DATE NOT NULL,
  WHO_CONFIRM INTEGER,
  DATE_CONFIRM DATE,
  DATE_OBSERVATION DATE NOT NULL,
  GROUP_ID VARCHAR2(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  IS_BASE INTEGER NOT NULL,
  MEASURE_TYPE_ID NOT NULL,
  JOURNAL_NUM VARCHAR2(100),
  NOTE VARCHAR2(250),
  PARENT_ID INTEGER,
  IS_CHECK INTEGER NOT NULL,
  PRIMARY KEY (JOURNAL_FIELD_ID),
  FOREIGN KEY (CYCLE_ID) REFERENCES CYCLES (CYCLE_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID),
  FOREIGN KEY (MEASURE_UNIT_ID) REFERENCES MEASURE_UNITS (MEASURE_UNIT_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (WHO_ENTER) REFERENCES PERSONNELS (PERSONNEL_ID),
  FOREIGN KEY (WHO_CONFIRM) REFERENCES PERSONNELS (PERSONNEL_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES JOURNAL_FIELDS (JOURNAL_FIELD_ID)
) 

--

/* Создание индекса по дате наблюдения полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_1
 ON JOURNAL_FIELDS(DATE_OBSERVATION)

--

/* Создание индекса по группе полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_2
 ON JOURNAL_FIELDS(GROUP_ID)

--

/* Создание индекса по приоритету полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_3
 ON JOURNAL_FIELDS(PRIORITY)

--

/* Создание индекса по параметру полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_4
 ON JOURNAL_FIELDS(PARAM_ID)

--

/* Создание индекса по циклу полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_5
 ON JOURNAL_FIELDS(CYCLE_ID)

--

/* Создание индекса по прибору полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_6
 ON JOURNAL_FIELDS(INSTRUMENT_ID)

--

/* Создание индекса по виду измерения полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_7
 ON JOURNAL_FIELDS(MEASURE_TYPE_ID)

--

/* Создание индекса по единице измерения полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_8
 ON JOURNAL_FIELDS(MEASURE_UNIT_ID)

--

/* Создание индекса по точке полевого журнала */

CREATE INDEX IDX_JOURNAL_FIELDS_9
 ON JOURNAL_FIELDS(POINT_ID)

--

/* Создание индекса по месяцу полевого журнала */

CREATE BITMAP INDEX IDX_JOURNAL_FIELDS_10
 ON JOURNAL_FIELDS (EXTRACT(MONTH FROM DATE_OBSERVATION))

--

/* Создание индекса по году полевого журнала */

CREATE BITMAP INDEX IDX_JOURNAL_FIELDS_11
 ON JOURNAL_FIELDS (EXTRACT(YEAR FROM DATE_OBSERVATION))

--

/* Создание просмотра таблицы полевого журнала */

CREATE OR REPLACE VIEW S_JOURNAL_FIELDS
AS
  SELECT JF.*, 
         C.CYCLE_NUM,
         PT.NAME AS POINT_NAME,
         PR.NAME AS PARAM_NAME,
		 MT.NAME AS MEASURE_TYPE_NAME,
         P1.FNAME||' '||P1.NAME||' '||P1.SNAME AS WHO_ENTER_NAME,
         P2.FNAME||' '||P2.NAME||' '||P2.SNAME AS WHO_CONFIRM_NAME,
		 I.NAME AS INSTRUMENT_NAME,
		 MU.NAME AS MEASURE_UNIT_NAME
    FROM JOURNAL_FIELDS JF, CYCLES C, POINTS PT, PARAMS PR, MEASURE_TYPES MT, 
         PERSONNELS P1, PERSONNELS P2, INSTRUMENTS I, MEASURE_UNITS MU
   WHERE JF.POINT_ID=PT.POINT_ID
     AND JF.PARAM_ID=PR.PARAM_ID
     AND JF.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
     AND JF.WHO_ENTER=P1.PERSONNEL_ID
	 AND JF.CYCLE_ID=C.CYCLE_ID
     AND JF.WHO_CONFIRM=P2.PERSONNEL_ID (+)
	 AND JF.INSTRUMENT_ID=I.INSTRUMENT_ID (+)
	 AND JF.MEASURE_UNIT_ID=MU.MEASURE_UNIT_ID (+)

--

/* Создание процедуры утверждения полевого журнала */

CREATE OR REPLACE PROCEDURE CONFIRM_JOURNAL_FIELD
(
  JOURNAL_FIELD_ID IN INTEGER
)
AS
BEGIN
  COMMIT;							    
END;

--

/* Создание процедуры создания записи в полевом журнале */

CREATE OR REPLACE PROCEDURE I_JOURNAL_FIELD
(
  JOURNAL_FIELD_ID IN INTEGER,
  CYCLE_ID IN INTEGER,
  POINT_ID IN INTEGER,
  PARAM_ID IN INTEGER,
  INSTRUMENT_ID IN INTEGER,
  MEASURE_UNIT_ID IN INTEGER,
  VALUE IN FLOAT,
  WHO_ENTER IN INTEGER,
  DATE_ENTER IN DATE,
  WHO_CONFIRM IN INTEGER,
  DATE_CONFIRM IN DATE,
  DATE_OBSERVATION IN DATE,
  GROUP_ID IN VARCHAR2,
  PRIORITY IN INTEGER,
  IS_BASE IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  JOURNAL_NUM IN VARCHAR2,
  NOTE IN VARCHAR2,
  PARENT_ID IN INTEGER,
  IS_CHECK IN INTEGER
)
AS
BEGIN
  INSERT INTO JOURNAL_FIELDS (JOURNAL_FIELD_ID,CYCLE_ID,POINT_ID,PARAM_ID,
                             INSTRUMENT_ID,MEASURE_UNIT_ID,VALUE,
                             WHO_ENTER,DATE_ENTER,WHO_CONFIRM,DATE_CONFIRM,
							 DATE_OBSERVATION,GROUP_ID,PRIORITY,IS_BASE,
							 MEASURE_TYPE_ID,JOURNAL_NUM,NOTE,PARENT_ID,IS_CHECK)
       VALUES (JOURNAL_FIELD_ID,CYCLE_ID,POINT_ID,PARAM_ID,
	           INSTRUMENT_ID,MEASURE_UNIT_ID,VALUE,
               WHO_ENTER,DATE_ENTER,WHO_CONFIRM,DATE_CONFIRM,
			   DATE_OBSERVATION,GROUP_ID,PRIORITY,IS_BASE,
			   MEASURE_TYPE_ID,JOURNAL_NUM,NOTE,PARENT_ID,IS_CHECK);
  COMMIT;
  CONFIRM_JOURNAL_FIELD (JOURNAL_FIELD_ID);
END;

--

/* Создание процедуры изменения записи в полевом журнале */

CREATE OR REPLACE PROCEDURE U_JOURNAL_FIELD
(
  JOURNAL_FIELD_ID IN INTEGER,
  CYCLE_ID IN INTEGER,
  POINT_ID IN INTEGER,
  PARAM_ID IN INTEGER,
  INSTRUMENT_ID IN INTEGER,
  MEASURE_UNIT_ID IN INTEGER,
  VALUE IN FLOAT,
  WHO_ENTER IN INTEGER,
  DATE_ENTER IN DATE,
  WHO_CONFIRM IN INTEGER,
  DATE_CONFIRM IN DATE,
  DATE_OBSERVATION IN DATE,
  GROUP_ID IN VARCHAR,
  PRIORITY IN INTEGER,
  IS_BASE IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  JOURNAL_NUM IN VARCHAR2,
  NOTE IN VARCHAR2,
  PARENT_ID IN INTEGER,
  IS_CHECK IN INTEGER,
  OLD_JOURNAL_FIELD_ID IN INTEGER
)
AS
BEGIN
  UPDATE JOURNAL_FIELDS 
     SET JOURNAL_FIELD_ID=U_JOURNAL_FIELD.JOURNAL_FIELD_ID,
         CYCLE_ID=U_JOURNAL_FIELD.CYCLE_ID,
         POINT_ID=U_JOURNAL_FIELD.POINT_ID,
         PARAM_ID=U_JOURNAL_FIELD.PARAM_ID,
         INSTRUMENT_ID=U_JOURNAL_FIELD.INSTRUMENT_ID,
         MEASURE_UNIT_ID=U_JOURNAL_FIELD.MEASURE_UNIT_ID,
         VALUE=U_JOURNAL_FIELD.VALUE,
         WHO_ENTER=U_JOURNAL_FIELD.WHO_ENTER,
         DATE_ENTER=U_JOURNAL_FIELD.DATE_ENTER,
         WHO_CONFIRM=U_JOURNAL_FIELD.WHO_CONFIRM,
         DATE_CONFIRM=U_JOURNAL_FIELD.DATE_CONFIRM,
         GROUP_ID=U_JOURNAL_FIELD.GROUP_ID,
         PRIORITY=U_JOURNAL_FIELD.PRIORITY,
         DATE_OBSERVATION=U_JOURNAL_FIELD.DATE_OBSERVATION,
		 IS_BASE=U_JOURNAL_FIELD.IS_BASE,
		 MEASURE_TYPE_ID=U_JOURNAL_FIELD.MEASURE_TYPE_ID,
		 JOURNAL_NUM=U_JOURNAL_FIELD.JOURNAL_NUM,
		 NOTE=U_JOURNAL_FIELD.NOTE,
		 PARENT_ID=U_JOURNAL_FIELD.PARENT_ID,
		 IS_CHECK=U_JOURNAL_FIELD.IS_CHECK
   WHERE JOURNAL_FIELD_ID=OLD_JOURNAL_FIELD_ID;
  COMMIT;
  CONFIRM_JOURNAL_FIELD(OLD_JOURNAL_FIELD_ID);        
END;

--

/* Создание процедуры удаления записи в полевом журнале */

CREATE OR REPLACE PROCEDURE D_JOURNAL_FIELD
(
  OLD_JOURNAL_FIELD_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM JOURNAL_FIELDS
        WHERE JOURNAL_FIELD_ID=OLD_JOURNAL_FIELD_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT