/* Создание просмотра персонала видов измерения */

CREATE OR REPLACE VIEW S_MEASURE_TYPE_PERSONNELS
AS
  SELECT MTR.MEASURE_TYPE_ID,
         MT.NAME AS MEASURE_TYPE_NAME, 
         MTR.ROUTE_ID, 
		 R.NAME AS ROUTE_NAME, 
		 PR.PERSONNEL_ID,
		 P.FNAME||' '||P.NAME||' '||P.SNAME AS PERSONNEL_NAME
    FROM MEASURE_TYPE_ROUTES MTR, 
	     MEASURE_TYPES MT,
		 ROUTES R, 
		 PERSONNEL_ROUTES PR,
		 PERSONNELS P
   WHERE MTR.ROUTE_ID=R.ROUTE_ID
     AND MTR.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
     AND R.ROUTE_ID=PR.ROUTE_ID
	 AND PR.PERSONNEL_ID=P.PERSONNEL_ID  

--

/* Фиксация изменений БД */

COMMIT
