/* Создание последовательности для таблицы файловых отчетов */

CREATE SEQUENCE SEQ_FILE_REPORTS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы файловых отчетов */

CREATE OR REPLACE FUNCTION GET_FILE_REPORT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_FILE_REPORTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы файловых отчетов */

CREATE TABLE FILE_REPORTS
(
  FILE_REPORT_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  FILE_NAME VARCHAR2(250) NOT NULL,
  MODULE_NAME VARCHAR2(100) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  MENU VARCHAR2(250) NOT NULL,
  PRIMARY KEY (FILE_REPORT_ID)
)

--

/* Создание просмотра таблицы файловых отчетов */

CREATE OR REPLACE VIEW S_FILE_REPORTS
AS
  SELECT P.*
    FROM FILE_REPORTS P

--

/* Создание процедуры создания файлового отчета */

CREATE OR REPLACE PROCEDURE I_FILE_REPORT
(
  FILE_REPORT_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  FILE_NAME IN VARCHAR2,
  MODULE_NAME IN VARCHAR2,
  PRIORITY IN INTEGER,
  MENU IN VARCHAR2
)
AS
BEGIN
  INSERT INTO FILE_REPORTS (FILE_REPORT_ID,NAME,DESCRIPTION,FILE_NAME,MODULE_NAME,PRIORITY,MENU)
       VALUES (FILE_REPORT_ID,NAME,DESCRIPTION,FILE_NAME,MODULE_NAME,PRIORITY,MENU);
  COMMIT;
END;

--

/* Создание процедуры изменения файлового отчета */


CREATE OR REPLACE PROCEDURE U_FILE_REPORT
(
  FILE_REPORT_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  FILE_NAME IN VARCHAR2,
  MODULE_NAME IN VARCHAR2,
  PRIORITY IN INTEGER,
  MENU IN VARCHAR2,
  OLD_FILE_REPORT_ID IN INTEGER
)
AS
BEGIN
  UPDATE FILE_REPORTS 
     SET FILE_REPORT_ID=U_FILE_REPORT.FILE_REPORT_ID,
         NAME=U_FILE_REPORT.NAME,
         DESCRIPTION=U_FILE_REPORT.DESCRIPTION,
         FILE_NAME=U_FILE_REPORT.FILE_NAME,
		 MODULE_NAME=U_FILE_REPORT.MODULE_NAME,
         PRIORITY=U_FILE_REPORT.PRIORITY,
		 MENU=U_FILE_REPORT.MENU
   WHERE FILE_REPORT_ID=OLD_FILE_REPORT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления файлового отчета */

CREATE OR REPLACE PROCEDURE D_FILE_REPORT
(
  OLD_FILE_REPORT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM FILE_REPORTS
        WHERE FILE_REPORT_ID=OLD_FILE_REPORT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT