/* Создание последовательности для таблицы базовых отчетов */

CREATE SEQUENCE SEQ_BASE_REPORTS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы базовых отчетов */

CREATE OR REPLACE FUNCTION GET_BASE_REPORT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_BASE_REPORTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы базовых отчетов */

CREATE TABLE BASE_REPORTS
(
  BASE_REPORT_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  REPORT BLOB,
  PRIORITY INTEGER,
  MENU VARCHAR2(250),
  PRIMARY KEY (BASE_REPORT_ID)
)

--

/* Создание просмотра таблицы базовых отчетов */

CREATE OR REPLACE VIEW S_BASE_REPORTS
AS
  SELECT B.*, (CASE WHEN DBMS_LOB.GETLENGTH(REPORT)>0 THEN 1 ELSE 0 END) AS REPORT_EXISTS 
    FROM BASE_REPORTS B

--

/* Создание процедуры создания базового отчета */

CREATE OR REPLACE PROCEDURE I_BASE_REPORT
(
  BASE_REPORT_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  REPORT IN BLOB,
  PRIORITY IN INTEGER,
  MENU IN VARCHAR2
)
AS
  CNT INTEGER;
  BASE_REPORTS_E EXCEPTION;
  ERROR VARCHAR(500);
BEGIN

  SELECT COUNT(*) INTO CNT FROM BASE_REPORTS WHERE UPPER(NAME)=UPPER(I_BASE_REPORT.NAME);
  IF (CNT>0) THEN
    ERROR:='Такое наименование уже существует.';
    RAISE BASE_REPORTS_E;
  END IF;

  INSERT INTO BASE_REPORTS (BASE_REPORT_ID,NAME,DESCRIPTION,REPORT,PRIORITY,MENU)
       VALUES (BASE_REPORT_ID,NAME,DESCRIPTION,REPORT,PRIORITY,MENU);
	   
  COMMIT;
  
EXCEPTION
  WHEN BASE_REPORTS_E THEN 
       RAISE_APPLICATION_ERROR(-20100,ERROR);
END;

--

/* Создание процедуры изменения базового отчета */

CREATE OR REPLACE PROCEDURE U_BASE_REPORT
(
  BASE_REPORT_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  REPORT IN BLOB,
  PRIORITY IN INTEGER,
  MENU IN VARCHAR2,
  OLD_BASE_REPORT_ID IN INTEGER
)
AS
  CNT INTEGER;
  BASE_REPORTS_E EXCEPTION;
  ERROR VARCHAR(500);
BEGIN

  SELECT COUNT(*) INTO CNT FROM BASE_REPORTS 
   WHERE UPPER(NAME)=UPPER(U_BASE_REPORT.NAME) 
     AND BASE_REPORT_ID<>U_BASE_REPORT.OLD_BASE_REPORT_ID;
  IF (CNT>0) THEN
    ERROR:='Такое наименование уже существует.';
    RAISE BASE_REPORTS_E;
  END IF;

  UPDATE BASE_REPORTS 
     SET BASE_REPORT_ID=U_BASE_REPORT.BASE_REPORT_ID,
         NAME=U_BASE_REPORT.NAME,
         DESCRIPTION=U_BASE_REPORT.DESCRIPTION,
         REPORT=U_BASE_REPORT.REPORT,
         PRIORITY=U_BASE_REPORT.PRIORITY,
		 MENU=U_BASE_REPORT.MENU
   WHERE BASE_REPORT_ID=OLD_BASE_REPORT_ID;
   
  COMMIT;

EXCEPTION
  WHEN BASE_REPORTS_E THEN 
       RAISE_APPLICATION_ERROR(-20100,ERROR);
END;

--

/* Создание процедуры удаления базового отчета */

CREATE OR REPLACE PROCEDURE D_BASE_REPORT
(
  OLD_BASE_REPORT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM BASE_REPORTS
        WHERE BASE_REPORT_ID=OLD_BASE_REPORT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT