/* Создание последовательности для таблицы отчетов интерфейсов */

CREATE SEQUENCE SEQ_INTERFACE_REPORTS
INCREMENT BY 1 
START WITH 2900 
MAXVALUE 1.0E28 
MINVALUE 2900
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы отчетов интерфейсов */

CREATE OR REPLACE FUNCTION GET_INTERFACE_REPORT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_INTERFACE_REPORTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы отчетов интерфейсов */

CREATE TABLE INTERFACE_REPORTS
(
  INTERFACE_REPORT_ID INTEGER NOT NULL, 
  BASE_REPORT_ID INTEGER NOT NULL,
  INTERFACE VARCHAR2(250) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (INTERFACE_REPORT_ID),
  FOREIGN KEY (BASE_REPORT_ID) REFERENCES BASE_REPORTS (BASE_REPORT_ID)
)

--

/* Создание просмотра таблицы отчетов интерфейсов */

CREATE OR REPLACE VIEW S_INTERFACE_REPORTS
AS
  SELECT RP.*, 
         BR.NAME AS BASE_REPORT_NAME
    FROM INTERFACE_REPORTS RP, BASE_REPORTS BR 
   WHERE RP.BASE_REPORT_ID=BR.BASE_REPORT_ID

--

/* Создание процедуры создания отчета интерфейса */

CREATE OR REPLACE PROCEDURE I_INTERFACE_REPORT
(
  INTERFACE_REPORT_ID IN INTEGER,
  BASE_REPORT_ID IN INTEGER,
  INTERFACE IN VARCHAR2,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO INTERFACE_REPORTS (INTERFACE_REPORT_ID,BASE_REPORT_ID,INTERFACE,PRIORITY)
       VALUES (INTERFACE_REPORT_ID,BASE_REPORT_ID,INTERFACE,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения отчета интерфейса */

CREATE OR REPLACE PROCEDURE U_INTERFACE_REPORT
(
  INTERFACE_REPORT_ID IN INTEGER,
  BASE_REPORT_ID IN INTEGER,
  INTERFACE IN VARCHAR2,
  PRIORITY IN INTEGER,
  OLD_INTERFACE_REPORT_ID IN INTEGER
)
AS
BEGIN
  UPDATE INTERFACE_REPORTS 
     SET INTERFACE_REPORT_ID=U_INTERFACE_REPORT.INTERFACE_REPORT_ID,
         BASE_REPORT_ID=U_INTERFACE_REPORT.BASE_REPORT_ID,
         INTERFACE=U_INTERFACE_REPORT.INTERFACE,
         PRIORITY=U_INTERFACE_REPORT.PRIORITY
   WHERE INTERFACE_REPORT_ID=OLD_INTERFACE_REPORT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления отчета интерфейса */

CREATE PROCEDURE D_INTERFACE_REPORT
(
  OLD_INTERFACE_REPORT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM INTERFACE_REPORTS
        WHERE INTERFACE_REPORT_ID=OLD_INTERFACE_REPORT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT