/* Создание просмотра точек видов измерения */

CREATE OR REPLACE VIEW S_MEASURE_TYPE_POINTS
AS
  SELECT MT.MEASURE_TYPE_ID,
         MT.NAME AS MEASURE_TYPE_NAME,
		 R.ROUTE_ID,
		 R.NAME AS ROUTE_NAME,
		 P.POINT_ID,
		 P.NAME AS POINT_NAME,
		 P.OBJECT_ID,
		 PL.CYCLE_ID,
		 PR.PERSONNEL_ID
    FROM MEASURE_TYPES MT,
	     MEASURE_TYPE_ROUTES MTR,
		 ROUTES R,
		 ROUTE_POINTS RP,
		 POINTS P,
		 PERSONNEL_ROUTES PR,
		 PLANS PL
   WHERE MT.MEASURE_TYPE_ID=MTR.MEASURE_TYPE_ID
     AND MTR.ROUTE_ID=R.ROUTE_ID
	 AND R.ROUTE_ID=RP.ROUTE_ID
	 AND RP.POINT_ID=P.POINT_ID
	 AND R.ROUTE_ID=PR.ROUTE_ID
	 AND MT.MEASURE_TYPE_ID=PL.MEASURE_TYPE_ID
ORDER BY MTR.PRIORITY, RP.PRIORITY  	
 

--

/* Фиксация изменений БД */

COMMIT
