/* Создание таблицы приборов параметров */

CREATE TABLE PARAM_INSTRUMENTS 
(
  PARAM_ID INTEGER NOT NULL, 
  INSTRUMENT_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (PARAM_ID,INSTRUMENT_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID)
)

--

/* Создание просмотра таблицы приборов параметров */

CREATE OR REPLACE VIEW S_PARAM_INSTRUMENTS
AS
  SELECT PI.*,
         P.NAME AS PARAM_NAME,
		 I.NAME AS INSTRUMENT_NAME  
    FROM PARAM_INSTRUMENTS PI, PARAMS P, INSTRUMENTS I   
   WHERE PI.PARAM_ID=P.PARAM_ID 
     AND PI.INSTRUMENT_ID=I.INSTRUMENT_ID
--

/* Создание процедуры добавления прибора параметру */

CREATE PROCEDURE I_PARAM_INSTRUMENT
(
  PARAM_ID IN INTEGER,
  INSTRUMENT_ID IN INTEGER,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO PARAM_INSTRUMENTS (PARAM_ID,INSTRUMENT_ID,PRIORITY)
       VALUES (PARAM_ID,INSTRUMENT_ID,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения прибора параметра */

CREATE OR REPLACE PROCEDURE U_PARAM_INSTRUMENT
(
  PARAM_ID IN INTEGER,
  INSTRUMENT_ID IN INTEGER,
  PRIORITY IN INTEGER,
  OLD_PARAM_ID IN INTEGER,
  OLD_INSTRUMENT_ID IN INTEGER
)
AS
BEGIN
  UPDATE PARAM_INSTRUMENTS 
     SET PARAM_ID=U_PARAM_INSTRUMENT.PARAM_ID,
         INSTRUMENT_ID=U_PARAM_INSTRUMENT.INSTRUMENT_ID,
         PRIORITY=U_PARAM_INSTRUMENT.PRIORITY
   WHERE PARAM_ID=OLD_PARAM_ID 
     AND INSTRUMENT_ID=OLD_INSTRUMENT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления прибора параметра */

CREATE PROCEDURE D_PARAM_INSTRUMENT
(
  OLD_PARAM_ID IN INTEGER,
  OLD_INSTRUMENT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM PARAM_INSTRUMENTS
        WHERE PARAM_ID=OLD_PARAM_ID
          AND INSTRUMENT_ID=OLD_INSTRUMENT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT