/* Изменение процедуры удаления вида измерения */

CREATE OR REPLACE PROCEDURE D_MEASURE_TYPE
(
  OLD_MEASURE_TYPE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM MEASURE_TYPE_ALGORITHMS
        WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID;

  DELETE FROM MEASURE_TYPE_PARAMS
        WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID;

  DELETE FROM MEASURE_TYPE_ROUTES
        WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID;

  DELETE FROM PLANS
        WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID;
		
  DELETE FROM MEASURE_TYPES CASCADE  
        WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID;
		
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT
