/* Создание последовательности для таблицы документов */

CREATE SEQUENCE SEQ_DOCUMENTS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы документов */

CREATE OR REPLACE FUNCTION GET_DOCUMENT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_DOCUMENTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы документов */

CREATE TABLE DOCUMENTS
(
  DOCUMENT_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  FILE_NAME VARCHAR2(250) NOT NULL,
  PRIMARY KEY (DOCUMENT_ID)
)

--

/* Создание просмотра таблицы документов */

CREATE VIEW S_DOCUMENTS
AS
  SELECT D.*
    FROM DOCUMENTS D


--

/* Создание процедуры создания документа */

CREATE OR REPLACE PROCEDURE I_DOCUMENT
(
  DOCUMENT_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  FILE_NAME IN VARCHAR2
)
AS
BEGIN
  INSERT INTO DOCUMENTS (DOCUMENT_ID,NAME,DESCRIPTION,FILE_NAME)
       VALUES (DOCUMENT_ID,NAME,DESCRIPTION,FILE_NAME);
  COMMIT;
END;

--

/* Создание процедуры изменения документа */


CREATE OR REPLACE PROCEDURE U_DOCUMENT
(
  DOCUMENT_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  FILE_NAME IN VARCHAR2,
  OLD_DOCUMENT_ID IN INTEGER
)
AS
BEGIN
  UPDATE DOCUMENTS 
     SET DOCUMENT_ID=U_DOCUMENT.DOCUMENT_ID,
         NAME=U_DOCUMENT.NAME,
         DESCRIPTION=U_DOCUMENT.DESCRIPTION,
         FILE_NAME=U_DOCUMENT.FILE_NAME
   WHERE DOCUMENT_ID=OLD_DOCUMENT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления документа */

CREATE PROCEDURE D_DOCUMENT
(
  OLD_DOCUMENT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM DOCUMENTS
        WHERE DOCUMENT_ID=OLD_DOCUMENT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT