/* Создание таблицы документов точек */

CREATE TABLE POINT_DOCUMENTS 
(
POINT_ID INTEGER NOT NULL, 
DOCUMENT_ID INTEGER NOT NULL, 
PRIORITY INTEGER NOT NULL,
PRIMARY KEY (POINT_ID,DOCUMENT_ID),
FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID),
FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (DOCUMENT_ID)
)


--

/* Создание просмотра таблицы документов точек */

CREATE OR REPLACE VIEW S_POINT_DOCUMENTS
AS
  SELECT PD.*, 
         P.NAME AS POINT_NAME, 
		 D.NAME AS DOCUMENT_NAME,
		 D.DESCRIPTION AS DOCUMENT_DESCRIPTION,
		 D.FILE_NAME AS FILE_NAME
    FROM POINT_DOCUMENTS PD, POINTS P, DOCUMENTS D
   WHERE P.POINT_ID=PD.POINT_ID AND D.DOCUMENT_ID=PD.DOCUMENT_ID

--

/* Создание процедуры добавления документов точкам */

CREATE PROCEDURE I_POINT_DOCUMENT
(
  POINT_ID IN INTEGER,
  DOCUMENT_ID IN INTEGER,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO POINT_DOCUMENTS (POINT_ID,DOCUMENT_ID,PRIORITY)
       VALUES (POINT_ID,DOCUMENT_ID,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения документа точки */

CREATE OR REPLACE PROCEDURE U_POINT_DOCUMENT
(
  POINT_ID IN INTEGER,
  DOCUMENT_ID IN INTEGER,
  PRIORITY IN INTEGER,
  OLD_POINT_ID IN INTEGER,
  OLD_DOCUMENT_ID IN INTEGER
)
AS
BEGIN
  UPDATE POINT_DOCUMENTS 
     SET POINT_ID=U_POINT_DOCUMENT.POINT_ID,
         DOCUMENT_ID=U_POINT_DOCUMENT.DOCUMENT_ID,
         PRIORITY=U_POINT_DOCUMENT.PRIORITY
   WHERE POINT_ID=OLD_POINT_ID 
     AND DOCUMENT_ID=OLD_DOCUMENT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления документа точки */

CREATE PROCEDURE D_POINT_DOCUMENT
(
  OLD_POINT_ID IN INTEGER,
  OLD_DOCUMENT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM POINT_DOCUMENTS
        WHERE POINT_ID=OLD_POINT_ID
          AND DOCUMENT_ID=OLD_DOCUMENT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT