/* Создание последовательности для таблицы устройств */

CREATE SEQUENCE SEQ_DEVICES
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы устройств */

CREATE OR REPLACE FUNCTION GET_DEVICE_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_DEVICES.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы устройств */

CREATE TABLE DEVICES
(
  DEVICE_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DATE_ENTER DATE NOT NULL,
  PRIMARY KEY (DEVICE_ID)
)

--

/* Создание просмотра таблицы устройств */

CREATE VIEW S_DEVICES
AS
  SELECT D.*
    FROM DEVICES D


--

/* Создание процедуры создания устройства */

CREATE OR REPLACE PROCEDURE I_DEVICE
(
  DEVICE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DATE_ENTER IN DATE
)
AS
BEGIN
  INSERT INTO DEVICES (DEVICE_ID,NAME,DESCRIPTION,DATE_ENTER)
       VALUES (DEVICE_ID,NAME,DESCRIPTION,DATE_ENTER);
  COMMIT;
END;

--

/* Создание процедуры изменения устройства */

CREATE OR REPLACE PROCEDURE U_DEVICE
(
  DEVICE_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DATE_ENTER IN DATE,
  OLD_DEVICE_ID IN INTEGER
)
AS
BEGIN
  UPDATE DEVICES 
     SET DEVICE_ID=U_DEVICE.DEVICE_ID,
         NAME=U_DEVICE.NAME,
         DESCRIPTION=U_DEVICE.DESCRIPTION,
         DATE_ENTER=U_DEVICE.DATE_ENTER
   WHERE DEVICE_ID=OLD_DEVICE_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления устройства */

CREATE PROCEDURE D_DEVICE
(
  OLD_DEVICE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM DEVICES
        WHERE DEVICE_ID=OLD_DEVICE_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT