/* Изменение процедуры удаления точки */

CREATE OR REPLACE PROCEDURE D_POINT
(
  OLD_POINT_ID IN INTEGER
)
AS
  CNT INTEGER;
  JOURNAL_FIELDS_E EXCEPTION;
  ERROR VARCHAR(500);
BEGIN

  SELECT COUNT(*) INTO CNT FROM JOURNAL_FIELDS WHERE POINT_ID=OLD_POINT_ID;
  IF (CNT>0) THEN
    ERROR:='Измерительная точка используется в полевом журнале.'||CHR(13)||
	       'Это тестовое исключение, находится в процедуре D_POINT.';
    RAISE JOURNAL_FIELDS_E;
  END IF;
     
  DELETE FROM ROUTE_POINTS
        WHERE POINT_ID=OLD_POINT_ID;

  DELETE FROM POINT_DOCUMENTS
        WHERE POINT_ID=OLD_POINT_ID;

  DELETE FROM CONVERTERS
        WHERE CONVERTER_ID=OLD_POINT_ID;

  DELETE FROM DEVICE_POINTS
        WHERE POINT_ID=OLD_POINT_ID;
		
  DELETE FROM POINTS
        WHERE POINT_ID=OLD_POINT_ID;

  COMMIT; 
  
EXCEPTION
  WHEN JOURNAL_FIELDS_E THEN 
       RAISE_APPLICATION_ERROR(-20100,ERROR);
END;

--

/* Фиксация изменений БД */

COMMIT