/* Создание последовательности для таблицы чертежей */

CREATE SEQUENCE SEQ_DRAWINGS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы чертежей */

CREATE OR REPLACE FUNCTION GET_DRAWING_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_DRAWINGS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы чертежей */

CREATE TABLE DRAWINGS
(
  DRAWING_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  FILE_NAME VARCHAR2(250) NOT NULL,
  PRIMARY KEY (DRAWING_ID)
)

--

/* Создание просмотра таблицы чертежей */

CREATE VIEW S_DRAWINGS
AS
  SELECT D.*
    FROM DRAWINGS D


--

/* Создание процедуры создания чертежа */

CREATE OR REPLACE PROCEDURE I_DRAWING
(
  DRAWING_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  FILE_NAME IN VARCHAR2
)
AS
BEGIN
  INSERT INTO DRAWINGS (DRAWING_ID,NAME,DESCRIPTION,FILE_NAME)
       VALUES (DRAWING_ID,NAME,DESCRIPTION,FILE_NAME);
  COMMIT;
END;

--

/* Создание процедуры изменения чертежа */


CREATE OR REPLACE PROCEDURE U_DRAWING
(
  DRAWING_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  FILE_NAME IN VARCHAR2,
  OLD_DRAWING_ID IN INTEGER
)
AS
BEGIN
  UPDATE DRAWINGS 
     SET DRAWING_ID=U_DRAWING.DRAWING_ID,
         NAME=U_DRAWING.NAME,
         DESCRIPTION=U_DRAWING.DESCRIPTION,
         FILE_NAME=U_DRAWING.FILE_NAME
   WHERE DRAWING_ID=OLD_DRAWING_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления чертежа */

CREATE PROCEDURE D_DRAWING
(
  OLD_DRAWING_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM DRAWINGS
        WHERE DRAWING_ID=OLD_DRAWING_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT