/* Создание таблицы чертежей объектов */

CREATE TABLE OBJECT_DRAWINGS 
(
  OBJECT_ID INTEGER NOT NULL, 
  DRAWING_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (OBJECT_ID,DRAWING_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID),
  FOREIGN KEY (DRAWING_ID) REFERENCES DRAWINGS (DRAWING_ID)
)


--

/* Создание просмотра таблицы чертежей объектов */

CREATE OR REPLACE VIEW S_OBJECT_DRAWINGS
AS
  SELECT OD.*, 
         O.NAME AS OBJECT_NAME, 
		 D.NAME AS DRAWING_NAME,
		 D.DESCRIPTION AS DRAWING_DESCRIPTION,
		 D.FILE_NAME
    FROM OBJECT_DRAWINGS OD, OBJECTS O, DRAWINGS D
   WHERE O.OBJECT_ID=OD.OBJECT_ID 
     AND D.DRAWING_ID=OD.DRAWING_ID

--

/* Создание процедуры добавления чертежа объекту */

CREATE PROCEDURE I_OBJECT_DRAWING
(
  OBJECT_ID IN INTEGER,
  DRAWING_ID IN INTEGER,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO OBJECT_DRAWINGS (OBJECT_ID,DRAWING_ID,PRIORITY)
       VALUES (OBJECT_ID,DRAWING_ID,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения чертежа объекта */

CREATE OR REPLACE PROCEDURE U_OBJECT_DRAWING
(
  OBJECT_ID IN INTEGER,
  DRAWING_ID IN INTEGER,
  PRIORITY IN INTEGER,
  OLD_OBJECT_ID IN INTEGER,
  OLD_DRAWING_ID IN INTEGER
)
AS
BEGIN
  UPDATE OBJECT_DRAWINGS 
     SET OBJECT_ID=U_OBJECT_DRAWING.OBJECT_ID,
         DRAWING_ID=U_OBJECT_DRAWING.DRAWING_ID,
         PRIORITY=U_OBJECT_DRAWING.PRIORITY
   WHERE OBJECT_ID=OLD_OBJECT_ID 
     AND DRAWING_ID=OLD_DRAWING_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления чертежа у объекта */

CREATE PROCEDURE D_OBJECT_DRAWING
(
  OLD_OBJECT_ID IN INTEGER,
  OLD_DRAWING_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM OBJECT_DRAWINGS
        WHERE OBJECT_ID=OLD_OBJECT_ID
          AND DRAWING_ID=OLD_DRAWING_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT