/* Создание последовательности для таблицы паспорт преобразователей */

CREATE SEQUENCE SEQ_CONVERTER_PASSPORTS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы паспорт преобразователей */

CREATE OR REPLACE FUNCTION GET_CONVERTER_PASSPORT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_CONVERTER_PASSPORTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы паспортов преобразователей */

CREATE TABLE CONVERTER_PASSPORTS
(
  CONVERTER_PASSPORT_ID INTEGER NOT NULL,
  COMPONENT_ID INTEGER NOT NULL,
  INSTRUMENT_ID INTEGER,
  MEASURE_UNIT_ID INTEGER,
  DESCRIPTION VARCHAR2(250),
  VALUE VARCHAR2(100) NOT NULL,
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE,
  PRIMARY KEY (CONVERTER_PASSPORT_ID),
  FOREIGN KEY (COMPONENT_ID) REFERENCES COMPONENTS (COMPONENT_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID),
  FOREIGN KEY (MEASURE_UNIT_ID) REFERENCES MEASURE_UNITS (MEASURE_UNIT_ID)
)

--

/* Создание просмотра таблицы паспорт преобразователей */

CREATE OR REPLACE VIEW S_CONVERTER_PASSPORTS
AS
  SELECT CP.*,
         C.NAME AS COMPONENT_NAME,
		 C.CONVERTER_ID,
		 I.NAME AS INSTRUMENT_NAME,
		 MU.NAME AS MEASURE_UNIT_NAME
    FROM CONVERTER_PASSPORTS CP, COMPONENTS C, 
	     INSTRUMENTS I, MEASURE_UNITS MU 
   WHERE CP.COMPONENT_ID=C.COMPONENT_ID
     AND CP.INSTRUMENT_ID=I.INSTRUMENT_ID (+)
	 AND CP.MEASURE_UNIT_ID=MU.MEASURE_UNIT_ID (+)
ORDER BY C.NAME, CP.DATE_BEGIN DESC 

--

/* Создание процедуры создания паспорта преобразователя */

CREATE OR REPLACE PROCEDURE I_CONVERTER_PASSPORT
(
  CONVERTER_PASSPORT_ID IN INTEGER,
  COMPONENT_ID IN INTEGER,
  INSTRUMENT_ID IN INTEGER,
  MEASURE_UNIT_ID IN INTEGER,
  DESCRIPTION IN VARCHAR2,
  VALUE IN VARCHAR2,
  DATE_BEGIN IN DATE,
  DATE_END IN DATE
)
AS
BEGIN
  INSERT INTO CONVERTER_PASSPORTS (CONVERTER_PASSPORT_ID,COMPONENT_ID,INSTRUMENT_ID,
                                   MEASURE_UNIT_ID,DESCRIPTION,VALUE,DATE_BEGIN,DATE_END)
       VALUES (CONVERTER_PASSPORT_ID,COMPONENT_ID,INSTRUMENT_ID,
               MEASURE_UNIT_ID,DESCRIPTION,VALUE,DATE_BEGIN,DATE_END);
  COMMIT;
END;

--

/* Создание процедуры изменения паспорта преобразователя */

CREATE OR REPLACE PROCEDURE U_CONVERTER_PASSPORT
(
  CONVERTER_PASSPORT_ID IN INTEGER,
  COMPONENT_ID IN INTEGER,
  INSTRUMENT_ID IN INTEGER,
  MEASURE_UNIT_ID IN INTEGER,
  DESCRIPTION IN VARCHAR2,
  VALUE IN VARCHAR2,
  DATE_BEGIN IN DATE,
  DATE_END IN DATE,
  OLD_CONVERTER_PASSPORT_ID IN INTEGER
)
AS
BEGIN
  UPDATE CONVERTER_PASSPORTS 
     SET CONVERTER_PASSPORT_ID=U_CONVERTER_PASSPORT.CONVERTER_PASSPORT_ID,
         COMPONENT_ID=U_CONVERTER_PASSPORT.COMPONENT_ID,
         INSTRUMENT_ID=U_CONVERTER_PASSPORT.INSTRUMENT_ID,
         MEASURE_UNIT_ID=U_CONVERTER_PASSPORT.MEASURE_UNIT_ID,
         DESCRIPTION=U_CONVERTER_PASSPORT.DESCRIPTION,
		 VALUE=U_CONVERTER_PASSPORT.VALUE,
		 DATE_BEGIN=U_CONVERTER_PASSPORT.DATE_BEGIN,
		 DATE_END=U_CONVERTER_PASSPORT.DATE_END
   WHERE CONVERTER_PASSPORT_ID=OLD_CONVERTER_PASSPORT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления паспорта преобразователя */

CREATE OR REPLACE PROCEDURE D_CONVERTER_PASSPORT
(
  OLD_CONVERTER_PASSPORT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM CONVERTER_PASSPORTS
        WHERE CONVERTER_PASSPORT_ID=OLD_CONVERTER_PASSPORT_ID;
  COMMIT;        
END;

--

/* Создание индекса на компонент паспорта преобразователя */

CREATE INDEX IDX_CONVERTER_PASSPORTS_1
 ON CONVERTER_PASSPORTS(COMPONENT_ID)

--

/* Фиксация изменений БД */

COMMIT