/* Создание последовательности для таблицы паспортов приборов */

CREATE SEQUENCE SEQ_INSTRUMENT_PASSPORTS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы паспортов приборов */

CREATE OR REPLACE FUNCTION GET_INSTRUMENT_PASSPORT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_INSTRUMENT_PASSPORTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы паспортов приборов */

CREATE TABLE INSTRUMENT_PASSPORTS
(
  INSTRUMENT_PASSPORT_ID INTEGER NOT NULL,
  INSTRUMENT_ID INTEGER NOT NULL,
  DATE_TEST DATE NOT NULL,
  DESCRIPTION VARCHAR2(250),
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (INSTRUMENT_PASSPORT_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID)
)

--

/* Создание просмотра таблицы паспортов приборов */

CREATE OR REPLACE VIEW S_INSTRUMENT_PASSPORTS
AS
  SELECT IP.*,
         I.NAME AS INSTRUMENT_NAME
    FROM INSTRUMENT_PASSPORTS IP, INSTRUMENTS I
   WHERE IP.INSTRUMENT_ID=I.INSTRUMENT_ID

--

/* Создание процедуры создания паспорта прибора */

CREATE OR REPLACE PROCEDURE I_INSTRUMENT_PASSPORT
(
  INSTRUMENT_PASSPORT_ID IN INTEGER,
  INSTRUMENT_ID IN INTEGER,
  DATE_TEST IN DATE,
  DESCRIPTION IN VARCHAR2,
  RATIO IN FLOAT
)
AS
BEGIN
  INSERT INTO INSTRUMENT_PASSPORTS (INSTRUMENT_PASSPORT_ID,INSTRUMENT_ID,DATE_TEST,DESCRIPTION,RATIO)
       VALUES (INSTRUMENT_PASSPORT_ID,INSTRUMENT_ID,DATE_TEST,DESCRIPTION,RATIO);
  COMMIT;
END;

--

/* Создание процедуры изменения паспорта прибора */

CREATE OR REPLACE PROCEDURE U_INSTRUMENT_PASSPORT
(
  INSTRUMENT_PASSPORT_ID IN INTEGER,
  INSTRUMENT_ID IN INTEGER,
  DATE_TEST IN DATE,
  DESCRIPTION IN VARCHAR2,
  RATIO IN FLOAT,
  OLD_INSTRUMENT_PASSPORT_ID IN INTEGER
)
AS
BEGIN
  UPDATE INSTRUMENT_PASSPORTS 
     SET INSTRUMENT_PASSPORT_ID=U_INSTRUMENT_PASSPORT.INSTRUMENT_PASSPORT_ID,
         INSTRUMENT_ID=U_INSTRUMENT_PASSPORT.INSTRUMENT_ID,
         DATE_TEST=U_INSTRUMENT_PASSPORT.DATE_TEST,
         DESCRIPTION=U_INSTRUMENT_PASSPORT.DESCRIPTION,
		 RATIO=U_INSTRUMENT_PASSPORT.RATIO
   WHERE INSTRUMENT_PASSPORT_ID=OLD_INSTRUMENT_PASSPORT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления паспорта прибора */

CREATE PROCEDURE D_INSTRUMENT_PASSPORT
(
  OLD_INSTRUMENT_PASSPORT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM INSTRUMENT_PASSPORTS
        WHERE INSTRUMENT_PASSPORT_ID=OLD_INSTRUMENT_PASSPORT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT