/* Изменение процедуры удаления объекта */

CREATE OR REPLACE PROCEDURE D_OBJECT
(
  OLD_OBJECT_ID IN INTEGER
)
AS
  CNT INTEGER;
  POINT_E EXCEPTION;
  ERROR VARCHAR(500);
BEGIN

  SELECT COUNT(*) INTO CNT FROM POINTS WHERE OBJECT_ID=OLD_OBJECT_ID;
  IF (CNT>0) THEN
    ERROR:='Объект используется в измерительных точках.';
    RAISE POINT_E;
  END IF;

  DELETE FROM OBJECT_DRAWINGS
        WHERE OBJECT_ID=OLD_OBJECT_ID;

  DELETE FROM OBJECT_DOCUMENTS
        WHERE OBJECT_ID=OLD_OBJECT_ID;
		
  DELETE FROM OBJECTS
        WHERE OBJECT_ID=OLD_OBJECT_ID;
		
  COMMIT;
  
EXCEPTION
  WHEN POINT_E THEN 
       RAISE_APPLICATION_ERROR(-20100,ERROR);
END;

--

/* Фиксация изменений БД */


COMMIT