/* Создание процедуры тождественного алгоритма */

CREATE OR REPLACE PROCEDURE CONFIRM_IDENTITY
(
  JOURNAL_FIELD_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER
)
AS
  JOURNAL_OBSERVATION_ID INTEGER;
  AMEASURE_TYPE_ID INTEGER;
  ACYCLE_ID INTEGER;
  AWHO_CONFIRM INTEGER;
  ADATE_CONFIRM DATE;
  AGROUP_ID VARCHAR2(32);
  APRIORITY INTEGER;
  AINSTRUMENT_ID INTEGER;
  AMEASURE_UNIT_ID INTEGER;
  ADATE_OBSERVATION DATE;
  APOINT_ID INTEGER;
  AVALUE FLOAT;
  APARAM_ID INTEGER;
BEGIN
  SELECT MEASURE_TYPE_ID,CYCLE_ID,WHO_CONFIRM,DATE_CONFIRM,GROUP_ID,PRIORITY,
         INSTRUMENT_ID,MEASURE_UNIT_ID,DATE_OBSERVATION,POINT_ID,VALUE,PARAM_ID 
    INTO AMEASURE_TYPE_ID,ACYCLE_ID,AWHO_CONFIRM,ADATE_CONFIRM,AGROUP_ID,APRIORITY,
         AINSTRUMENT_ID,AMEASURE_UNIT_ID,ADATE_OBSERVATION,APOINT_ID,AVALUE,APARAM_ID
    FROM JOURNAL_FIELDS
   WHERE JOURNAL_FIELD_ID=CONFIRM_IDENTITY.JOURNAL_FIELD_ID;
  
  DELETE FROM JOURNAL_OBSERVATIONS
        WHERE JOURNAL_FIELD_ID=CONFIRM_IDENTITY.JOURNAL_FIELD_ID
          AND ALGORITHM_ID=CONFIRM_IDENTITY.ALGORITHM_ID 
		  AND MEASURE_TYPE_ID=AMEASURE_TYPE_ID
		  AND CYCLE_ID=ACYCLE_ID
		  AND DATE_OBSERVATION=ADATE_OBSERVATION
		  AND GROUP_ID=AGROUP_ID
          AND POINT_ID=APOINT_ID
          AND PARAM_ID=APARAM_ID;
  COMMIT;	  						  

  IF (AWHO_CONFIRM IS NOT NULL) THEN				  
    I_JOURNAL_OBSERVATION(GET_JOURNAL_OBSERVATION_ID,
	                      JOURNAL_FIELD_ID,
		  				  AINSTRUMENT_ID,
						  AMEASURE_TYPE_ID,
						  AMEASURE_UNIT_ID,
						  ADATE_OBSERVATION,
						  ACYCLE_ID,
						  APOINT_ID,
						  APARAM_ID,
						  AVALUE,
						  AWHO_CONFIRM,
						  ADATE_CONFIRM,
						  ALGORITHM_ID,
						  AGROUP_ID,
						  APRIORITY);
  END IF;											 
END;

--

/* Фиксация изменений БД */

COMMIT