/* Создание просмотра паспортов преобразователей по видам измерения */

CREATE OR REPLACE VIEW S_MEASURE_TYPE_CONVERTER_PASS
AS 
SELECT MTR.MEASURE_TYPE_ID,
        MT.NAME AS MEASURE_TYPE_NAME,
        PT.POINT_ID,
        PT.NAME AS POINT_NAME,
        CR.CONVERTER_ID,
        CR.NAME AS CONVERTER_NAME,
        P.PARAM_ID,
        P.NAME AS PARAM_NAME,
        C.COMPONENT_ID,
        C.NAME AS COMPONENT_NAME,
        CP.CONVERTER_PASSPORT_ID,
        CP.DATE_BEGIN,
        CP.DATE_END,
        CP.DESCRIPTION,
        CP.VALUE
   FROM CONVERTER_PASSPORTS CP, COMPONENTS C, CONVERTERS CR,
        PARAMS P, POINTS PT, ROUTE_POINTS RP,
 	    MEASURE_TYPE_ROUTES MTR, MEASURE_TYPES MT
  WHERE CP.COMPONENT_ID=C.COMPONENT_ID
    AND C.CONVERTER_ID=CR.CONVERTER_ID
    AND C.PARAM_ID=P.PARAM_ID
    AND CR.CONVERTER_ID=PT.POINT_ID
    AND PT.POINT_ID=RP.POINT_ID
    AND RP.ROUTE_ID=MTR.ROUTE_ID
    AND MTR.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
  ORDER BY MT.PRIORITY, MTR.PRIORITY, RP.PRIORITY, P.NAME, CP.DATE_BEGIN DESC

--

/* Фиксация изменений БД */

COMMIT
