/* Создание процедуры расчета приведенного пьезометрического напора */

CREATE OR REPLACE PROCEDURE CONFIRM_PRESSURE_BROUGHT
(
  JOURNAL_FIELD_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER
)
AS
  JOURNAL_OBSERVATION_ID INTEGER;
  AMEASURE_TYPE_ID INTEGER;
  ACYCLE_ID INTEGER;
  AWHO_CONFIRM INTEGER;
  ADATE_CONFIRM DATE;
  AGROUP_ID VARCHAR2(32);
  APRIORITY INTEGER;
  APOINT_ID INTEGER;
  APARAM_ID INTEGER;
  ADATE_OBSERVATION DATE;
  AVALUE FLOAT;
  AINSTRUMENT_ID INTEGER;
  AMEASURE_UNIT_ID INTEGER;
  PRESSURE_ACTIVE FLOAT;
  PRESSURE_OPPOSE FLOAT;
  PRESSURE_BROUGHT FLOAT;
  FLAG INTEGER;
BEGIN
  SELECT MEASURE_TYPE_ID,CYCLE_ID,WHO_CONFIRM,DATE_CONFIRM,GROUP_ID,PRIORITY,POINT_ID,
         DATE_OBSERVATION,VALUE,PARAM_ID,INSTRUMENT_ID,MEASURE_UNIT_ID  
    INTO AMEASURE_TYPE_ID,ACYCLE_ID,AWHO_CONFIRM,ADATE_CONFIRM,AGROUP_ID,APRIORITY,APOINT_ID,
         ADATE_OBSERVATION,AVALUE,APARAM_ID,AINSTRUMENT_ID,AMEASURE_UNIT_ID
    FROM JOURNAL_FIELDS
   WHERE JOURNAL_FIELD_ID=CONFIRM_PRESSURE_BROUGHT.JOURNAL_FIELD_ID;

  IF (APARAM_ID=2920)/* Отсчет пьезометра */ THEN 

     DELETE FROM JOURNAL_OBSERVATIONS
	       WHERE JOURNAL_FIELD_ID=CONFIRM_PRESSURE_BROUGHT.JOURNAL_FIELD_ID
             AND ALGORITHM_ID=CONFIRM_PRESSURE_BROUGHT.ALGORITHM_ID 
             AND MEASURE_TYPE_ID=AMEASURE_TYPE_ID
             AND CYCLE_ID=ACYCLE_ID
             AND DATE_OBSERVATION=ADATE_OBSERVATION
             AND GROUP_ID=AGROUP_ID
             AND POINT_ID=APOINT_ID
             AND PARAM_ID=2963; /* Приведенный напор */
    COMMIT;
			 
    IF (AWHO_CONFIRM IS NOT NULL) THEN
	  
	  FLAG:=0;
	  PRESSURE_ACTIVE:=0;
	  FOR INC IN (SELECT VALUE
                    FROM JOURNAL_OBSERVATIONS
                   WHERE JOURNAL_FIELD_ID=CONFIRM_PRESSURE_BROUGHT.JOURNAL_FIELD_ID
					 AND MEASURE_TYPE_ID=AMEASURE_TYPE_ID
					 AND CYCLE_ID=ACYCLE_ID
					 AND DATE_OBSERVATION=ADATE_OBSERVATION
					 AND GROUP_ID=AGROUP_ID
					 AND POINT_ID=APOINT_ID
                     AND ALGORITHM_ID=2801 /* Действующий напор */
					 AND PARAM_ID=2961 /* Действующий напор */) LOOP
        PRESSURE_ACTIVE:=INC.VALUE;
		EXIT WHEN PRESSURE_ACTIVE IS NOT NULL;					  
      END LOOP;					 

	  PRESSURE_OPPOSE:=0;
	  FOR INC IN (SELECT VALUE
                    FROM JOURNAL_OBSERVATIONS
                   WHERE JOURNAL_FIELD_ID=CONFIRM_PRESSURE_BROUGHT.JOURNAL_FIELD_ID
					 AND MEASURE_TYPE_ID=AMEASURE_TYPE_ID
					 AND CYCLE_ID=ACYCLE_ID
					 AND DATE_OBSERVATION=ADATE_OBSERVATION
					 AND GROUP_ID=AGROUP_ID
					 AND POINT_ID=APOINT_ID
                     AND ALGORITHM_ID=2802 /* Фильтрационное противодавление */
					 AND PARAM_ID=2962 /* Фильтрационное противодавление */) LOOP
        PRESSURE_OPPOSE:=INC.VALUE;
		EXIT WHEN PRESSURE_OPPOSE IS NOT NULL;					  
      END LOOP;					 
	  
	  IF (PRESSURE_ACTIVE IS NOT NULL) AND 
	     (PRESSURE_OPPOSE IS NOT NULL) THEN
		FLAG:=1; 
		PRESSURE_BROUGHT:=0;
		IF (PRESSURE_ACTIVE<>0) THEN
  		  PRESSURE_BROUGHT:=PRESSURE_OPPOSE/PRESSURE_ACTIVE;
		END IF;  
	  END IF;	  
	  
	  IF (FLAG=1) THEN
        I_JOURNAL_OBSERVATION(GET_JOURNAL_OBSERVATION_ID,
                              JOURNAL_FIELD_ID,
                              NULL,
                              AMEASURE_TYPE_ID,
                              NULL,
                              ADATE_OBSERVATION,
                              ACYCLE_ID,
                              APOINT_ID,
                              2963,/* Приведенный напор */
                              PRESSURE_BROUGHT,
                              AWHO_CONFIRM,
                              ADATE_CONFIRM,
                              ALGORITHM_ID,
                              AGROUP_ID,
                              APRIORITY);
      END IF;							  
	END IF;  
  END IF;		 
END;

--

/* Фиксация изменений БД */

COMMIT