/* Создание просмотра преобразователей по видам измерений */

CREATE VIEW S_MEASURE_TYPE_CONVERTERS
AS
SELECT MTR.MEASURE_TYPE_ID,
       MT.NAME AS MEASURE_TYPE_NAME,
       RP.ROUTE_ID,
	   R.NAME AS ROUTE_NAME,
	   P.POINT_ID,
	   P.NAME AS POINT_NAME,
	   C.CONVERTER_ID,
	   C.NAME AS CONVERTER_NAME
  FROM MEASURE_TYPES MT, MEASURE_TYPE_ROUTES MTR, 
       ROUTES R, ROUTE_POINTS RP, 
	   POINTS P, CONVERTERS C
 WHERE MT.MEASURE_TYPE_ID=MTR.MEASURE_TYPE_ID
   AND MTR.ROUTE_ID=R.ROUTE_ID
   AND R.ROUTE_ID=RP.ROUTE_ID
   AND RP.POINT_ID=P.POINT_ID
   AND P.POINT_ID=C.CONVERTER_ID
 ORDER BY MT.PRIORITY, MTR.PRIORITY, RP.PRIORITY

--

/* Фиксация изменений БД */

COMMIT
