/* Создание последовательности для таблицы контроля */

CREATE SEQUENCE SEQ_CHECKINGS
INCREMENT BY 1 
START WITH 2900 
MAXVALUE 1.0E28 
MINVALUE 2900
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы контроля */

CREATE OR REPLACE FUNCTION GET_CHECKING_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_CHECKINGS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы контроля */

CREATE TABLE CHECKINGS
(
  CHECKING_ID INTEGER NOT NULL,
  MEASURE_TYPE_ID INTEGER NOT NULL,
  POINT_ID INTEGER,
  PARAM_ID INTEGER NOT NULL,  
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PROC_NAME VARCHAR2(100),
  PRIORITY INTEGER,
  PRIMARY KEY (CHECKING_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID)
)

--

/* Создание просмотра таблицы контроля */

CREATE OR REPLACE VIEW S_CHECKINGS
AS
  SELECT C.*, 
         MT.NAME AS MEASURE_TYPE_NAME,
		 PT.NAME AS POINT_NAME,
		 P.NAME AS PARAM_NAME
    FROM CHECKINGS C, MEASURE_TYPES MT, PARAMS P, POINTS PT 
   WHERE C.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
     AND C.PARAM_ID=P.PARAM_ID
	 AND C.POINT_ID=PT.POINT_ID (+)

--

/* Создание процедуры создания контроля */

CREATE OR REPLACE PROCEDURE I_CHECKING
(
  CHECKING_ID IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  POINT_ID IN INTEGER,
  PARAM_ID IN INTEGER,  
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PROC_NAME IN VARCHAR2,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO CHECKINGS (CHECKING_ID,MEASURE_TYPE_ID,POINT_ID,PARAM_ID,NAME,DESCRIPTION,PROC_NAME,PRIORITY)
       VALUES (CHECKING_ID,MEASURE_TYPE_ID,POINT_ID,PARAM_ID,NAME,DESCRIPTION,PROC_NAME,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения контроля */


CREATE OR REPLACE PROCEDURE U_CHECKING
(
  CHECKING_ID IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  POINT_ID IN INTEGER,
  PARAM_ID IN INTEGER,  
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PROC_NAME IN VARCHAR2,
  PRIORITY IN INTEGER,
  OLD_CHECKING_ID IN INTEGER
)
AS
BEGIN
  UPDATE CHECKINGS 
     SET CHECKING_ID=U_CHECKING.CHECKING_ID,
	     MEASURE_TYPE_ID=U_CHECKING.MEASURE_TYPE_ID,
		 POINT_ID=U_CHECKING.POINT_ID,
		 PARAM_ID=U_CHECKING.PARAM_ID,
         NAME=U_CHECKING.NAME,
         DESCRIPTION=U_CHECKING.DESCRIPTION,
		 PROC_NAME=U_CHECKING.PROC_NAME,
		 PRIORITY=U_CHECKING.PRIORITY
   WHERE CHECKING_ID=OLD_CHECKING_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления контроля */

CREATE PROCEDURE D_CHECKING
(
  OLD_CHECKING_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM CHECKINGS
        WHERE CHECKING_ID=OLD_CHECKING_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT