/* Создание процедуры установки значения по умолчанию для объема */

CREATE OR REPLACE PROCEDURE DEFAULT_VOLUME
(
  POINT_ID IN INTEGER,
  PARAM_ID_0 IN INTEGER,
  INSTRUMENT_ID_0 IN INTEGER,
  MEASHURE_UNIT_ID_0 IN INTEGER,
  VALUE_0 IN OUT FLOAT,
  PARAM_ID_1 IN INTEGER,
  INSTRUMENT_ID_1 IN INTEGER,
  MEASHURE_UNIT_ID_1 IN INTEGER,
  VALUE_1 IN OUT FLOAT,
  PARAM_ID_2 IN INTEGER,
  VALUE_2 IN OUT FLOAT
)
AS
BEGIN
  IF (VALUE_0 IS NULL) THEN
    VALUE_0:=1.0;
  END IF;	
  IF (VALUE_1 IS NOT NULL) AND
     (VALUE_1<>0.0) THEN
	VALUE_2:=VALUE_0/(VALUE_1*1000);
  ELSE
    IF (VALUE_1 IS NOT NULL) THEN
      VALUE_2:=0.0;
	END IF;  	 
  END IF;	  
END;

--

/* Фиксация изменений БД */

COMMIT