/* Добавление колонки тип ввода к полевому журналу */

ALTER TABLE JOURNAL_FIELDS
ADD INPUT_TYPE INTEGER DEFAULT 0

--

/* Изменение таблицы просмотра полевого журнала */

CREATE OR REPLACE VIEW S_JOURNAL_FIELDS
AS 
SELECT JF.*, 
         C.CYCLE_NUM,
         PT.NAME AS POINT_NAME,
         PR.NAME AS PARAM_NAME,
		 MT.NAME AS MEASURE_TYPE_NAME,
         P1.FNAME||' '||P1.NAME||' '||P1.SNAME AS WHO_ENTER_NAME,
         P2.FNAME||' '||P2.NAME||' '||P2.SNAME AS WHO_CONFIRM_NAME,
		 I.NAME AS INSTRUMENT_NAME,
		 MU.NAME AS MEASURE_UNIT_NAME
    FROM JOURNAL_FIELDS JF, CYCLES C, POINTS PT, PARAMS PR, MEASURE_TYPES MT, 
         PERSONNELS P1, PERSONNELS P2, INSTRUMENTS I, MEASURE_UNITS MU
   WHERE JF.POINT_ID=PT.POINT_ID
     AND JF.PARAM_ID=PR.PARAM_ID
     AND JF.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
     AND JF.WHO_ENTER=P1.PERSONNEL_ID
	 AND JF.CYCLE_ID=C.CYCLE_ID
     AND JF.WHO_CONFIRM=P2.PERSONNEL_ID (+)
	 AND JF.INSTRUMENT_ID=I.INSTRUMENT_ID (+)
	 AND JF.MEASURE_UNIT_ID=MU.MEASURE_UNIT_ID (+);

--

/* Фиксация изменений БД */

COMMIT