/* Создание процедуры обновления журнала наблюдений старых данных фильтрации */

CREATE OR REPLACE PROCEDURE R_FLT_JOURNAL_OBSERVATIONS
AS 
BEGIN 
  R_FLT_JOURNAL_OBSERVATIONS_1; 
  R_FLT_JOURNAL_OBSERVATIONS_2; 
  R_FLT_JOURNAL_OBSERVATIONS_3; 
  R_FLT_JOURNAL_OBSERVATIONS_4; 
  R_FLT_JOURNAL_OBSERVATIONS_5; 
  R_FLT_JOURNAL_OBSERVATIONS_6; 
END;

--

/* Фиксация изменений */

COMMIT
