/* Создание последовательности для таблицы видов дефектов  */

CREATE SEQUENCE SEQ_DEFECT_VIEWS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора для таблицы видов дефектов */


CREATE OR REPLACE FUNCTION GET_DEFECT_VIEW_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_DEFECT_VIEWS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы видов дефектов */

CREATE TABLE DEFECT_VIEWS
(
  DEFECT_VIEW_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (DEFECT_VIEW_ID)
)

--

/* Создание просмотра таблицы видов дефектов */

CREATE OR REPLACE VIEW S_DEFECT_VIEWS
AS
  SELECT DV.*
    FROM DEFECT_VIEWS DV

--

/* Создание процедуры создания вида дефекта */

CREATE OR REPLACE PROCEDURE I_DEFECT_VIEW
(
  DEFECT_VIEW_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO DEFECT_VIEWS (DEFECT_VIEW_ID,NAME,DESCRIPTION,PRIORITY)
       VALUES (DEFECT_VIEW_ID,NAME,DESCRIPTION,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения вида дефекта */

CREATE OR REPLACE PROCEDURE U_DEFECT_VIEW
(
  DEFECT_VIEW_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PRIORITY IN INTEGER,
  OLD_DEFECT_VIEW_ID IN INTEGER
)
AS
BEGIN
  UPDATE DEFECT_VIEWS 
     SET DEFECT_VIEW_ID=U_DEFECT_VIEW.DEFECT_VIEW_ID,
         NAME=U_DEFECT_VIEW.NAME, 
         DESCRIPTION=U_DEFECT_VIEW.DESCRIPTION,
		 PRIORITY=U_DEFECT_VIEW.PRIORITY 
   WHERE DEFECT_VIEW_ID=OLD_DEFECT_VIEW_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления вида дефекта */

CREATE PROCEDURE D_DEFECT_VIEW
(
  OLD_DEFECT_VIEW_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM DEFECT_VIEWS
        WHERE DEFECT_VIEW_ID=OLD_DEFECT_VIEW_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT