/* Создание последовательности для таблицы журнала осмотров */

CREATE SEQUENCE SEQ_JOURNAL_CHECKUPS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора таблицы журнала осмотров */

CREATE OR REPLACE FUNCTION GET_JOURNAL_CHECKUP_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_JOURNAL_CHECKUPS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы журнала осмотров */

CREATE TABLE JOURNAL_CHECKUPS
(
  JOURNAL_CHECKUP_ID INTEGER NOT NULL,
  POINT_ID INTEGER NOT NULL,
  CYCLE_ID INTEGER NOT NULL,
  MEASURE_TYPE_ID INTEGER NOT NULL,
  DEFECT_VIEW_ID INTEGER NOT NULL,
  DATE_OBSERVATION DATE NOT NULL,
  NOTE VARCHAR2(250),
  JOURNAL_NUM VARCHAR2(100),
  WHO_ENTER INTEGER NOT NULL,
  DATE_ENTER DATE NOT NULL,
  WHO_CONFIRM INTEGER,
  DATE_CONFIRM DATE,
  INCLINATION VARCHAR2(250),
  WIDTH_DEFECT VARCHAR2(50),
  HEIGHT_DEFECT VARCHAR2(50),
  LENGTH_DEFECT VARCHAR2(50),
  PRIMARY KEY (JOURNAL_CHECKUP_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID),
  FOREIGN KEY (CYCLE_ID) REFERENCES CYCLES (CYCLE_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (DEFECT_VIEW_ID) REFERENCES DEFECT_VIEWS (DEFECT_VIEW_ID),
  FOREIGN KEY (WHO_ENTER) REFERENCES PERSONNELS (PERSONNEL_ID),
  FOREIGN KEY (WHO_CONFIRM) REFERENCES PERSONNELS (PERSONNEL_ID)
) 

--

/* Создание индекса по дате наблюдения журнала осмотров */

CREATE INDEX IDX_JOURNAL_CHECKUPS_1
 ON JOURNAL_CHECKUPS(DATE_OBSERVATION)

--

/* Создание индекса по циклу журнала осмотров */

CREATE INDEX IDX_JOURNAL_CHECKUPS_2
 ON JOURNAL_CHECKUPS(CYCLE_ID)

--

/* Создание индекса по виду измерения журнала осмотров */

CREATE INDEX IDX_JOURNAL_CHECKUPS_3
 ON JOURNAL_CHECKUPS(MEASURE_TYPE_ID)

--

/* Создание индекса по точке журнала осмотров */

CREATE INDEX IDX_JOURNAL_CHECKUPS_4
 ON JOURNAL_CHECKUPS(POINT_ID)

--

/* Создание индекса по виду дефекта */

CREATE INDEX IDX_JOURNAL_CHECKUPS_5
 ON JOURNAL_CHECKUPS(DEFECT_VIEW_ID)

--

/* Создание индекса по месяцу журнала осмотров */

CREATE BITMAP INDEX IDX_JOURNAL_CHECKUPS_6
 ON JOURNAL_CHECKUPS (EXTRACT(MONTH FROM DATE_OBSERVATION))

--

/* Создание индекса по году журнала осмотров */

CREATE BITMAP INDEX IDX_JOURNAL_CHECKUPS_7
 ON JOURNAL_CHECKUPS (EXTRACT(YEAR FROM DATE_OBSERVATION))

--

/* Создание просмотра таблицы журнала осмотров */

CREATE OR REPLACE VIEW S_JOURNAL_CHECKUPS
AS
  SELECT JC.*, 
         C.CYCLE_NUM,
         PT.NAME AS POINT_NAME,
		 MT.NAME AS MEASURE_TYPE_NAME,
		 DV.NAME AS DEFECT_VIEW_NAME,
         P1.FNAME||' '||P1.NAME||' '||P1.SNAME AS WHO_ENTER_NAME,
         P2.FNAME||' '||P2.NAME||' '||P2.SNAME AS WHO_CONFIRM_NAME
    FROM JOURNAL_CHECKUPS JC, CYCLES C, POINTS PT, MEASURE_TYPES MT, 
         DEFECT_VIEWS DV, PERSONNELS P1, PERSONNELS P2
   WHERE JC.POINT_ID=PT.POINT_ID
	 AND JC.CYCLE_ID=C.CYCLE_ID
     AND JC.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
     AND JC.DEFECT_VIEW_ID=DV.DEFECT_VIEW_ID
     AND JC.WHO_ENTER=P1.PERSONNEL_ID
     AND JC.WHO_CONFIRM=P2.PERSONNEL_ID (+)

--

/* Создание процедуры утверждения журнала осмотров */

CREATE OR REPLACE PROCEDURE CONFIRM_JOURNAL_CHECKUP
(
  JOURNAL_CHECKUP_ID IN INTEGER
)
AS
BEGIN
  COMMIT;							    
END;

--

/* Создание процедуры создания записи в журнале осмотров */

CREATE OR REPLACE PROCEDURE I_JOURNAL_CHECKUP
(
  JOURNAL_CHECKUP_ID IN INTEGER,
  POINT_ID IN INTEGER,
  CYCLE_ID IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  DEFECT_VIEW_ID IN INTEGER,
  DATE_OBSERVATION IN DATE,
  NOTE IN VARCHAR2,
  JOURNAL_NUM IN VARCHAR2,
  WHO_ENTER IN INTEGER,
  DATE_ENTER IN DATE,
  WHO_CONFIRM IN INTEGER,
  DATE_CONFIRM IN DATE,
  INCLINATION IN VARCHAR2,
  WIDTH_DEFECT IN VARCHAR2,
  HEIGHT_DEFECT IN VARCHAR2,
  LENGTH_DEFECT IN VARCHAR2
)
AS
BEGIN
  INSERT INTO JOURNAL_CHECKUPS (JOURNAL_CHECKUP_ID,POINT_ID,CYCLE_ID,MEASURE_TYPE_ID,
                                DEFECT_VIEW_ID,DATE_OBSERVATION,NOTE,JOURNAL_NUM,
                                WHO_ENTER,DATE_ENTER,WHO_CONFIRM,DATE_CONFIRM,INCLINATION,
								WIDTH_DEFECT,HEIGHT_DEFECT,LENGTH_DEFECT)
       VALUES (JOURNAL_CHECKUP_ID,POINT_ID,CYCLE_ID,MEASURE_TYPE_ID,
               DEFECT_VIEW_ID,DATE_OBSERVATION,NOTE,JOURNAL_NUM,
               WHO_ENTER,DATE_ENTER,WHO_CONFIRM,DATE_CONFIRM,INCLINATION,
               WIDTH_DEFECT,HEIGHT_DEFECT,LENGTH_DEFECT);
  COMMIT;
  CONFIRM_JOURNAL_CHECKUP (JOURNAL_CHECKUP_ID);
END;

--

/* Создание процедуры изменения записи в журнале осмотров */

CREATE OR REPLACE PROCEDURE U_JOURNAL_CHECKUP
(
  JOURNAL_CHECKUP_ID IN INTEGER,
  POINT_ID IN INTEGER,
  CYCLE_ID IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  DEFECT_VIEW_ID IN INTEGER,
  DATE_OBSERVATION IN DATE,
  NOTE IN VARCHAR2,
  JOURNAL_NUM IN VARCHAR2,
  WHO_ENTER IN INTEGER,
  DATE_ENTER IN DATE,
  WHO_CONFIRM IN INTEGER,
  DATE_CONFIRM IN DATE,
  INCLINATION IN VARCHAR2,
  WIDTH_DEFECT IN VARCHAR2,
  HEIGHT_DEFECT IN VARCHAR2,
  LENGTH_DEFECT IN VARCHAR2,
  OLD_JOURNAL_CHECKUP_ID IN INTEGER
)
AS
BEGIN
  UPDATE JOURNAL_CHECKUPS 
     SET JOURNAL_CHECKUP_ID=U_JOURNAL_CHECKUP.JOURNAL_CHECKUP_ID,
         POINT_ID=U_JOURNAL_CHECKUP.POINT_ID,
         CYCLE_ID=U_JOURNAL_CHECKUP.CYCLE_ID,
		 MEASURE_TYPE_ID=U_JOURNAL_CHECKUP.MEASURE_TYPE_ID,
         DEFECT_VIEW_ID=U_JOURNAL_CHECKUP.DEFECT_VIEW_ID,
         DATE_OBSERVATION=U_JOURNAL_CHECKUP.DATE_OBSERVATION,
		 NOTE=U_JOURNAL_CHECKUP.NOTE,
		 JOURNAL_NUM=U_JOURNAL_CHECKUP.JOURNAL_NUM,
         WHO_ENTER=U_JOURNAL_CHECKUP.WHO_ENTER,
         DATE_ENTER=U_JOURNAL_CHECKUP.DATE_ENTER,
         WHO_CONFIRM=U_JOURNAL_CHECKUP.WHO_CONFIRM,
         DATE_CONFIRM=U_JOURNAL_CHECKUP.DATE_CONFIRM,
		 INCLINATION=U_JOURNAL_CHECKUP.INCLINATION,
		 WIDTH_DEFECT=U_JOURNAL_CHECKUP.WIDTH_DEFECT,
		 HEIGHT_DEFECT=U_JOURNAL_CHECKUP.HEIGHT_DEFECT,
		 LENGTH_DEFECT=U_JOURNAL_CHECKUP.LENGTH_DEFECT
   WHERE JOURNAL_CHECKUP_ID=OLD_JOURNAL_CHECKUP_ID;
  COMMIT;
  CONFIRM_JOURNAL_CHECKUP(OLD_JOURNAL_CHECKUP_ID);        
END;

--

/* Создание процедуры удаления записи в журнале осмотров */

CREATE OR REPLACE PROCEDURE D_JOURNAL_CHECKUP
(
  OLD_JOURNAL_CHECKUP_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM JOURNAL_CHECKUPS
        WHERE JOURNAL_CHECKUP_ID=OLD_JOURNAL_CHECKUP_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT