/* Создание последовательности для таблицы документов осмотров */

CREATE SEQUENCE SEQ_DOC_CHECKUPS
INCREMENT BY 1 
START WITH 2500 
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание фунции генерации идентификатора таблицы документов осмотров */

CREATE OR REPLACE FUNCTION GET_DOC_CHECKUP_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_DOC_CHECKUPS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы документов осмотров */

CREATE TABLE DOC_CHECKUPS
(
  DOC_CHECKUP_ID INTEGER NOT NULL,
  JOURNAL_CHECKUP_ID INTEGER NOT NULL,
  DATE_DOC DATE NOT NULL,
  NAME VARCHAR2(250) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DOC BLOB NOT NULL,
  EXTENSION VARCHAR2(50) NOT NULL,
  PRIMARY KEY (DOC_CHECKUP_ID),
  FOREIGN KEY (JOURNAL_CHECKUP_ID) REFERENCES JOURNAL_CHECKUPS (JOURNAL_CHECKUP_ID)
) 

--

/* Создание просмотра таблицы документов осмотров */

CREATE OR REPLACE VIEW S_DOC_CHECKUPS
AS
  SELECT DC.*
    FROM DOC_CHECKUPS DC

--

/* Создание процедуры создания документов осмотра */

CREATE OR REPLACE PROCEDURE I_DOC_CHECKUP
(
  DOC_CHECKUP_ID IN INTEGER,
  JOURNAL_CHECKUP_ID IN INTEGER,
  DATE_DOC IN DATE,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DOC IN BLOB,
  EXTENSION IN VARCHAR2
)
AS
BEGIN
  INSERT INTO DOC_CHECKUPS (DOC_CHECKUP_ID,JOURNAL_CHECKUP_ID,DATE_DOC,
                            NAME,DESCRIPTION,DOC,EXTENSION)
       VALUES (DOC_CHECKUP_ID,JOURNAL_CHECKUP_ID,DATE_DOC,
               NAME,DESCRIPTION,DOC,EXTENSION);
  COMMIT;
END;

--

/* Создание процедуры изменения документов осмотра */

CREATE OR REPLACE PROCEDURE U_DOC_CHECKUP
(
  DOC_CHECKUP_ID IN INTEGER,
  JOURNAL_CHECKUP_ID IN INTEGER,
  DATE_DOC IN DATE,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  DOC IN BLOB,
  EXTENSION IN VARCHAR2,
  OLD_DOC_CHECKUP_ID IN INTEGER
)
AS
BEGIN
  UPDATE DOC_CHECKUPS 
     SET DOC_CHECKUP_ID=U_DOC_CHECKUP.DOC_CHECKUP_ID,
         JOURNAL_CHECKUP_ID=U_DOC_CHECKUP.JOURNAL_CHECKUP_ID,
         DATE_DOC=U_DOC_CHECKUP.DATE_DOC,
		 NAME=U_DOC_CHECKUP.NAME,
         DESCRIPTION=U_DOC_CHECKUP.DESCRIPTION,
		 DOC=U_DOC_CHECKUP.DOC,
		 EXTENSION=U_DOC_CHECKUP.EXTENSION 
   WHERE DOC_CHECKUP_ID=OLD_DOC_CHECKUP_ID;
  COMMIT;
END;

--

/* Создание процедуры удаления документов осмотра */

CREATE OR REPLACE PROCEDURE D_DOC_CHECKUP
(
  OLD_DOC_CHECKUP_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM DOC_CHECKUPS
        WHERE DOC_CHECKUP_ID=OLD_DOC_CHECKUP_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления документов осмотра по журналу */

CREATE OR REPLACE PROCEDURE D_DOC_CHECKUP_JOURNAL
(
  JOURNAL_CHECKUP_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM DOC_CHECKUPS
        WHERE JOURNAL_CHECKUP_ID=D_DOC_CHECKUP_JOURNAL.JOURNAL_CHECKUP_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT