/* Изменение просмотра объектов маршрута */

CREATE OR REPLACE VIEW S_ROUTE_OBJECTS
AS
  SELECT RP.ROUTE_ID,
         R.NAME AS ROUTE_NAME,
         RP.POINT_ID,
  	     P.NAME AS POINT_NAME,
	     P.OBJECT_ID,
	     O.NAME AS OBJECT_NAME,
		 OT.OBJECT_PATHS   
    FROM ROUTE_POINTS RP, ROUTES R, POINTS P, OBJECTS O,
         (SELECT OT1.OBJECT_ID, 
		         SUBSTR(MAX(SYS_CONNECT_BY_PATH(O1.NAME,'\')),2) AS OBJECT_PATHS
            FROM OBJECT_TREES OT1, OBJECTS O1
           WHERE OT1.OBJECT_ID=O1.OBJECT_ID
           START WITH OT1.PARENT_ID IS NULL
         CONNECT BY OT1.PARENT_ID=PRIOR OT1.OBJECT_TREE_ID
		   GROUP BY OT1.OBJECT_ID) OT	   
   WHERE RP.ROUTE_ID=R.ROUTE_ID
     AND RP.POINT_ID=P.POINT_ID
     AND P.OBJECT_ID=O.OBJECT_ID
	 AND O.OBJECT_ID=OT.OBJECT_ID (+)

--

/* Фиксация изменений БД */

COMMIT
