/* Добавление ссылки на алгоритмы в таблицу контроля */

ALTER TABLE CHECKINGS
ADD ALGORITHM_ID INTEGER

--

/* Создание алгоритмов на базе процедур контроля */

BEGIN
  INSERT INTO ALGORITHMS (ALGORITHM_ID,NAME,PROC_NAME,DESCRIPTION)
  SELECT GET_ALGORITHM_ID,T.NAME,T.PROC_NAME,T.DESCRIPTION 
    FROM (SELECT NAME,PROC_NAME,DESCRIPTION 
            FROM CHECKINGS
           GROUP BY NAME,PROC_NAME,DESCRIPTION) T;
  COMMIT;
END;

--

/* Изменение привязки к алгоритмам в таблице контроля */

BEGIN
  UPDATE CHECKINGS C
  SET C.ALGORITHM_ID=(SELECT A.ALGORITHM_ID 
                        FROM ALGORITHMS A 
		       WHERE A.PROC_NAME=C.PROC_NAME;
  COMMIT;
END;

--

/* Измнение сслыки на алгоритмы в таблице контроля */

ALTER TABLE CHECKINGS
MODIFY ALGORITHM_ID INTEGER NOT NULL

--

/* Добавление поля включения контроля */


ALTER TABLE CHECKINGS
ADD ENABLED INTEGER

--

/* Изменения таблицы контроля на предмет его включения */

BEGIN
  UPDATE CHECKINGS
  SET ENABLED=1;
  COMMIT;
END;

--

/* Изменения поля включения контроля */

ALTER TABLE CHECKINGS
MODIFY ENABLED INTEGER NOT NULL

--

/* Добавление вторичного ключа к таблице контроля */ 

ALTER TABLE CHECKINGS
ADD FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHMS (ALGORITHM_ID)

--

/* Удаление поля процедура из таблицы контроля */

ALTER TABLE CHECKINGS
DROP COLUMN PROC_NAME

--

/* Изменение таблицы просмотра контроля */

CREATE OR REPLACE VIEW S_CHECKINGS
AS
  SELECT C.*, 
         MT.NAME AS MEASURE_TYPE_NAME,
         MT2.PATH AS MEASURE_TYPE_PATH,
		 A.NAME AS ALGORITHM_NAME,
		 A.PROC_NAME,
		 PT.NAME AS POINT_NAME,
		 P.NAME AS PARAM_NAME
    FROM CHECKINGS C, MEASURE_TYPES MT, 
	     ALGORITHMS A, PARAMS P, POINTS PT,
         (SELECT MT.MEASURE_TYPE_ID, 
                 SUBSTR(MAX(SYS_CONNECT_BY_PATH(MT.NAME,'\')),2) AS PATH	   
		    FROM MEASURE_TYPES MT
           START WITH MT.PARENT_ID IS NULL
         CONNECT BY MT.PARENT_ID=PRIOR MT.MEASURE_TYPE_ID
           GROUP BY MT.MEASURE_TYPE_ID) MT2
   WHERE C.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID
     AND C.ALGORITHM_ID=A.ALGORITHM_ID
     AND C.PARAM_ID=P.PARAM_ID
	 AND MT.MEASURE_TYPE_ID=MT2.MEASURE_TYPE_ID
	 AND C.POINT_ID=PT.POINT_ID (+)

--

/* Изменение процедуры создания контроля */

CREATE OR REPLACE PROCEDURE I_CHECKING
(
  CHECKING_ID IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  POINT_ID IN INTEGER,
  PARAM_ID IN INTEGER,  
  ALGORITHM_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  ENABLED IN INTEGER,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO CHECKINGS (CHECKING_ID,MEASURE_TYPE_ID,POINT_ID,PARAM_ID,ALGORITHM_ID,NAME,DESCRIPTION,ENABLED,PRIORITY)
       VALUES (CHECKING_ID,MEASURE_TYPE_ID,POINT_ID,PARAM_ID,ALGORITHM_ID,NAME,DESCRIPTION,ENABLED,PRIORITY);
  COMMIT;
END;

--

/* Изменение процедуры редактирования контроля */

CREATE OR REPLACE PROCEDURE U_CHECKING
(
  CHECKING_ID IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  POINT_ID IN INTEGER,
  PARAM_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER,  
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  ENABLED IN INTEGER,
  PRIORITY IN INTEGER,
  OLD_CHECKING_ID IN INTEGER
)
AS
BEGIN
  UPDATE CHECKINGS 
     SET CHECKING_ID=U_CHECKING.CHECKING_ID,
	     MEASURE_TYPE_ID=U_CHECKING.MEASURE_TYPE_ID,
		 POINT_ID=U_CHECKING.POINT_ID,
		 PARAM_ID=U_CHECKING.PARAM_ID,
		 ALGORITHM_ID=U_CHECKING.ALGORITHM_ID,
         NAME=U_CHECKING.NAME,
         DESCRIPTION=U_CHECKING.DESCRIPTION,
		 ENABLED=U_CHECKING.ENABLED,
		 PRIORITY=U_CHECKING.PRIORITY
   WHERE CHECKING_ID=OLD_CHECKING_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT
