/* Создание функции получения таблицы из строки */

CREATE OR REPLACE FUNCTION GET_VARCHAR_TABLE
(
  VALUE IN VARCHAR2,
  DIVIDER IN VARCHAR2
) 
RETURN VARCHAR_TABLE 
PIPELINED 
AS
  RET VARCHAR_OBJECT:=VARCHAR_OBJECT(NULL);
  S VARCHAR2(1000):='';
  S1 VARCHAR2(250):='';
  POS INTEGER:=-1;
BEGIN
  S:=VALUE;
  WHILE (POS<>0) LOOP
    POS:=INSTR(S,DIVIDER);
	IF (POS<>0) THEN
	  S1:=SUBSTR(S,1,POS-1);
	  S:=SUBSTR(S,POS+LENGTH(DIVIDER));
	ELSE
	  S1:=S;
	END IF;
	RET.VALUE:=S1;
	PIPE ROW(RET);
  END LOOP;
  RETURN; 
END;  

--

/* Фиксация изменений */

COMMIT;