/* Создание процедуры добавления вида дефекта */

CREATE OR REPLACE PROCEDURE I_DEFECT_VIEW
( 
  DEFECT_VIEW_ID IN INTEGER, 
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO DEFECT_VIEWS (DEFECT_VIEW_ID,NAME,DESCRIPTION,PRIORITY) 
       VALUES (DEFECT_VIEW_ID,NAME,DESCRIPTION,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
