/* Создание процедуры добавления устройства */

CREATE OR REPLACE PROCEDURE I_DEVICE
( 
  DEVICE_ID IN INTEGER, 
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2, 
  DATE_ENTER IN DATE 
) 
AS 
BEGIN 
  INSERT INTO DEVICES (DEVICE_ID,NAME,DESCRIPTION,DATE_ENTER) 
       VALUES (DEVICE_ID,NAME,DESCRIPTION,DATE_ENTER); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
