/* Создание процедуры добавления отдела */

CREATE OR REPLACE PROCEDURE I_DIVISION
( 
  DIVISION_ID IN INTEGER, 
  PARENT_ID IN INTEGER,  
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2, 
  PRIORITY IN INTEGER 
)   
AS 
BEGIN 
  INSERT INTO DIVISIONS (DIVISION_ID,PARENT_ID,NAME,DESCRIPTION,PRIORITY)  
                 VALUES (DIVISION_ID,PARENT_ID,NAME,DESCRIPTION,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
