/* Создание процедуры добавления документа */

CREATE OR REPLACE PROCEDURE I_DOCUMENT
( 
  DOCUMENT_ID IN INTEGER, 
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2, 
  FILE_NAME IN VARCHAR2 
) 
AS 
BEGIN 
  INSERT INTO DOCUMENTS (DOCUMENT_ID,NAME,DESCRIPTION,FILE_NAME) 
       VALUES (DOCUMENT_ID,NAME,DESCRIPTION,FILE_NAME); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
