/* Создание процедуры добавления паспорта прибора */

CREATE OR REPLACE PROCEDURE I_INSTRUMENT_PASSPORT
( 
  INSTRUMENT_PASSPORT_ID IN INTEGER, 
  INSTRUMENT_ID IN INTEGER, 
  DATE_TEST IN DATE, 
  DESCRIPTION IN VARCHAR2, 
  RATIO IN FLOAT 
) 
AS 
BEGIN 
  INSERT INTO INSTRUMENT_PASSPORTS (INSTRUMENT_PASSPORT_ID,INSTRUMENT_ID,DATE_TEST,DESCRIPTION,RATIO) 
       VALUES (INSTRUMENT_PASSPORT_ID,INSTRUMENT_ID,DATE_TEST,DESCRIPTION,RATIO); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
