/* Создание процедуры добавления типоа прибора */

CREATE OR REPLACE PROCEDURE I_INSTRUMENT_TYPE
( 
  INSTRUMENT_TYPE_ID IN INTEGER, 
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2 
) 
AS 
BEGIN 
  INSERT INTO INSTRUMENT_TYPES (INSTRUMENT_TYPE_ID,NAME,DESCRIPTION) 
       VALUES (INSTRUMENT_TYPE_ID,NAME,DESCRIPTION); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
