/* Создание процедуры добавления отчета интерфейсу */

CREATE OR REPLACE PROCEDURE I_INTERFACE_REPORT
( 
  INTERFACE_REPORT_ID IN INTEGER, 
  BASE_REPORT_ID IN INTEGER, 
  INTERFACE IN VARCHAR2, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO INTERFACE_REPORTS (INTERFACE_REPORT_ID,BASE_REPORT_ID,INTERFACE,PRIORITY) 
       VALUES (INTERFACE_REPORT_ID,BASE_REPORT_ID,INTERFACE,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
