/* Создание процедуры добавления алгоритма виду измерения */

CREATE OR REPLACE PROCEDURE I_MEASURE_TYPE_ALGORITHM
( 
  MEASURE_TYPE_ID IN INTEGER, 
  ALGORITHM_ID IN INTEGER, 
  DATE_BEGIN IN DATE, 
  DATE_END IN DATE, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO MEASURE_TYPE_ALGORITHMS (MEASURE_TYPE_ID,ALGORITHM_ID,DATE_BEGIN,DATE_END,PRIORITY) 
       VALUES (MEASURE_TYPE_ID,ALGORITHM_ID,DATE_BEGIN,DATE_END,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
