/* Создание процедуры добавления параметра виду измерения */

CREATE OR REPLACE PROCEDURE I_MEASURE_TYPE_PARAM
( 
  MEASURE_TYPE_ID IN INTEGER, 
  PARAM_ID IN INTEGER, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO MEASURE_TYPE_PARAMS (MEASURE_TYPE_ID,PARAM_ID,PRIORITY) 
       VALUES (MEASURE_TYPE_ID,PARAM_ID,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
