/* Создание процедуры добавления документа объекту */

CREATE OR REPLACE PROCEDURE I_OBJECT_DOCUMENT
( 
  OBJECT_ID IN INTEGER, 
  DOCUMENT_ID IN INTEGER, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO OBJECT_DOCUMENTS (OBJECT_ID,DOCUMENT_ID,PRIORITY) 
       VALUES (OBJECT_ID,DOCUMENT_ID,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
