/* Создание процедуры добавления чертежа объекту */

CREATE OR REPLACE PROCEDURE I_OBJECT_DRAWING
( 
  OBJECT_ID IN INTEGER, 
  DRAWING_ID IN INTEGER, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO OBJECT_DRAWINGS (OBJECT_ID,DRAWING_ID,PRIORITY) 
       VALUES (OBJECT_ID,DRAWING_ID,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
