/* Создание процедуры добавления узла в дереве объектов */

CREATE OR REPLACE PROCEDURE I_OBJECT_TREE
( 
  OBJECT_TREE_ID IN INTEGER, 
  OBJECT_ID IN INTEGER, 
  PRIORITY IN INTEGER, 
  PARENT_ID IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO OBJECT_TREES (OBJECT_TREE_ID,OBJECT_ID,PRIORITY,PARENT_ID) 
       VALUES (OBJECT_TREE_ID,OBJECT_ID,PRIORITY,PARENT_ID); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
