/* Создание процедуры добавления прибора параметру */

CREATE OR REPLACE PROCEDURE I_PARAM_INSTRUMENT
( 
  PARAM_ID IN INTEGER, 
  INSTRUMENT_ID IN INTEGER, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO PARAM_INSTRUMENTS (PARAM_ID,INSTRUMENT_ID,PRIORITY) 
       VALUES (PARAM_ID,INSTRUMENT_ID,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
