/* Создание процедуры добавления права доступа */

CREATE OR REPLACE PROCEDURE I_PERMISSION
( 
  PERMISSION_ID IN INTEGER, 
  ACCOUNT_ID IN INTEGER,  
  INTERFACE IN VARCHAR2, 
  PERMISSION IN VARCHAR2, 
  PERMISSION_VALUE IN VARCHAR2 
) 
AS 
BEGIN 
  INSERT INTO PERMISSIONS (PERMISSION_ID,ACCOUNT_ID,INTERFACE,PERMISSION,PERMISSION_VALUE) 
       VALUES (PERMISSION_ID,ACCOUNT_ID,INTERFACE,PERMISSION,PERMISSION_VALUE); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
