/* Создание процедуры добавления персоны */

CREATE OR REPLACE PROCEDURE I_PERSONNEL
( 
  PERSONNEL_ID IN INTEGER, 
  DIVISION_ID IN INTEGER, 
  FNAME IN VARCHAR2, 
  NAME IN VARCHAR2, 
  SNAME IN VARCHAR2, 
  DATE_ACCEPT IN DATE, 
  DATE_SACK IN DATE 
)   
AS 
BEGIN 
  INSERT INTO PERSONNELS (PERSONNEL_ID,DIVISION_ID,FNAME,NAME,SNAME,DATE_ACCEPT,DATE_SACK)  
       VALUES (PERSONNEL_ID,DIVISION_ID,FNAME,NAME,SNAME,DATE_ACCEPT,DATE_SACK); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
