/* Создание процедуры добавления маршрута персоне */

CREATE OR REPLACE PROCEDURE I_PERSONNEL_ROUTE
( 
  PERSONNEL_ID IN INTEGER, 
  ROUTE_ID IN INTEGER, 
  DEPUTY_ID IN INTEGER, 
  DATE_PURPOSE IN DATE 
) 
AS 
BEGIN 
  INSERT INTO PERSONNEL_ROUTES (PERSONNEL_ID,ROUTE_ID,DEPUTY_ID,DATE_PURPOSE) 
       VALUES (PERSONNEL_ID,ROUTE_ID,DEPUTY_ID,DATE_PURPOSE); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
