/* Создание процедуры добавления документа точке */

CREATE OR REPLACE PROCEDURE I_POINT_DOCUMENT
( 
  POINT_ID IN INTEGER, 
  DOCUMENT_ID IN INTEGER, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO POINT_DOCUMENTS (POINT_ID,DOCUMENT_ID,PRIORITY) 
       VALUES (POINT_ID,DOCUMENT_ID,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
