/* Создание процедуры добавления прибора точке */

CREATE OR REPLACE PROCEDURE I_POINT_INSTRUMENT
( 
  POINT_ID IN INTEGER, 
  INSTRUMENT_ID IN INTEGER, 
  PARAM_ID IN INTEGER, 
  PRIORITY IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO POINT_INSTRUMENTS (POINT_ID,INSTRUMENT_ID,PARAM_ID,PRIORITY) 
       VALUES (POINT_ID,INSTRUMENT_ID,PARAM_ID,PRIORITY); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
