/* Создание процедуры добавления паспорта точки */

CREATE OR REPLACE PROCEDURE I_POINT_PASSPORT
( 
  POINT_PASSPORT_ID IN INTEGER, 
  POINT_ID IN INTEGER, 
  DATE_CHECKUP IN DATE, 
  DESCRIPTION IN VARCHAR2 
) 
AS 
BEGIN 
  INSERT INTO POINT_PASSPORTS (POINT_PASSPORT_ID,POINT_ID,DATE_CHECKUP,DESCRIPTION) 
       VALUES (POINT_PASSPORT_ID,POINT_ID,DATE_CHECKUP,DESCRIPTION); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
