/* Создание процедуры добавления маршрута */

CREATE OR REPLACE PROCEDURE I_ROUTE
( 
  ROUTE_ID IN INTEGER, 
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2, 
  DATE_ROUTE IN DATE, 
  IS_ACTIVE IN INTEGER 
) 
AS 
BEGIN 
  INSERT INTO ROUTES (ROUTE_ID,NAME,DESCRIPTION,DATE_ROUTE,IS_ACTIVE) 
       VALUES (ROUTE_ID,NAME,DESCRIPTION,DATE_ROUTE,IS_ACTIVE); 
  COMMIT; 
END;

--

/* Фиксация изменений */

COMMIT
