/* Обновление таблицы срезов */

BEGIN
  UPDATE CUTS 
     SET VIEW_NAME='S_PZM_JOURNAL_OBSERVATIONS_GMO',
         CONDITION='MEASURE_TYPE_ID=2561' 
   WHERE CUT_ID=2561;

  UPDATE CUTS 
     SET VIEW_NAME='S_PZM_JOURNAL_OBSERVATIONS_GMO',
         CONDITION='MEASURE_TYPE_ID=2562' 
   WHERE CUT_ID=2562;

  UPDATE CUTS 
     SET VIEW_NAME='S_PZM_JOURNAL_OBSERVATIONS_GMO',
         CONDITION='MEASURE_TYPE_ID=2563' 
   WHERE CUT_ID=2563;

  COMMIT;
END;