/* Создание просмотра ведомостей маршрутов */

CREATE OR REPLACE VIEW S_ROUTE_POINT_INSTRUMENTS
AS
SELECT RP.ROUTE_ID,
       P.NAME AS POINT_NAME,
       C.NAME AS CONVERTER_NAME,
	   TRIM(CHR(10) FROM TRIM(CHR(13) FROM GET_OBJECT_PATHS(P.OBJECT_ID))) AS OBJECT_PATHS,
	   P.COORDINATE_Z,
	   PI.NAME AS INSTRUMENT_NAME
  FROM POINTS P, ROUTE_POINTS RP, CONVERTERS C, 
       (SELECT PI.POINT_ID, I.NAME 
	      FROM POINT_INSTRUMENTS PI, INSTRUMENTS I
	     WHERE PI.INSTRUMENT_ID=I.INSTRUMENT_ID
		 GROUP BY PI.POINT_ID, I.NAME) PI
 WHERE RP.POINT_ID=P.POINT_ID
   AND C.CONVERTER_ID=P.POINT_ID
   AND P.POINT_ID=PI.POINT_ID(+) 
 ORDER BY RP.PRIORITY     

--

/* Фиксация изменений */ 

COMMIT