/* Создание процедуры удаления базового отчета */

CREATE OR REPLACE PROCEDURE D_BASE_REPORT (
   OLD_BASE_REPORT_ID IN INTEGER
)
AS
   OLD_NAME VARCHAR2 (250);
BEGIN
   SELECT NAME
     INTO OLD_NAME
     FROM BASE_REPORTS
    WHERE BASE_REPORT_ID = OLD_BASE_REPORT_ID;

   DELETE FROM PERMISSIONS
         WHERE INTERFACE = OLD_NAME;

   DELETE FROM BASE_REPORTS
         WHERE BASE_REPORT_ID = OLD_BASE_REPORT_ID;

   COMMIT;
END;

--

/* Фиксация изменений */

COMMIT

