/* Создание процедуры удаления записи в журнале осмотров */

CREATE OR REPLACE PROCEDURE D_JOURNAL_CHECKUP
( 
  OLD_JOURNAL_CHECKUP_ID IN INTEGER 
) 
AS 
BEGIN 
  DELETE FROM DOC_CHECKUPS 
        WHERE JOURNAL_CHECKUP_ID=OLD_JOURNAL_CHECKUP_ID; 
 
  DELETE FROM JOURNAL_CHECKUPS 
        WHERE JOURNAL_CHECKUP_ID=OLD_JOURNAL_CHECKUP_ID; 
 
  COMMIT;         
END;

--

/* Фиксация изменений */

COMMIT

