/* Создание процедуры удаления записи в полевом журнале */

CREATE OR REPLACE PROCEDURE D_JOURNAL_FIELD
( 
  OLD_JOURNAL_FIELD_ID IN INTEGER 
) 
AS 
BEGIN 
  DELETE FROM JOURNAL_OBSERVATIONS 
        WHERE JOURNAL_FIELD_ID=OLD_JOURNAL_FIELD_ID; 
 
  DELETE FROM JOURNAL_FIELDS 
        WHERE JOURNAL_FIELD_ID=OLD_JOURNAL_FIELD_ID; 
  COMMIT;         
END;

--

/* Фиксация изменений */

COMMIT

