/* Создание процедуры удаления прибора точки */

CREATE OR REPLACE PROCEDURE D_POINT_INSTRUMENT
( 
  OLD_POINT_ID IN INTEGER, 
  OLD_INSTRUMENT_ID IN INTEGER, 
  OLD_PARAM_ID IN INTEGER 
) 
AS 
BEGIN 
  DELETE FROM POINT_INSTRUMENTS 
        WHERE POINT_ID=OLD_POINT_ID 
          AND INSTRUMENT_ID=OLD_INSTRUMENT_ID 
    AND PARAM_ID=OLD_PARAM_ID; 
  COMMIT;         
END;

--

/* Фиксация изменений */

COMMIT

