/* Создание процедуры установки значения по умолчанию для частоты */

CREATE OR REPLACE PROCEDURE DEFAULT_FREQUENCY
(
  POINT_ID INTEGER,
  PARAM_ID_2 IN INTEGER,
  INSTRUMENT_ID_2 IN INTEGER,
  MEASHURE_UNIT_ID_2 IN INTEGER,
  VALUE_2 IN OUT FLOAT,
  VALUE_3 IN OUT FLOAT
)  
AS
BEGIN
  IF (VALUE_2 IS NULL) THEN
    VALUE_2:=0.0;
  END IF;
  IF (VALUE_2<>0.0) THEN
    VALUE_3:=1/VALUE_2*1000;
  END IF;
END;

--

/* Фиксация изменений БД */

COMMIT