/* Создание процедуры удаления данных по виду измерения и циклу */

CREATE OR REPLACE PROCEDURE DELETE_BY_CYCLE
(
  MEASURE_TYPE_ID IN INTEGER,
  CYCLE_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM JOURNAL_OBSERVATIONS
   WHERE MEASURE_TYPE_ID=DELETE_BY_CYCLE.MEASURE_TYPE_ID
     AND CYCLE_ID=DELETE_BY_CYCLE.CYCLE_ID;
  
  DELETE FROM JOURNAL_FIELDS
   WHERE MEASURE_TYPE_ID=DELETE_BY_CYCLE.MEASURE_TYPE_ID
     AND CYCLE_ID=DELETE_BY_CYCLE.CYCLE_ID;
	 
  COMMIT;	 
END;

--

/* Фиксация изменений БД */

COMMIT