/* Создание процедуры расчета относительных деформации */

CREATE OR REPLACE PROCEDURE CALCULATE_NDS_R_DEFORM
(
  POINT_ID IN INTEGER,
  FREQUENCY IN FLOAT,
  RELATIVE_DEFORMATION OUT FLOAT
)
AS
  RATIO_INSTRUMENT FLOAT;
  MODULE_FREQUENCY FLOAT;
BEGIN
  IF POINT_ID IS NOT NULL THEN
    RATIO_INSTRUMENT:=NULL;
    FOR INC IN (SELECT CP.VALUE,
 	                   CP.DATE_BEGIN,
                       CP.DATE_END
                  FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
                 WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                   AND C.CONVERTER_ID=P.POINT_ID
                   AND P.POINT_ID=CALCULATE_NDS_R_DEFORM.POINT_ID
                   AND C.PARAM_ID=60018 /* Коэффициент прибора */
                 ORDER BY CP.DATE_BEGIN) LOOP
      RATIO_INSTRUMENT:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');				   
      EXIT WHEN RATIO_INSTRUMENT IS NOT NULL;
    END LOOP;
	
/*	DBMS_OUTPUT.PUT_LINE('RATIO_INSTRUMENT='||TO_CHAR(RATIO_INSTRUMENT));*/
  
	MODULE_FREQUENCY:=NULL;
    FOR INC IN (SELECT CP.VALUE,
 	                   CP.DATE_BEGIN,
                       CP.DATE_END
                  FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
                 WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                   AND C.CONVERTER_ID=P.POINT_ID
                   AND P.POINT_ID=CALCULATE_NDS_R_DEFORM.POINT_ID
                   AND C.PARAM_ID=60019 /* Модуль частоты */
                 ORDER BY CP.DATE_BEGIN) LOOP
      MODULE_FREQUENCY:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');				   
      EXIT WHEN MODULE_FREQUENCY IS NOT NULL;
    END LOOP;

/*	DBMS_OUTPUT.PUT_LINE('MODULE_FREQUENCY='||TO_CHAR(MODULE_FREQUENCY));*/
  
    IF (RATIO_INSTRUMENT IS NOT NULL) AND 
	   (MODULE_FREQUENCY IS NOT NULL) THEN
	   
      RELATIVE_DEFORMATION:=RATIO_INSTRUMENT*(POWER(FREQUENCY,2)/1000-MODULE_FREQUENCY);
	  
	END IF;  
  END IF;	
END;

--

/* Фиксация изменений БД */

COMMIT