/* Создание процедуры расчета раскрытия контактного шва */

CREATE OR REPLACE PROCEDURE CALCULATE_NDS_CONTACT_OPENING
(
  POINT_ID IN INTEGER,
  FREQUENCY IN FLOAT,
  DATE_OBSERVATION IN DATE,
  MEASURE_TYPE_ID IN INTEGER,
  CYCLE_ID IN INTEGER,
  IS_BASE IN INTEGER,
  OPENING OUT FLOAT
)
AS
  B0 FLOAT;
  B1 FLOAT;
  B2 FLOAT;
  LENGTH_INSTRUMENT FLOAT;
  LENGTH_0 FLOAT;
  POINT_NAME INTEGER;
BEGIN

  SELECT NAME INTO POINT_NAME FROM POINTS WHERE POINT_ID=CALCULATE_NDS_CONTACT_OPENING.POINT_ID;
  DBMS_OUTPUT.PUT_LINE('POINT_NAME='||TO_CHAR(POINT_NAME));			
  DBMS_OUTPUT.PUT_LINE('DATE='||TO_CHAR(DATE_OBSERVATION));		
  DBMS_OUTPUT.PUT_LINE('FREQUENCY='||TO_CHAR(FREQUENCY));		
  
  B0:=NULL;
  FOR INC IN (SELECT CP.VALUE,
 	                 CP.DATE_BEGIN,
                     CP.DATE_END
                FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
               WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                 AND C.CONVERTER_ID=P.POINT_ID
                 AND P.POINT_ID=CALCULATE_NDS_CONTACT_OPENING.POINT_ID
                 AND C.PARAM_ID=60014 /* B0 */
               ORDER BY CP.DATE_BEGIN) LOOP
    B0:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');			   
	EXIT WHEN B0 IS NOT NULL;
  END LOOP;
  
  DBMS_OUTPUT.PUT_LINE('B0='||TO_CHAR(B0));
	  
  B1:=NULL;
  FOR INC IN (SELECT CP.VALUE,
 	                 CP.DATE_BEGIN,
                     CP.DATE_END
                FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
               WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                 AND C.CONVERTER_ID=P.POINT_ID
                 AND P.POINT_ID=CALCULATE_NDS_CONTACT_OPENING.POINT_ID
                 AND C.PARAM_ID=60015 /* B1 */
               ORDER BY CP.DATE_BEGIN) LOOP
    B1:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');			   
	EXIT WHEN B1 IS NOT NULL;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('B1='||TO_CHAR(B1));

  B2:=NULL;
  FOR INC IN (SELECT CP.VALUE,
 	                 CP.DATE_BEGIN,
                     CP.DATE_END
                FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
               WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                 AND C.CONVERTER_ID=P.POINT_ID
                 AND P.POINT_ID=CALCULATE_NDS_CONTACT_OPENING.POINT_ID
                 AND C.PARAM_ID=60016 /* B2 */
               ORDER BY CP.DATE_BEGIN) LOOP
    B2:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');			   
	EXIT WHEN B2 IS NOT NULL;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('B2='||TO_CHAR(B2));

  LENGTH_INSTRUMENT:=NULL;
  FOR INC IN (SELECT CP.VALUE,
 	                 CP.DATE_BEGIN,
                     CP.DATE_END
                FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
               WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                 AND C.CONVERTER_ID=P.POINT_ID
                 AND P.POINT_ID=CALCULATE_NDS_CONTACT_OPENING.POINT_ID
                 AND C.PARAM_ID=60022 /* Длина прибора */
               ORDER BY CP.DATE_BEGIN) LOOP
    LENGTH_INSTRUMENT:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');			   
	EXIT WHEN LENGTH_INSTRUMENT IS NOT NULL;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('LENGTH_INSTRUMENT='||TO_CHAR(LENGTH_INSTRUMENT));

  LENGTH_0:=NULL;
  FOR INC IN (SELECT CP.VALUE,
 	                 CP.DATE_BEGIN,
                     CP.DATE_END
                FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
               WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                 AND C.CONVERTER_ID=P.POINT_ID
                 AND P.POINT_ID=CALCULATE_NDS_CONTACT_OPENING.POINT_ID
                 AND C.PARAM_ID=60027 /* Начальное удлинение */
               ORDER BY CP.DATE_BEGIN) LOOP
    LENGTH_0:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');			   
	EXIT WHEN LENGTH_0 IS NOT NULL;
  END LOOP;
	  
  DBMS_OUTPUT.PUT_LINE('LENGTH_0='||TO_CHAR(LENGTH_0));

  IF (B0 IS NOT NULL) AND
     (B1 IS NOT NULL) AND
	 (B2 IS NOT NULL) AND
	 (LENGTH_INSTRUMENT IS NOT NULL) AND
	 (LENGTH_0 IS NOT NULL) THEN
	
	OPENING:=(B0+(B1*FREQUENCY/POWER(10,3))+(B2*POWER(FREQUENCY,2)/POWER(10,6)))*LENGTH_INSTRUMENT/POWER(10,5)-LENGTH_0; 
  END IF;
  
  DBMS_OUTPUT.PUT_LINE('OPENING='||TO_CHAR(OPENING));	 
END;

--

/* Фиксация изменений БД */

COMMIT