/* Обновление таблицы просмотра измерительных точек */

CREATE OR REPLACE VIEW S_POINTS
AS 
SELECT P.*, PT.NAME AS POINT_TYPE_NAME, O.NAME AS OBJECT_NAME, OT.OBJECT_PATHS  
    FROM POINTS P, POINT_TYPES PT, OBJECTS O,
	    (SELECT OT1.OBJECT_ID, SUBSTR(MAX(SYS_CONNECT_BY_PATH(O1.NAME,'\')),2) AS OBJECT_PATHS
                        FROM OBJECT_TREES OT1, OBJECTS O1
                       WHERE OT1.OBJECT_ID=O1.OBJECT_ID
                       START WITH OT1.PARENT_ID IS NULL
                     CONNECT BY OT1.PARENT_ID=PRIOR OT1.OBJECT_TREE_ID
					   GROUP BY OT1.OBJECT_ID) OT
   WHERE P.POINT_TYPE_ID=PT.POINT_TYPE_ID
     AND P.OBJECT_ID=O.OBJECT_ID
	 AND OT.OBJECT_ID=O.OBJECT_ID

--

/* Фиксация изменений БД */

COMMIT