/* Создание последовательности для таблицы срезов */

CREATE SEQUENCE SEQ_CUTS 
INCREMENT BY 1 
START WITH 2500
MAXVALUE 1.0E28 
MINVALUE 2500
NOCYCLE 
CACHE 20 
NOORDER

--

/* Создание функции генерации идентификатора для таблицы срезов */

CREATE FUNCTION GET_CUT_ID RETURN INTEGER IS
  ID INTEGER;
BEGIN
  SELECT SEQ_CUTS.NEXTVAL INTO ID FROM DUAL;
  RETURN ID;
END;

--

/* Создание таблицы срезов */

CREATE TABLE CUTS 
(
  CUT_ID INTEGER NOT NULL,
  MEASURE_TYPE_ID INTEGER,
  OBJECT_ID INTEGER,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250), 
  VIEW_NAME VARCHAR2(100) NOT NULL,
  PROC_NAME VARCHAR2(100),
  DETERMINATION CLOB NOT NULL,
  CONDITION VARCHAR2(250),
  PRIORITY INTEGER NOT NULL,
  CUT_TYPE INTEGER NOT NULL,
  PRIMARY KEY (CUT_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID)
)

--

/* Создание просмотра таблицы срезов */

CREATE OR REPLACE VIEW S_CUTS
AS
  SELECT C.*, 
         MT.NAME AS MEASURE_TYPE_NAME,
         O.NAME AS OBJECT_NAME
    FROM CUTS C, MEASURE_TYPES MT, OBJECTS O
   WHERE C.MEASURE_TYPE_ID=MT.MEASURE_TYPE_ID (+)
     AND C.OBJECT_ID=O.OBJECT_ID (+)

--

/* Создание процедуры создания среза */

CREATE OR REPLACE PROCEDURE I_CUT
(
  CUT_ID IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  OBJECT_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  VIEW_NAME IN VARCHAR2,
  DETERMINATION IN CLOB,
  CONDITION IN VARCHAR2,
  PROC_NAME IN VARCHAR2,
  PRIORITY IN INTEGER,
  CUT_TYPE IN INTEGER
)
AS
BEGIN
  INSERT INTO CUTS (CUT_ID,MEASURE_TYPE_ID,OBJECT_ID,VIEW_NAME,NAME,DESCRIPTION,
                    DETERMINATION,CONDITION,PROC_NAME,PRIORITY,CUT_TYPE)
       VALUES (CUT_ID,MEASURE_TYPE_ID,OBJECT_ID,VIEW_NAME,NAME,DESCRIPTION,
               DETERMINATION,CONDITION,PROC_NAME,PRIORITY,CUT_TYPE);
	   
  COMMIT;
END;

--

/* Создание процедуры изменения среза */

CREATE OR REPLACE PROCEDURE U_CUT
(
  CUT_ID IN INTEGER,
  MEASURE_TYPE_ID IN INTEGER,
  OBJECT_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  VIEW_NAME IN VARCHAR2,
  DETERMINATION IN CLOB,
  CONDITION IN VARCHAR2,
  PROC_NAME IN VARCHAR2,
  PRIORITY IN INTEGER,
  CUT_TYPE IN INTEGER,
  OLD_CUT_ID IN INTEGER
)
AS
BEGIN
  UPDATE CUTS 
     SET CUT_ID=U_CUT.CUT_ID,
	     MEASURE_TYPE_ID=U_CUT.MEASURE_TYPE_ID,
		 OBJECT_ID=U_CUT.OBJECT_ID,
         VIEW_NAME=U_CUT.VIEW_NAME,
         NAME=U_CUT.NAME,
		 DESCRIPTION=U_CUT.DESCRIPTION,
		 DETERMINATION=U_CUT.DETERMINATION,
		 CONDITION=U_CUT.CONDITION,
		 PROC_NAME=U_CUT.PROC_NAME,
		 PRIORITY=U_CUT.PRIORITY,
		 CUT_TYPE=U_CUT.CUT_TYPE
   WHERE CUT_ID=OLD_CUT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления среза */

CREATE OR REPLACE PROCEDURE D_CUT
(
  OLD_CUT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM CUTS
        WHERE CUT_ID=OLD_CUT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT