/* Создание таблицы связи объектов и групп */

CREATE TABLE GROUP_OBJECTS 
(
  GROUP_ID INTEGER NOT NULL, 
  OBJECT_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (GROUP_ID,OBJECT_ID),
  FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID)
)


--

/* Создание просмотра связи объектов и групп */

CREATE OR REPLACE VIEW S_GROUP_OBJECTS
AS
  SELECT GO.*, 
         G.NAME AS GROUP_NAME, 
		 O.NAME AS OBJECT_NAME
    FROM GROUP_OBJECTS GO, GROUPS G, OBJECTS O
   WHERE G.GROUP_ID=GO.GROUP_ID 
     AND O.OBJECT_ID=GO.OBJECT_ID

--

/* Создание процедуры добавления объекта группе */

CREATE OR REPLACE PROCEDURE I_GROUP_OBJECT
(
  GROUP_ID IN INTEGER,
  OBJECT_ID IN INTEGER,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO GROUP_OBJECTS (GROUP_ID,OBJECT_ID,PRIORITY)
       VALUES (GROUP_ID,OBJECT_ID,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения объекта у группы */

CREATE OR REPLACE PROCEDURE U_GROUP_OBJECT
(
  GROUP_ID IN INTEGER,
  OBJECT_ID IN INTEGER,
  PRIORITY IN INTEGER,
  OLD_GROUP_ID IN INTEGER,
  OLD_OBJECT_ID IN INTEGER
)
AS
BEGIN
  UPDATE GROUP_OBJECTS 
     SET GROUP_ID=U_GROUP_OBJECT.GROUP_ID,
         OBJECT_ID=U_GROUP_OBJECT.OBJECT_ID,
         PRIORITY=U_GROUP_OBJECT.PRIORITY
   WHERE GROUP_ID=OLD_GROUP_ID 
     AND OBJECT_ID=OLD_OBJECT_ID;
  COMMIT;        
END;

--

/* Создание процедуры удаления объекта у группы */

CREATE PROCEDURE D_GROUP_OBJECT
(
  OLD_GROUP_ID IN INTEGER,
  OLD_OBJECT_ID IN INTEGER
)
AS
BEGIN
  DELETE FROM GROUP_OBJECTS
        WHERE GROUP_ID=OLD_GROUP_ID
          AND OBJECT_ID=OLD_OBJECT_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT