/* Создание просмотра таблицы алгоритмов видов измеренияв */

CREATE OR REPLACE VIEW S_MEASURE_TYPE_ALGORITHMS
AS
  SELECT MTA.*, 
         MT.NAME AS MEASURE_TYPE_NAME, 
         A.NAME AS ALGORITHM_NAME,
		 A.DESCRIPTION AS ALGORITHM_DESCRIPTION,
		 A.PROC_NAME AS ALGORITHM_PROC_NAME
    FROM MEASURE_TYPE_ALGORITHMS MTA, MEASURE_TYPES MT, ALGORITHMS A
   WHERE MT.MEASURE_TYPE_ID=MTA.MEASURE_TYPE_ID 
     AND A.ALGORITHM_ID=MTA.ALGORITHM_ID

--

/* Создание процедуры добавления алгоритма виду измерения */

CREATE OR REPLACE PROCEDURE I_MEASURE_TYPE_ALGORITHM
(
  MEASURE_TYPE_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER,
  DATE_BEGIN IN DATE,
  DATE_END IN DATE,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO MEASURE_TYPE_ALGORITHMS (MEASURE_TYPE_ID,ALGORITHM_ID,DATE_BEGIN,DATE_END,PRIORITY)
       VALUES (MEASURE_TYPE_ID,ALGORITHM_ID,DATE_BEGIN,DATE_END,PRIORITY);
  COMMIT;
END;

--

/* Создание процедуры изменения алгоритма вида измерения */

CREATE OR REPLACE PROCEDURE U_MEASURE_TYPE_ALGORITHM
(
  MEASURE_TYPE_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER,
  DATE_BEGIN IN DATE,
  DATE_END IN DATE,
  PRIORITY IN INTEGER,
  OLD_MEASURE_TYPE_ID IN INTEGER,
  OLD_ALGORITHM_ID IN INTEGER
)
AS
BEGIN
  UPDATE MEASURE_TYPE_ALGORITHMS 
     SET MEASURE_TYPE_ID=U_MEASURE_TYPE_ALGORITHM.MEASURE_TYPE_ID,
         ALGORITHM_ID=U_MEASURE_TYPE_ALGORITHM.ALGORITHM_ID,
		 DATE_BEGIN=U_MEASURE_TYPE_ALGORITHM.DATE_BEGIN,
		 DATE_END=U_MEASURE_TYPE_ALGORITHM.DATE_END,
         PRIORITY=U_MEASURE_TYPE_ALGORITHM.PRIORITY
   WHERE MEASURE_TYPE_ID=OLD_MEASURE_TYPE_ID 
     AND ALGORITHM_ID=OLD_ALGORITHM_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT