/* Добавление колонки определени в таблицу параметров */

ALTER TABLE PARAMS
ADD DETERMINATION CLOB

--

/* Создание просмотра таблицы параметров */

CREATE OR REPLACE VIEW S_PARAMS
AS
  SELECT P.*, 
         A.NAME AS ALGORITHM_NAME
    FROM PARAMS P, ALGORITHMS A 
   WHERE P.ALGORITHM_ID=A.ALGORITHM_ID (+)


--

/* Создание процедуры создания параметра */

CREATE OR REPLACE PROCEDURE I_PARAM
(
  PARAM_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PARAM_TYPE IN INTEGER,
  FORMAT IN VARCHAR2,
  DETERMINATION IN CLOB
)
AS
BEGIN
  INSERT INTO PARAMS (PARAM_ID,ALGORITHM_ID,NAME,DESCRIPTION,PARAM_TYPE,FORMAT,DETERMINATION)
       VALUES (PARAM_ID,ALGORITHM_ID,NAME,DESCRIPTION,PARAM_TYPE,FORMAT,DETERMINATION);
  COMMIT;
END;

--

/* Создание процедуры изменения параметра */


CREATE OR REPLACE PROCEDURE U_PARAM
(
  PARAM_ID IN INTEGER,
  ALGORITHM_ID IN INTEGER,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PARAM_TYPE IN INTEGER,
  FORMAT IN VARCHAR2,
  DETERMINATION IN CLOB,
  OLD_PARAM_ID IN INTEGER
)
AS
BEGIN
  UPDATE PARAMS 
     SET PARAM_ID=U_PARAM.PARAM_ID,
         ALGORITHM_ID=U_PARAM.ALGORITHM_ID,
         NAME=U_PARAM.NAME,
         DESCRIPTION=U_PARAM.DESCRIPTION,
         PARAM_TYPE=U_PARAM.PARAM_TYPE,
		 FORMAT=U_PARAM.FORMAT,
		 DETERMINATION=U_PARAM.DETERMINATION
   WHERE PARAM_ID=OLD_PARAM_ID;
  COMMIT;        
END;

--

/* Фиксация изменений БД */

COMMIT