/* Создание просмотра таблицы параметров видов измерения */

CREATE OR REPLACE VIEW S_MEASURE_TYPE_PARAMS
AS
  SELECT MTP.*, 
         MT.NAME AS MEASURE_TYPE_NAME, 
         P.NAME AS PARAM_NAME,
		 P.DESCRIPTION AS PARAM_DESCRIPTION,
		 P.PARAM_TYPE,
		 P.FORMAT AS PARAM_FORMAT,
		 P.ALGORITHM_ID,
		 A.NAME AS ALGORITHM_NAME,
		 A.PROC_NAME AS ALGORITHM_PROC_NAME,
		 P.DETERMINATION AS PARAM_DETERMINATION
    FROM MEASURE_TYPE_PARAMS MTP, MEASURE_TYPES MT, PARAMS P, ALGORITHMS A
   WHERE MT.MEASURE_TYPE_ID=MTP.MEASURE_TYPE_ID 
     AND P.PARAM_ID=MTP.PARAM_ID
	 AND P.ALGORITHM_ID=A.ALGORITHM_ID (+)
ORDER BY MTP.PRIORITY

--

/* Фиксация изменений БД */

COMMIT