/* Создание процедуры расчета невязки */

CREATE OR REPLACE PROCEDURE CONFIRM_ERROR_MARK (JOURNAL_FIELD_ID IN INTEGER, ALGORITHM_ID IN INTEGER)
AS JOURNAL_OBSERVATION_ID INTEGER;
AMEASURE_TYPE_ID INTEGER;
ACYCLE_ID INTEGER;
AWHO_CONFIRM INTEGER;
ADATE_CONFIRM DATE;
AGROUP_ID VARCHAR2(32);
APRIORITY INTEGER;
APOINT_ID INTEGER;
ADATE_OBSERVATION DATE;
APARAM_ID INTEGER;
DISPLACEMENT FLOAT;

F_OT FLOAT;
L_OT FLOAT;
M_OT FLOAT;
M_OT_INT INTEGER;
M_OT_STR VARCHAR2(100);
LAST_SYMB VARCHAR2(1);
ST VARCHAR2(100);
M FLOAT;
SUM_F FLOAT;
SUM_L FLOAT;
SUM_SQR FLOAT;
NAP_XODA INTEGER;

 BEGIN
 SELECT MEASURE_TYPE_ID,CYCLE_ID,WHO_CONFIRM,DATE_CONFIRM,GROUP_ID,PRIORITY,POINT_ID,DATE_OBSERVATION,PARAM_ID
 INTO AMEASURE_TYPE_ID,ACYCLE_ID,AWHO_CONFIRM,ADATE_CONFIRM,AGROUP_ID,APRIORITY,APOINT_ID,ADATE_OBSERVATION,APARAM_ID
 FROM JOURNAL_FIELDS
 WHERE JOURNAL_FIELD_ID=CONFIRM_ERROR_MARK.JOURNAL_FIELD_ID;

 NAP_XODA:=NULL;
 SELECT VALUE INTO NAP_XODA FROM JOURNAL_OBSERVATIONS WHERE GROUP_ID=AGROUP_ID AND PARAM_ID=15122;

 IF APARAM_ID=15121 AND NAP_XODA=1/* Отсчет (ход обратно) */ THEN
 	DELETE FROM JOURNAL_OBSERVATIONS
 	WHERE JOURNAL_FIELD_ID=CONFIRM_ERROR_MARK.JOURNAL_FIELD_ID
 	AND ALGORITHM_ID=CONFIRM_ERROR_MARK.ALGORITHM_ID
 	AND MEASURE_TYPE_ID=AMEASURE_TYPE_ID
 	AND CYCLE_ID=ACYCLE_ID
 	AND DATE_OBSERVATION=ADATE_OBSERVATION
 	AND GROUP_ID=AGROUP_ID
 	AND POINT_ID=APOINT_ID
 	AND PARAM_ID=17201; /* Невязка между ходом прямо и обратно */
 	COMMIT;
 	IF (AWHO_CONFIRM IS NOT NULL) THEN
 	   /* Обработка */

	   IF (APARAM_ID=15121) AND (NAP_XODA=1) THEN

	   	  /* Находим значения отсчета(ход прямо), отсчета(ход обратно) и место нуля */
		  SELECT VALUE INTO L_OT FROM JOURNAL_OBSERVATIONS WHERE JOURNAL_FIELD_ID=CONFIRM_ERROR_MARK.JOURNAL_FIELD_ID AND PARAM_ID=15121;

		  F_OT:=0;
		  FOR INC IN (SELECT GROUP_ID, VALUE FROM JOURNAL_OBSERVATIONS WHERE CYCLE_ID=ACYCLE_ID AND POINT_ID=APOINT_ID AND PARAM_ID=15121) LOOP
		  SELECT VALUE INTO NAP_XODA FROM JOURNAL_OBSERVATIONS WHERE GROUP_ID=INC.GROUP_ID AND PARAM_ID=15122;
		  IF NAP_XODA=0 THEN
		  	  F_OT:=INC.VALUE;
		  END IF;
		  END LOOP;

		  /* Находим значение среднего отсчета */
		  M_OT:=(F_OT+L_OT)/2;
		  M_OT:=M_OT*100;
		  M_OT_INT:=M_OT-MOD(M_OT,1);
		  M_OT_STR:=TO_NCHAR(M_OT_INT);
		  SELECT SUBSTR(M_OT_STR,LENGTH(M_OT_STR),1) INTO LAST_SYMB FROM DUAL;

		  IF LAST_SYMB='0' THEN M_OT:=M_OT_INT/100; END IF;

		  IF LAST_SYMB='1' OR LAST_SYMB='2' OR LAST_SYMB='3' OR LAST_SYMB='4' THEN
		  SELECT SUBSTR(M_OT_STR, 1, LENGTH(M_OT_STR)-1) INTO ST FROM DUAL;
		  ST:=ST||'2';
		  M_OT_INT:=TO_NUMBER(ST);
		  M_OT:=M_OT_INT/100;
		  END IF;

		  IF LAST_SYMB='5' THEN M_OT:=M_OT_INT/100; END IF;

		  IF LAST_SYMB='6' OR LAST_SYMB='7' OR LAST_SYMB='8' OR LAST_SYMB='9' THEN
		  SELECT SUBSTR(M_OT_STR, 1, LENGTH(M_OT_STR)-1) INTO ST FROM DUAL;
		  ST:=ST||'8';
		  M_OT_INT:=TO_NUMBER(ST);
		  M_OT:=M_OT_INT/100;
		  END IF;

		  /* Находим значение невязки */
		  SUM_SQR:=0;
		  FOR INC IN (SELECT VALUE, POINT_ID, GROUP_ID FROM JOURNAL_OBSERVATIONS WHERE CYCLE_ID=ACYCLE_ID AND PARAM_ID=15121) LOOP
		  SELECT VALUE INTO NAP_XODA FROM JOURNAL_OBSERVATIONS WHERE GROUP_ID=INC.GROUP_ID AND PARAM_ID=15122;
		  IF NAP_XODA=0 THEN
		  	  SUM_F:=INC.VALUE;
			  FOR INC2 IN (SELECT VALUE, GROUP_ID FROM JOURNAL_OBSERVATIONS WHERE CYCLE_ID=ACYCLE_ID AND PARAM_ID=15121 AND POINT_ID=INC.POINT_ID) LOOP
			  SELECT VALUE INTO NAP_XODA FROM JOURNAL_OBSERVATIONS WHERE GROUP_ID=INC2.GROUP_ID AND PARAM_ID=15122;
		  	  IF NAP_XODA=1 THEN
			  SUM_L:=INC2.VALUE;
			  SUM_SQR:=SUM_SQR+POWER(SUM_F-SUM_L,2);
			  END IF;
			  END LOOP;
		  END IF;
		  END LOOP;

		  M:=ROUND(SQRT(SUM_SQR/110)*0.5*1000)/1000;

		  I_JOURNAL_OBSERVATION(GET_JOURNAL_OBSERVATION_ID, JOURNAL_FIELD_ID, NULL, AMEASURE_TYPE_ID, NULL, ADATE_OBSERVATION, ACYCLE_ID, APOINT_ID, 17201,/* Невязка */ M, AWHO_CONFIRM, ADATE_CONFIRM, ALGORITHM_ID, AGROUP_ID, APRIORITY);
	   END IF;

 	   /* Обработка */

 	END IF;
 END IF;
 END;

--

/* Фиксация изменений БД */

COMMIT

