/* Создание процедуры установки значения отсчета по умолчанию */

CREATE OR REPLACE PROCEDURE DEFAULT_OTSCHET_MARK  (
POINT_ID INTEGER,
CYCLE_ID INTEGER,
PARAM_ID_1 IN INTEGER,
INSTRUMENT_ID_1 IN INTEGER,
MEASHURE_UNIT_ID_1 IN INTEGER,
VALUE_1 IN OUT FLOAT,
VALUE_2 IN FLOAT  )
AS
BEGIN
IF (VALUE_1 IS NULL) THEN
   VALUE_1:=0.0;
END IF;
END;

--

/* Фиксация изменений БД */

COMMIT

