/* Создание процедуры получения значения разницы между отсчетами ход прямо и ход обратно */

CREATE OR REPLACE PROCEDURE DEFAULT_DIFFERENCE_COURSE  (
CYCLE_ID IN INTEGER,
POINT_ID IN INTEGER,
VALUE_1 IN FLOAT,
VALUE_2 IN FLOAT,
VALUE_3 IN OUT FLOAT)
AS

V1 FLOAT;
V2 FLOAT;
NAP INTEGER;
DIFF FLOAT;
P_ID INTEGER;
C_ID INTEGER;

BEGIN
	 P_ID:=POINT_ID;
	 C_ID:=CYCLE_ID;
	 IF VALUE_2=0 THEN
	 DIFF:=0;
	 END IF;
	 IF VALUE_2=1 THEN
	 V1:=NULL;
	 FOR INC IN (SELECT VALUE, GROUP_ID FROM JOURNAL_FIELDS WHERE POINT_ID=P_ID AND CYCLE_ID=C_ID AND PARAM_ID=15121 ORDER BY DATE_OBSERVATION) LOOP
	 	 SELECT VALUE INTO NAP FROM JOURNAL_FIELDS WHERE PARAM_ID=15122 AND GROUP_ID=INC.GROUP_ID;
		 IF NAP=0 THEN
	 	 	V1:=INC.VALUE;
		 END IF;
	 END LOOP;
	 IF V1 IS NULL THEN
	 	DIFF:=0;
	 END IF;
	 IF V1 IS NOT NULL THEN
	 V2:=VALUE_1;
	 DIFF:=ABS(V2-V1);
	 END IF;
	 END IF;
	 VALUE_3:=DIFF;
END;

--

/* Фиксация изменений БД */

COMMIT
