/* Создание типа объекта Струнно-оптического створа журнала наблюдений */

CREATE OR REPLACE TYPE SOS_JOURNAL_OBSERVATION_OBJECT 
AS OBJECT
(
  CYCLE_ID INTEGER,
  CYCLE_NUM INTEGER,
  DATE_OBSERVATION DATE,
  POINT_ID INTEGER,
  POINT_NAME INTEGER,
  CONVERTER_ID INTEGER,
  CONVERTER_NAME VARCHAR2(100),
  PLACE_ZERO FLOAT,
  DIRECTION_MOVE FLOAT,
  VALUE FLOAT,
  DIFFERENCE_MOVE FLOAT,
  VALUE_AVERAGE FLOAT,
  OFFSET_MARK_BEGIN_OBSERV FLOAT,
  OFFSET_MARK_CYCLE_ZERO FLOAT,
  CURRENT_OFFSET_MARK FLOAT,
  OBJECT_PATHS VARCHAR2(1000)
)

--

/* Создание типа таблицы Струнно-оптического створа журнала наблюдений */

CREATE OR REPLACE TYPE SOS_JOURNAL_OBSERVATION_TABLE 
AS TABLE OF SOS_JOURNAL_OBSERVATION_OBJECT

--

/* Создание функции просмотра Струнно-оптического створа в журнале наблюдений */

CREATE OR REPLACE FUNCTION GET_SOS_JOURNAL_OBSERVATIONS
(
  IS_CLOSE INTEGER
)
RETURN SOS_JOURNAL_OBSERVATION_TABLE
PIPELINED
IS
  INC2 SOS_JOURNAL_OBSERVATION_OBJECT:=SOS_JOURNAL_OBSERVATION_OBJECT(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                                                                      NULL,NULL,NULL,NULL,NULL,NULL,NULL);
  NUM_MIN INTEGER:=NULL;
  NUM_MAX INTEGER:=NULL;
BEGIN
  FOR INC IN (SELECT MIN(CYCLE_NUM) AS NUM_MIN, MAX(CYCLE_NUM) AS NUM_MAX 
                FROM CYCLES
               WHERE IS_CLOSE=GET_SOS_JOURNAL_OBSERVATIONS.IS_CLOSE) LOOP
    NUM_MIN:=INC.NUM_MIN;
	NUM_MAX:=INC.NUM_MAX;    			   
    EXIT;			   
  END LOOP;			    
   
  FOR INC1 IN (SELECT /*+ INDEX (JF) INDEX (C) INDEX (P) INDEX (RP) INDEX (CR) */
                      JO.DATE_OBSERVATION,
                      JO.CYCLE_ID,
                      C.CYCLE_NUM,
                      JO.POINT_ID,
                      P.NAME AS POINT_NAME,
                      CR.CONVERTER_ID,
                      CR.NAME AS CONVERTER_NAME,
  					  MIN(DECODE(JO.PARAM_ID,15120,JO.VALUE,NULL)) AS PLACE_ZERO,  
  					  MIN(DECODE(JO.PARAM_ID,15122,JO.VALUE,NULL)) AS DIRECTION_MOVE,  
  					  MIN(DECODE(JO.PARAM_ID,15121,JO.VALUE,NULL)) AS VALUE,
  					  MIN(DECODE(JO.PARAM_ID,8000,JO.VALUE,NULL)) AS DIFFERENCE_MOVE,
  					  MIN(DECODE(JO.PARAM_ID,17200,JO.VALUE,NULL)) AS VALUE_AVERAGE,
  					  MIN(DECODE(JO.PARAM_ID,17181,JO.VALUE,NULL)) AS OFFSET_MARK_BEGIN_OBSERV,
  					  MIN(DECODE(JO.PARAM_ID,17240,JO.VALUE,NULL)) AS OFFSET_MARK_CYCLE_ZERO,
  					  MIN(DECODE(JO.PARAM_ID,17182,JO.VALUE,NULL)) AS CURRENT_OFFSET_MARK,
					  OT.OBJECT_PATHS
                 FROM JOURNAL_OBSERVATIONS JO, CYCLES C, POINTS P,
                      ROUTE_POINTS RP, CONVERTERS CR,
                      (SELECT OT1.OBJECT_ID, SUBSTR(MAX(SYS_CONNECT_BY_PATH(O1.NAME,'\')),2) AS OBJECT_PATHS
                         FROM OBJECT_TREES OT1, OBJECTS O1
                        WHERE OT1.OBJECT_ID=O1.OBJECT_ID
                        START WITH OT1.PARENT_ID IS NULL
                      CONNECT BY OT1.PARENT_ID=PRIOR OT1.OBJECT_TREE_ID
					    GROUP BY OT1.OBJECT_ID) OT
                WHERE JO.CYCLE_ID=C.CYCLE_ID
                  AND JO.POINT_ID=P.POINT_ID
                  AND RP.POINT_ID=JO.POINT_ID
                  AND CR.CONVERTER_ID=P.POINT_ID 
				  AND P.OBJECT_ID=OT.OBJECT_ID
				  AND JO.MEASURE_TYPE_ID=3620
                  AND JO.PARAM_ID IN (15120, /* Место нуля */
                                      15122, /* Направление хода */
                                      15121, /* Отсчет */
                                      8000, /* Разн. хода */
									  17200, /* Отсчет средний */
									  17181, /* Смещ. марки с нач. набл. */
									  17240, /* Смещ. марки с цикла прин. за нулевой */
									  17182 /* Текущее смещение марки */)
                  AND C.CYCLE_NUM>=NUM_MIN AND C.CYCLE_NUM<=NUM_MAX
				  AND C.IS_CLOSE=GET_SOS_JOURNAL_OBSERVATIONS.IS_CLOSE								  
				GROUP BY JO.DATE_OBSERVATION, JO.CYCLE_ID, C.CYCLE_NUM, JO.POINT_ID, 
				         P.NAME, CR.CONVERTER_ID, CR.NAME, JO.GROUP_ID, RP.PRIORITY,  
						 OT.OBJECT_PATHS
                ORDER BY JO.DATE_OBSERVATION, JO.GROUP_ID, RP.PRIORITY) LOOP
	INC2.CYCLE_ID:=INC1.CYCLE_ID;
	INC2.CYCLE_NUM:=INC1.CYCLE_NUM;
	INC2.DATE_OBSERVATION:=INC1.DATE_OBSERVATION;
	INC2.POINT_ID:=INC1.POINT_ID;
	INC2.POINT_NAME:=INC1.POINT_NAME;
	INC2.CONVERTER_ID:=INC1.CONVERTER_ID;
	INC2.CONVERTER_NAME:=INC1.CONVERTER_NAME;
    INC2.PLACE_ZERO:=INC1.PLACE_ZERO;
    INC2.DIRECTION_MOVE:=INC1.DIRECTION_MOVE;
    INC2.VALUE:=INC1.VALUE;
    INC2.DIFFERENCE_MOVE:=INC1.DIFFERENCE_MOVE;
    INC2.VALUE_AVERAGE:=INC1.VALUE_AVERAGE;
    INC2.OFFSET_MARK_BEGIN_OBSERV:=INC1.OFFSET_MARK_BEGIN_OBSERV;
    INC2.OFFSET_MARK_CYCLE_ZERO:=INC1.OFFSET_MARK_CYCLE_ZERO;
    INC2.CURRENT_OFFSET_MARK:=INC1.CURRENT_OFFSET_MARK;	
	INC2.OBJECT_PATHS:=INC1.OBJECT_PATHS;
	
    PIPE ROW (INC2);
  END LOOP;	
  RETURN;
END;

--

/* Создание просмотра Струнно-оптического створа в журнале наблюдений старых данных */

CREATE MATERIALIZED VIEW S_SOS_JOURNAL_OBSERVATIONS_O
NOLOGGING
NOCACHE
NOPARALLEL
BUILD DEFERRED
REFRESH COMPLETE
START WITH TO_DATE('01.06.2007','DD.MM.YYYY')
DISABLE QUERY REWRITE AS
SELECT * FROM TABLE(GET_SOS_JOURNAL_OBSERVATIONS(1))

--

/* Обновление просмотра Струнно-оптического створа в журнале наблюдений старых данных */

BEGIN
  DBMS_REFRESH.REFRESH('S_SOS_JOURNAL_OBSERVATIONS_O');
END;

--

/* Создание индекса на цикл просмотра Струнно-оптического створа в журнале наблюдений старых данных */

CREATE INDEX IDX_SOS_JO_O_1
 ON S_SOS_JOURNAL_OBSERVATIONS_O(CYCLE_ID)

--

/* Создание индекса на дату наблюдения просмотра Струнно-оптического створа в журнале наблюдений старых данных */

CREATE INDEX IDX_SOS_JO_O_2
 ON S_SOS_JOURNAL_OBSERVATIONS_O(DATE_OBSERVATION)

--

/* Создание просмотра Струнно-оптического створа в журнале наблюдений новых данных */

CREATE OR REPLACE VIEW S_SOS_JOURNAL_OBSERVATIONS_N
AS
  SELECT * FROM TABLE(GET_SOS_JOURNAL_OBSERVATIONS(0))

--

/* Создание просмотра Струнно-оптического створа в журнале наблюдений */

CREATE OR REPLACE VIEW S_SOS_JOURNAL_OBSERVATIONS
AS
  SELECT JOO.*
    FROM S_SOS_JOURNAL_OBSERVATIONS_O JOO
   UNION
  SELECT JON.*
    FROM S_SOS_JOURNAL_OBSERVATIONS_N JON

--

/* Фиксация изменений БД */

COMMIT
