/* Создание просмотра Пьезометров с Гидрометеорологией в журнале наблюдений */

CREATE OR REPLACE VIEW S_PZM_JOURNAL_OBSERVATIONS_GMO
AS
  SELECT PZM.*,
         GMO.UVB, 
		 GMO.UNB,
		 GMO.T_AIR,
		 GMO.T_WATER,
		 GMO.RAIN_DAY,
		 GMO.PREC,
		 GMO.PREC_NAME,
		 GMO.UNSET,
		 GMO.INFLUX,
		 GMO.V_VAULT,
		 GMO.UVB_INC,
		 GMO.RAIN_YEAR,
		 GMO.T_AIR_10,
		 GMO.T_AIR_30
    FROM S_PZM_JOURNAL_OBSERVATIONS PZM, S_GMO_JOURNAL_OBSERVATIONS GMO
   WHERE PZM.DATE_OBSERVATION=GMO.DATE_OBSERVATION (+)	 

--

/* Фиксация изменений БД */

COMMIT
