/* Создание таблицы просмотра суммарных расходов */ 

CREATE OR REPLACE VIEW S_FLT_TOTAL_CHARGES
AS 
SELECT
JO.MEASURE_TYPE_ID,
MT.NAME AS MEASURE_TYPE_NAME,
JO.CYCLE_ID,
C.CYCLE_NUM,
JO.DATE_OBSERVATION,
SUM(JO.VALUE) AS RASXOD,
P.COORDINATE_Z,
MT.PRIORITY AS PR_MT
FROM
JOURNAL_OBSERVATIONS JO,
CYCLES C,
POINTS P,
MEASURE_TYPES MT
WHERE
JO.MEASURE_TYPE_ID IN (2581,2626,2582,2583)
AND JO.PARAM_ID=3042
AND C.CYCLE_ID=JO.CYCLE_ID
AND P.POINT_ID=JO.POINT_ID
AND MT.MEASURE_TYPE_ID=JO.MEASURE_TYPE_ID
GROUP BY
JO.MEASURE_TYPE_ID,
MT.NAME,
JO.CYCLE_ID,
C.CYCLE_NUM,
JO.DATE_OBSERVATION,
P.COORDINATE_Z,
MT.PRIORITY
ORDER BY
MT.PRIORITY,
P.COORDINATE_Z DESC



