/* Создание таблицы просмотра суммарных фильтрационных расходов 2 1 */

CREATE OR REPLACE VIEW S_FLT_TOTAL_CHARGES_2_1
AS 
SELECT "MEASURE_TYPE_ID","MEASURE_TYPE_NAME","CYCLE_ID","CYCLE_NUM","POINT_ID","DATE_OBSERVATION","RASXOD","COORDINATE_Z","SEK","PR_MT"
FROM S_FLT_TOTAL_CHARGES_2
WHERE POINT_ID=3529


