/* Создание таблицы отделов */

CREATE TABLE DIVISIONS
(
  DIVISION_ID INTEGER NOT NULL, 
  PARENT_ID INTEGER,
  NAME VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY(DIVISION_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES DIVISIONS (DIVISION_ID) ON DELETE CASCADE
)

--

/* Фиксация изменений */

COMMIT

