/* Создание таблицы персонала */

CREATE TABLE PERSONNELS
(
  PERSONNEL_ID INTEGER NOT NULL, 
  DIVISION_ID INTEGER NOT NULL,
  FNAME VARCHAR2(50) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  SNAME VARCHAR2(50) NOT NULL,
  DATE_ACCEPT DATE NOT NULL,
  DATE_SACK DATE,
  PRIMARY KEY (PERSONNEL_ID),
  FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS (DIVISION_ID)
)  

--

/* Фиксация изменений */

COMMIT