/* Создание таблицы файловых отчетов */

CREATE TABLE FILE_REPORTS
(
  FILE_REPORT_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  FILE_NAME VARCHAR2(250) NOT NULL,
  MODULE_NAME VARCHAR2(100) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  MENU VARCHAR2(250) NOT NULL,
  PRIMARY KEY (FILE_REPORT_ID)
)

--

/* Фиксация изменений */

COMMIT