/* Создание таблицы базовых отчетов */

CREATE TABLE BASE_REPORTS
(
  BASE_REPORT_ID INTEGER NOT NULL, 
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  REPORT BLOB,
  PRIORITY INTEGER,
  MENU VARCHAR2(250),
  PRIMARY KEY (BASE_REPORT_ID)
)

--

/* Фиксация изменений */

COMMIT