/* Создание таблицы отчетов интерфейсов */

CREATE TABLE INTERFACE_REPORTS
(
  INTERFACE_REPORT_ID INTEGER NOT NULL, 
  BASE_REPORT_ID INTEGER NOT NULL,
  INTERFACE VARCHAR2(250) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (INTERFACE_REPORT_ID),
  FOREIGN KEY (BASE_REPORT_ID) REFERENCES BASE_REPORTS (BASE_REPORT_ID)
)

--

/* Фиксация изменений */

COMMIT