/* Создание таблицы журнала действий */

CREATE TABLE JOURNAL_ACTIONS
(
  JOURNAL_ACTION_ID INTEGER NOT NULL,
  PERSONNEL_ID INTEGER NOT NULL,
  DATE_ACTION DATE NOT NULL,
  OBJECT VARCHAR2(100) NOT NULL,
  METHOD VARCHAR2(100),
  PARAM VARCHAR2(100),
  VALUE CLOB,
  PRIMARY KEY (JOURNAL_ACTION_ID),
  FOREIGN KEY (PERSONNEL_ID) REFERENCES PERSONNELS (PERSONNEL_ID)
)

--

/* Фиксация изменений */

COMMIT
