/* Создание таблицы видов измерений */

CREATE TABLE MEASURE_TYPES
(
  MEASURE_TYPE_ID INTEGER NOT NULL, 
  PARENT_ID INTEGER,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DATE_BEGIN DATE NOT NULL,
  IS_ACTIVE INTEGER NOT NULL,
  PRIORITY INTEGER NOT NULL,
  IS_VISUAL INTEGER DEFAULT 0 NOT NULL,
  IS_BASE INTEGER DEFAULT 0 NOT NULL,
  PRIMARY KEY (MEASURE_TYPE_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID) ON DELETE CASCADE
)  

--

/* Фиксация изменений */

COMMIT
