/* Создание таблицы алгоритмов видов измерения */

CREATE TABLE MEASURE_TYPE_ALGORITHMS 
(
  MEASURE_TYPE_ID INTEGER NOT NULL, 
  ALGORITHM_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE,
  PRIMARY KEY (MEASURE_TYPE_ID,ALGORITHM_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHMS (ALGORITHM_ID)
)

--

/* Фиксация изменений */

COMMIT