/* Создание таблицы уровней параметров */

CREATE TABLE PARAM_LEVELS 
(
  PARAM_ID INTEGER NOT NULL, 
  LEVEL_ID INTEGER NOT NULL, 
  LEVEL_MIN FLOAT NOT NULL,
  LEVEL_MAX FLOAT NOT NULL,
  PRIMARY KEY (PARAM_ID,LEVEL_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID),
  FOREIGN KEY (LEVEL_ID) REFERENCES LEVELS (LEVEL_ID)
)

--

/* Фиксация изменений */

COMMIT