/* Создание таблицы типов приборов */

CREATE TABLE INSTRUMENTS
(
  INSTRUMENT_ID INTEGER NOT NULL, 
  INSTRUMENT_TYPE_ID INTEGER NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DATE_ENTER DATE NOT NULL,
  SERIAL_NUMBER VARCHAR2(100),
  INVENTORY_NUMBER VARCHAR2(100),
  FREQUENCY_TEST VARCHAR2(250),
  DATE_END DATE,
  CLASS_ACCURACY FLOAT,
  RANGE_MEASURE VARCHAR2(100),  
  PRIMARY KEY (INSTRUMENT_ID),
  FOREIGN KEY (INSTRUMENT_TYPE_ID) REFERENCES INSTRUMENT_TYPES (INSTRUMENT_TYPE_ID)
)

--

/* Фиксация изменений */

COMMIT