/* Создание таблицы паспортов приборов */

CREATE TABLE INSTRUMENT_PASSPORTS
(
  INSTRUMENT_PASSPORT_ID INTEGER NOT NULL,
  INSTRUMENT_ID INTEGER NOT NULL,
  DATE_TEST DATE NOT NULL,
  DESCRIPTION VARCHAR2(250),
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (INSTRUMENT_PASSPORT_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID)
)

--

/* Фиксация изменений */

COMMIT