/* Создание таблицы единицы приборов */

CREATE TABLE INSTRUMENT_UNITS 
(
  INSTRUMENT_ID INTEGER NOT NULL, 
  MEASURE_UNIT_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (INSTRUMENT_ID,MEASURE_UNIT_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID),
  FOREIGN KEY (MEASURE_UNIT_ID) REFERENCES MEASURE_UNITS (MEASURE_UNIT_ID)
)

--

/* Фиксация изменений */

COMMIT
