/* Создание таблицы приборов параметров */

CREATE TABLE PARAM_INSTRUMENTS 
(
  PARAM_ID INTEGER NOT NULL, 
  INSTRUMENT_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (PARAM_ID,INSTRUMENT_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID)
)

--

/* Фиксация изменений */

COMMIT