/* Создание таблицы параметров видов измерения */

CREATE TABLE MEASURE_TYPE_PARAMS 
(
  MEASURE_TYPE_ID INTEGER NOT NULL, 
  PARAM_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (MEASURE_TYPE_ID,PARAM_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID)
)

--

/* Фиксация изменений */

COMMIT