/* Создание таблицы плана */

CREATE TABLE PLANS 
(
  MEASURE_TYPE_ID INTEGER NOT NULL, 
  CYCLE_ID INTEGER NOT NULL, 
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE,
  PRIMARY KEY (MEASURE_TYPE_ID,CYCLE_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (CYCLE_ID) REFERENCES CYCLES (CYCLE_ID)
)

--

/* Фиксация изменений */

COMMIT