/* Создание таблицы маршрутов персонала */

CREATE TABLE PERSONNEL_ROUTES 
(
  PERSONNEL_ID INTEGER NOT NULL, 
  ROUTE_ID INTEGER NOT NULL, 
  DEPUTY_ID INTEGER,
  DATE_PURPOSE DATE NOT NULL,
  PRIMARY KEY (PERSONNEL_ID,ROUTE_ID),
  FOREIGN KEY (PERSONNEL_ID) REFERENCES PERSONNELS (PERSONNEL_ID),
  FOREIGN KEY (ROUTE_ID) REFERENCES ROUTES (ROUTE_ID),
  FOREIGN KEY (DEPUTY_ID) REFERENCES PERSONNELS (PERSONNEL_ID)
)

--

/* Фиксация изменений */

COMMIT