/* Создание таблицы точек */

CREATE TABLE POINTS
(
  POINT_ID INTEGER NOT NULL, 
  POINT_TYPE_ID INTEGER NOT NULL,
  OBJECT_ID INTEGER NOT NULL, 
  NAME INTEGER NOT NULL,
  DESCRIPTION VARCHAR2(250),
  COORDINATE_X FLOAT, 
  COORDINATE_Y FLOAT, 
  COORDINATE_Z FLOAT, 
  DATE_ENTER DATE NOT NULL,
  PRIMARY KEY (POINT_ID),
  FOREIGN KEY (POINT_TYPE_ID) REFERENCES POINT_TYPES (POINT_TYPE_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID)
)

--

/* Фиксация изменений */

COMMIT