/* Создание таблицы срезов */

CREATE TABLE CUTS 
(
  CUT_ID INTEGER NOT NULL,
  MEASURE_TYPE_ID INTEGER,
  OBJECT_ID INTEGER,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250), 
  VIEW_NAME VARCHAR2(100) NOT NULL,
  PROC_NAME VARCHAR2(100),
  DETERMINATION CLOB NOT NULL,
  CONDITION VARCHAR2(250),
  PRIORITY INTEGER NOT NULL,
  CUT_TYPE INTEGER NOT NULL,
  PRIMARY KEY (CUT_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID)
)

--

/* Фиксация изменений */

COMMIT