/* Создание таблицы графиков */

CREATE TABLE GRAPHS 
(
  GRAPH_ID INTEGER NOT NULL,
  CUT_ID INTEGER NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  GRAPH_TYPE INTEGER NOT NULL,
  DETERMINATION CLOB,
  PRIORITY INTEGER NOT NULL,
  MENU VARCHAR2(250),
  PRIMARY KEY (GRAPH_ID),
  FOREIGN KEY (CUT_ID) REFERENCES CUTS (CUT_ID)
)

--

/* Фиксация изменений */

COMMIT