/* Создание таблицы приборов точек */

CREATE TABLE POINT_INSTRUMENTS 
(
  POINT_ID INTEGER NOT NULL, 
  INSTRUMENT_ID INTEGER NOT NULL,
  PARAM_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (POINT_ID,INSTRUMENT_ID,PARAM_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID)
)

--

/* Фиксация изменений */

COMMIT