/* Создание таблицы паспортов точек */

CREATE TABLE POINT_PASSPORTS
(
  POINT_PASSPORT_ID INTEGER NOT NULL, 
  POINT_ID INTEGER NOT NULL,
  DATE_CHECKUP DATE NOT NULL,  
  DESCRIPTION VARCHAR2(250),
  PRIMARY KEY (POINT_PASSPORT_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID)
)

--

/* Фиксация изменений */

COMMIT