/* Создание таблицы дерева объектов */

CREATE TABLE OBJECT_TREES
(
  OBJECT_TREE_ID INTEGER NOT NULL, 
  OBJECT_ID INTEGER NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PARENT_ID INTEGER,
  PRIMARY KEY (OBJECT_TREE_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES OBJECT_TREES (OBJECT_TREE_ID)
)

--

/* Фиксация изменений */

COMMIT