/* Создание таблицы чертежей объектов */

CREATE TABLE OBJECT_DRAWINGS 
(
  OBJECT_ID INTEGER NOT NULL, 
  DRAWING_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (OBJECT_ID,DRAWING_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID),
  FOREIGN KEY (DRAWING_ID) REFERENCES DRAWINGS (DRAWING_ID)
)

--

/* Фиксация изменений */

COMMIT