/* Создание таблицы документов объектов */

CREATE TABLE OBJECT_DOCUMENTS 
(
  OBJECT_ID INTEGER NOT NULL, 
  DOCUMENT_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (OBJECT_ID,DOCUMENT_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID),
  FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (DOCUMENT_ID)
)

--

/* Фиксация изменений */

COMMIT