/* Создание таблицы документов точек */

CREATE TABLE POINT_DOCUMENTS 
(
  POINT_ID INTEGER NOT NULL, 
  DOCUMENT_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (POINT_ID,DOCUMENT_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID),
  FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (DOCUMENT_ID)
)

--

/* Фиксация изменений */

COMMIT