/* Создание таблицы паспортов объектов */

CREATE TABLE OBJECT_PASSPORTS
(
  OBJECT_PASSPORT_ID INTEGER NOT NULL, 
  OBJECT_ID INTEGER NOT NULL,
  DATE_PASSPORT DATE NOT NULL,
  PARAM_NAME VARCHAR2(100),
  VALUE FLOAT,  
  DESCRIPTION VARCHAR2(250),
  PRIMARY KEY (OBJECT_PASSPORT_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID)
)

--

/* Фиксация изменений */

COMMIT