/* Создание таблицы преобразователей */

CREATE TABLE CONVERTERS 
(
  CONVERTER_ID INTEGER NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DATE_ENTER DATE NOT NULL,   
  NOT_OPERATION INTEGER NOT NULL,
  PRIMARY KEY (CONVERTER_ID),
  FOREIGN KEY (CONVERTER_ID) REFERENCES POINTS (POINT_ID)
)

--

/* Фиксация изменений */

COMMIT