/* Создание таблицы компонентов преобразователей */

CREATE TABLE COMPONENTS
(
  COMPONENT_ID INTEGER NOT NULL,
  CONVERTER_ID INTEGER NOT NULL,
  PARAM_ID INTEGER NOT NULL,   
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PRIMARY KEY (COMPONENT_ID),
  FOREIGN KEY (CONVERTER_ID) REFERENCES CONVERTERS (CONVERTER_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID)
)

--

/* Фиксация изменений */

COMMIT