/* Создание таблицы паспортов преобразователей */

CREATE TABLE CONVERTER_PASSPORTS
(
  CONVERTER_PASSPORT_ID INTEGER NOT NULL,
  COMPONENT_ID INTEGER NOT NULL,
  INSTRUMENT_ID INTEGER,
  MEASURE_UNIT_ID INTEGER,
  DESCRIPTION VARCHAR2(250),
  VALUE VARCHAR2(100),
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE,
  PRIMARY KEY (CONVERTER_PASSPORT_ID),
  FOREIGN KEY (COMPONENT_ID) REFERENCES COMPONENTS (COMPONENT_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID),
  FOREIGN KEY (MEASURE_UNIT_ID) REFERENCES MEASURE_UNITS (MEASURE_UNIT_ID)
)

--

/* Фиксация изменений */

COMMIT