/* Создание таблицы критериев безопасности */

CREATE TABLE CRITERIAS
(
  CRITERIA_ID INTEGER NOT NULL,
  ALGORITHM_ID INTEGER NOT NULL,
  MEASURE_UNIT_ID INTEGER,
  NAME VARCHAR2(250) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  FIRST_MIN_VALUE FLOAT NOT NULL,
  FIRST_MAX_VALUE FLOAT,
  FIRST_MODULO INTEGER NOT NULL,
  SECOND_MIN_VALUE FLOAT NOT NULL,
  SECOND_MAX_VALUE FLOAT,
  SECOND_MODULO INTEGER NOT NULL,
  ENABLED INTEGER NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (CRITERIA_ID),
  FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHMS (ALGORITHM_ID),
  FOREIGN KEY (MEASURE_UNIT_ID) REFERENCES MEASURE_UNITS (MEASURE_UNIT_ID)
)

--

/* Фиксация изменений */

COMMIT