/* Создание таблицы план-графиков */

CREATE TABLE MEASURE_TYPE_GRAPHS
(
  YEAR INTEGER NOT NULL,
  MEASURE_TYPE_ID INTEGER,
  JANUARY INTEGER,
  FEBRUARY INTEGER,
  MARCH INTEGER,
  APRIL INTEGER,
  MAY INTEGER,
  JUNE INTEGER,
  JULY INTEGER,
  AUGUST INTEGER,
  SEPTEMBER INTEGER,
  OKTOBER INTEGER,
  NOVEMBER INTEGER,
  DECEMBER INTEGER,
  PRIMARY KEY (YEAR,MEASURE_TYPE_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID)

)

--

/* Фиксация изменений */

COMMIT