/* Создание таблицы журнала осмотров */

CREATE TABLE JOURNAL_CHECKUPS
(
  JOURNAL_CHECKUP_ID INTEGER NOT NULL,
  POINT_ID INTEGER NOT NULL,
  CYCLE_ID INTEGER NOT NULL,
  MEASURE_TYPE_ID INTEGER NOT NULL,
  DEFECT_VIEW_ID INTEGER NOT NULL,
  DATE_OBSERVATION DATE NOT NULL,
  NOTE VARCHAR2(250),
  JOURNAL_NUM VARCHAR2(100),
  WHO_ENTER INTEGER NOT NULL,
  DATE_ENTER DATE NOT NULL,
  WHO_CONFIRM INTEGER,
  DATE_CONFIRM DATE,
  INCLINATION VARCHAR2(250),
  WIDTH_DEFECT VARCHAR2(50),
  HEIGHT_DEFECT VARCHAR2(50),
  LENGTH_DEFECT VARCHAR2(50),
  PRIMARY KEY (JOURNAL_CHECKUP_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID),
  FOREIGN KEY (CYCLE_ID) REFERENCES CYCLES (CYCLE_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (DEFECT_VIEW_ID) REFERENCES DEFECT_VIEWS (DEFECT_VIEW_ID),
  FOREIGN KEY (WHO_ENTER) REFERENCES PERSONNELS (PERSONNEL_ID),
  FOREIGN KEY (WHO_CONFIRM) REFERENCES PERSONNELS (PERSONNEL_ID)
) 

--

/* Создание индекса по дате наблюдения журнала осмотров */

CREATE INDEX IDX_JOURNAL_CHECKUPS_1
 ON JOURNAL_CHECKUPS(DATE_OBSERVATION)

--

/* Создание индекса по циклу журнала осмотров */

CREATE INDEX IDX_JOURNAL_CHECKUPS_2
 ON JOURNAL_CHECKUPS(CYCLE_ID)

--

/* Создание индекса по виду измерения журнала осмотров */

CREATE INDEX IDX_JOURNAL_CHECKUPS_3
 ON JOURNAL_CHECKUPS(MEASURE_TYPE_ID)

--

/* Создание индекса по точке журнала осмотров */

CREATE INDEX IDX_JOURNAL_CHECKUPS_4
 ON JOURNAL_CHECKUPS(POINT_ID)

--

/* Создание индекса по виду дефекта */

CREATE INDEX IDX_JOURNAL_CHECKUPS_5
 ON JOURNAL_CHECKUPS(DEFECT_VIEW_ID)

--

/* Создание индекса по месяцу журнала осмотров */

CREATE BITMAP INDEX IDX_JOURNAL_CHECKUPS_6
 ON JOURNAL_CHECKUPS (EXTRACT(MONTH FROM DATE_OBSERVATION))

--

/* Создание индекса по году журнала осмотров */

CREATE BITMAP INDEX IDX_JOURNAL_CHECKUPS_7
 ON JOURNAL_CHECKUPS (EXTRACT(YEAR FROM DATE_OBSERVATION))

--

/* Фиксация изменений */

COMMIT