/* Создание таблицы документов осмотров */

CREATE TABLE DOC_CHECKUPS
(
  DOC_CHECKUP_ID INTEGER NOT NULL,
  JOURNAL_CHECKUP_ID INTEGER NOT NULL,
  DATE_DOC DATE NOT NULL,
  NAME VARCHAR2(250) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  DOC BLOB NOT NULL,
  EXTENSION VARCHAR2(50) NOT NULL,
  PRIMARY KEY (DOC_CHECKUP_ID),
  FOREIGN KEY (JOURNAL_CHECKUP_ID) REFERENCES JOURNAL_CHECKUPS (JOURNAL_CHECKUP_ID)
) 

--

/* Фиксация изменений */

COMMIT