/* Создание таблицы связи объектов и групп */

CREATE TABLE GROUP_OBJECTS 
(
  GROUP_ID INTEGER NOT NULL, 
  OBJECT_ID INTEGER NOT NULL, 
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (GROUP_ID,OBJECT_ID),
  FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID)
)

--

/* Фиксация изменений */

COMMIT

