/* Создание таблицы журнала наблюдений */

CREATE TABLE JOURNAL_OBSERVATIONS
(
  JOURNAL_OBSERVATION_ID INTEGER NOT NULL,
  JOURNAL_FIELD_ID INTEGER,
  INSTRUMENT_ID INTEGER,
  MEASURE_TYPE_ID INTEGER NOT NULL,
  MEASURE_UNIT_ID INTEGER,
  DATE_OBSERVATION DATE NOT NULL,
  CYCLE_ID INTEGER NOT NULL,
  POINT_ID INTEGER,
  PARAM_ID INTEGER,
  VALUE FLOAT NOT NULL,
  WHO_ENTER INTEGER NOT NULL,
  DATE_ENTER DATE NOT NULL,
  ALGORITHM_ID INTEGER NOT NULL,
  GROUP_ID VARCHAR2(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (JOURNAL_OBSERVATION_ID),
  FOREIGN KEY (CYCLE_ID) REFERENCES CYCLES (CYCLE_ID),
  FOREIGN KEY (POINT_ID) REFERENCES POINTS (POINT_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID),
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENTS (INSTRUMENT_ID),
  FOREIGN KEY (MEASURE_UNIT_ID) REFERENCES MEASURE_UNITS (MEASURE_UNIT_ID),
  FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPES (MEASURE_TYPE_ID),
  FOREIGN KEY (WHO_ENTER) REFERENCES PERSONNELS (PERSONNEL_ID),
  FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHMS (ALGORITHM_ID)
)

--

/* Создание индекса по алгоритму журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_1
 ON JOURNAL_OBSERVATIONS(ALGORITHM_ID)

--

/* Создание индекса по циклу журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_2
 ON JOURNAL_OBSERVATIONS(CYCLE_ID)

--

/* Создание индекса по дате наблюдения журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_3
 ON JOURNAL_OBSERVATIONS(DATE_OBSERVATION)

--

/* Создание индекса по группе журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_4
 ON JOURNAL_OBSERVATIONS(GROUP_ID)

--

/* Создание индекса по прибору журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_5
 ON JOURNAL_OBSERVATIONS(INSTRUMENT_ID)

--

/* Создание индекса по идентификатору журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_6
 ON JOURNAL_OBSERVATIONS(JOURNAL_FIELD_ID)

--

/* Создание индекса по виду измерения журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_7
 ON JOURNAL_OBSERVATIONS(MEASURE_TYPE_ID)

--

/* Создание индекса по единице измерения журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_8
 ON JOURNAL_OBSERVATIONS(MEASURE_UNIT_ID)

--

/* Создание индекса по параметру журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_9
 ON JOURNAL_OBSERVATIONS(PARAM_ID)

--

/* Создание индекса по точке журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_10
 ON JOURNAL_OBSERVATIONS(POINT_ID)

--

/* Создание индекса по месяцу журнала наблюдений */

CREATE BITMAP INDEX IDX_JOURNAL_OBSERVATIONS_11
 ON JOURNAL_OBSERVATIONS (EXTRACT(MONTH FROM DATE_OBSERVATION))

--

/* Создание индекса по году журнала наблюдений */

CREATE BITMAP INDEX IDX_JOURNAL_OBSERVATIONS_12
 ON JOURNAL_OBSERVATIONS (EXTRACT(YEAR FROM DATE_OBSERVATION))

--

/* Создание индекса по приоритету журнала наблюдений */

CREATE INDEX IDX_JOURNAL_OBSERVATIONS_13
 ON JOURNAL_OBSERVATIONS (PRIORITY)

--

/* Фиксация изменений */

COMMIT