/* Создание процедуры изменения роли учетной записи */

CREATE OR REPLACE PROCEDURE U_ACCOUNT_ROLE
(
  ACCOUNT_ID IN INTEGER, 
  ROLE_ID IN INTEGER, 
  OLD_ACCOUNT_ID IN INTEGER, 
  OLD_ROLE_ID IN INTEGER 
) 
AS 
BEGIN 
  UPDATE ACCOUNTS_ROLES  
     SET ACCOUNT_ID=U_ACCOUNT_ROLE.ACCOUNT_ID, 
         ROLE_ID=U_ACCOUNT_ROLE.ROLE_ID 
   WHERE ACCOUNT_ID=OLD_ACCOUNT_ID  
     AND ROLE_ID=OLD_ROLE_ID; 
  COMMIT;         
END;

--

/* Фиксация изменений */

COMMIT

