/* Создание процедуры изменения устройства */

CREATE OR REPLACE PROCEDURE U_DEVICE
( 
  DEVICE_ID IN INTEGER, 
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2, 
  DATE_ENTER IN DATE, 
  OLD_DEVICE_ID IN INTEGER 
) 
AS 
BEGIN 
  UPDATE DEVICES  
     SET DEVICE_ID=U_DEVICE.DEVICE_ID, 
         NAME=U_DEVICE.NAME, 
         DESCRIPTION=U_DEVICE.DESCRIPTION, 
         DATE_ENTER=U_DEVICE.DATE_ENTER 
   WHERE DEVICE_ID=OLD_DEVICE_ID; 
  COMMIT;         
END;

--

/* Фиксация изменений */

COMMIT

