/* Создание процедуры изменения объекта */

CREATE OR REPLACE PROCEDURE U_OBJECT
( 
  OBJECT_ID IN INTEGER, 
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2, 
  SHORT_NAME IN VARCHAR2, 
  OLD_OBJECT_ID IN INTEGER 
) 
AS 
BEGIN 
  UPDATE OBJECTS  
     SET OBJECT_ID=U_OBJECT.OBJECT_ID, 
         NAME=U_OBJECT.NAME,  
         DESCRIPTION=U_OBJECT.DESCRIPTION, 
   SHORT_NAME=U_OBJECT.SHORT_NAME  
   WHERE OBJECT_ID=OLD_OBJECT_ID; 
  COMMIT;         
END;

--

/* Фиксация изменений */

COMMIT

