/* Создание процедуры изменения типа точки */
        
CREATE OR REPLACE PROCEDURE U_POINT_TYPE
( 
  POINT_TYPE_ID IN INTEGER, 
  NAME IN VARCHAR2, 
  DESCRIPTION IN VARCHAR2, 
  OLD_POINT_TYPE_ID IN INTEGER 
) 
AS 
BEGIN 
  UPDATE POINT_TYPES  
     SET POINT_TYPE_ID=U_POINT_TYPE.POINT_TYPE_ID, 
         NAME=U_POINT_TYPE.NAME,  
         DESCRIPTION=U_POINT_TYPE.DESCRIPTION  
   WHERE POINT_TYPE_ID=OLD_POINT_TYPE_ID; 
  COMMIT;         
END;

--

/* Фиксация изменений */

COMMIT

