/* Создание процедуры изменения роли */

CREATE OR REPLACE PROCEDURE U_ROLE
( 
  ACCOUNT_ID IN INTEGER, 
  NAME IN VARCHAR2,  
  DESCRIPTION IN VARCHAR2, 
  OLD_ACCOUNT_ID IN INTEGER 
) 
AS 
BEGIN 
  UPDATE ACCOUNTS  
     SET ACCOUNT_ID=U_ROLE.ACCOUNT_ID, 
         NAME=U_ROLE.NAME, 
         DESCRIPTION=U_ROLE.DESCRIPTION 
   WHERE ACCOUNT_ID=OLD_ACCOUNT_ID; 
  COMMIT;         
END;

--

/* Фиксация изменений */

COMMIT

