/* Создание процедуры расчета напряжения по арматурным динамометрам */

CREATE OR REPLACE PROCEDURE CALCULATE_NDS_ARMATURE_TENSION
(
  POINT_ID IN INTEGER,
  FREQUENCY IN FLOAT,
  DATE_OBSERVATION IN DATE,
  MEASURE_TYPE_ID IN INTEGER,
  CYCLE_ID IN INTEGER,
  IS_BASE IN INTEGER,
  TENSION OUT FLOAT
)
AS
  RATIO_INSTRUMENT FLOAT;
  MODULE_FREQUENCY FLOAT;
  DIAMETER FLOAT;
  FREQUENCY_0 FLOAT;
  POINT_NAME INTEGER;
BEGIN

  SELECT NAME INTO POINT_NAME FROM POINTS WHERE POINT_ID=CALCULATE_NDS_ARMATURE_TENSION.POINT_ID;
/*  DBMS_OUTPUT.PUT_LINE('POINT_NAME='||TO_CHAR(POINT_NAME));			
  DBMS_OUTPUT.PUT_LINE('DATE='||TO_CHAR(DATE_OBSERVATION));		
  DBMS_OUTPUT.PUT_LINE('FREQUENCY='||TO_CHAR(FREQUENCY));*/		
  
  RATIO_INSTRUMENT:=NULL;
  FOR INC IN (SELECT CP.VALUE,
 	                 CP.DATE_BEGIN,
                     CP.DATE_END
                FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
               WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                 AND C.CONVERTER_ID=P.POINT_ID
                 AND P.POINT_ID=CALCULATE_NDS_ARMATURE_TENSION.POINT_ID
                 AND C.PARAM_ID=60018 /* Коэффициент прибора */
               ORDER BY CP.DATE_BEGIN) LOOP
    RATIO_INSTRUMENT:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');				   
    EXIT WHEN RATIO_INSTRUMENT IS NOT NULL;
  END LOOP;

/*  DBMS_OUTPUT.PUT_LINE('RATIO_INSTRUMENT='||TO_CHAR(RATIO_INSTRUMENT));*/		
  
  MODULE_FREQUENCY:=NULL;
  FOR INC IN (SELECT CP.VALUE,
 	                 CP.DATE_BEGIN,
                     CP.DATE_END
                FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
               WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                 AND C.CONVERTER_ID=P.POINT_ID
                 AND P.POINT_ID=CALCULATE_NDS_ARMATURE_TENSION.POINT_ID
                 AND C.PARAM_ID=60019 /* Модуль частоты */
               ORDER BY CP.DATE_BEGIN) LOOP
    MODULE_FREQUENCY:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');				   
    EXIT WHEN MODULE_FREQUENCY IS NOT NULL;
  END LOOP;

/*  DBMS_OUTPUT.PUT_LINE('MODULE_FREQUENCY='||TO_CHAR(MODULE_FREQUENCY));*/		

  DIAMETER:=NULL;
  FOR INC IN (SELECT CP.VALUE,
 	                 CP.DATE_BEGIN,
                     CP.DATE_END
                FROM CONVERTER_PASSPORTS CP, COMPONENTS C, POINTS P
               WHERE CP.COMPONENT_ID=C.COMPONENT_ID
                 AND C.CONVERTER_ID=P.POINT_ID
                 AND P.POINT_ID=CALCULATE_NDS_ARMATURE_TENSION.POINT_ID
                 AND C.PARAM_ID=60021 /* Диаметр арматуры */
               ORDER BY CP.DATE_BEGIN) LOOP
    DIAMETER:=TO_NUMBER(REPLACE(INC.VALUE,',','.'),'FM99999.9999');				   
    EXIT WHEN DIAMETER IS NOT NULL;
  END LOOP;

/*  DBMS_OUTPUT.PUT_LINE('DIAMETER='||TO_CHAR(DIAMETER));*/		
  
  IF (MODULE_FREQUENCY IS NOT NULL) AND
     (RATIO_INSTRUMENT IS NOT NULL) AND
	 (DIAMETER IS NOT NULL) THEN
	 
	 FREQUENCY_0:=0.0;
	 DIAMETER:=DIAMETER/20;
	 IF (DIAMETER<>0.0) THEN
 	   TENSION:=((POWER(FREQUENCY,2)/1000-MODULE_FREQUENCY)*RATIO_INSTRUMENT*1000)/(3.1415927*POWER(DIAMETER,2))*0.0981;
	 END IF;  
	 
  END IF;
  
/*  DBMS_OUTPUT.PUT_LINE('TENSION='||TO_CHAR(TENSION));*/	 
END;

--

/* Фиксация изменений БД */

COMMIT