/* Создание просмотра персонала */

CREATE OR REPLACE VIEW S_PERSONNELS
AS 
SELECT P.PERSONNEL_ID,P.DIVISION_ID,P.FNAME,P.NAME,P.SNAME,P.DATE_ACCEPT,P.DATE_SACK, D.NAME AS DIVISION_NAME 
  FROM PERSONNELS P, DIVISIONS D
 WHERE D.DIVISION_ID=P.DIVISION_ID

--

/* Фиксация изменений */

COMMIT


