/* Создание просмотра марщрутов видов измерения */

CREATE OR REPLACE VIEW S_MEASURE_TYPE_ROUTES
AS
SELECT MTR.MEASURE_TYPE_ID,
       MTR.ROUTE_ID,
       MTR.PRIORITY,
       MT.NAME AS MEASURE_TYPE_NAME,
       MT.IS_BASE,
       R.NAME AS ROUTE_NAME,
       R.DESCRIPTION AS ROUTE_DESCRIPTION
  FROM MEASURE_TYPE_ROUTES MTR,
       MEASURE_TYPES MT,
       ROUTES R
 WHERE MT.MEASURE_TYPE_ID = MTR.MEASURE_TYPE_ID
   AND R.ROUTE_ID = MTR.ROUTE_ID

--

/* Фиксация изменений */

COMMIT



