/* Создание просмотра измерительных точек маршрутов */

CREATE OR REPLACE VIEW S_ROUTE_POINTS
AS
SELECT RP.ROUTE_ID, RP.POINT_ID, RP.PRIORITY, R.NAME AS ROUTE_NAME, P.NAME AS POINT_NAME, P.DESCRIPTION AS POINT_DESCRIPTION, O.OBJECT_ID,
       O.NAME AS OBJECT_NAME
  FROM ROUTE_POINTS RP, ROUTES R, POINTS P, OBJECTS O
 WHERE R.ROUTE_ID = RP.ROUTE_ID AND P.POINT_ID = RP.POINT_ID AND P.OBJECT_ID = O.OBJECT_ID

--

/* Фиксация изменений */

COMMIT


