/* Создание просмотра документов объектов */

CREATE OR REPLACE VIEW S_OBJECT_DOCUMENTS
AS 
SELECT OD.OBJECT_ID,
       OD.DOCUMENT_ID,
       OD.PRIORITY,
       O.NAME AS OBJECT_NAME,
       D.NAME AS DOCUMENT_NAME,
       D.DESCRIPTION AS DOCUMENT_DESCRIPTION,
       D.FILE_NAME
  FROM OBJECT_DOCUMENTS OD,
       OBJECTS O,
       DOCUMENTS D
 WHERE O.OBJECT_ID = OD.OBJECT_ID
   AND D.DOCUMENT_ID = OD.DOCUMENT_ID

--

/* Фиксация изменений */

COMMIT


