/* Создание просмотра паспортов объектов */

CREATE OR REPLACE VIEW S_OBJECT_PASSPORTS
AS 
SELECT OP.OBJECT_PASSPORT_ID,OP.OBJECT_ID,OP.DATE_PASSPORT,OP.PARAM_NAME,OP.VALUE,OP.DESCRIPTION,
       O.NAME AS OBJECT_NAME
  FROM OBJECT_PASSPORTS OP, OBJECTS O
 WHERE OP.OBJECT_ID=O.OBJECT_ID

--

/* Фиксация изменений */

COMMIT


