/* Создание просмотра компонентов приборов */

CREATE OR REPLACE VIEW S_INSTRUMENT_COMPONENTS
AS 
SELECT PI.PARAM_ID,
       PI.INSTRUMENT_ID,
       PI.PRIORITY,
       I.NAME AS INSTRUMENT_NAME,
       C.NAME AS COMPONENT_NAME,
       C.COMPONENT_ID
  FROM PARAM_INSTRUMENTS PI,
       COMPONENTS C,
       INSTRUMENTS I
 WHERE PI.PARAM_ID = C.PARAM_ID
   AND PI.INSTRUMENT_ID = I.INSTRUMENT_ID

--

/* Фиксация изменений */

COMMIT

