/* Создание просмотра плана-графика */

CREATE OR REPLACE VIEW S_PLAN_GRAPH_YEARS
AS 
SELECT MTG.YEAR, 
       MAX(DECODE(C.CYCLE_MONTH, 11, C.IS_CLOSE, -1)) AS IS_CLOSE
  FROM MEASURE_TYPE_GRAPHS MTG, CYCLES C
 WHERE C.CYCLE_YEAR=MTG.YEAR
 GROUP BY MTG.YEAR

--

/* Фиксация изменений */

COMMIT


