/* Создание просмотра полевого журнала новых данных струнно-оптического створа */

CREATE OR REPLACE VIEW S_SOS_JOURNAL_FIELDS_N
AS
SELECT CYCLE_ID,CYCLE_NUM,JOURNAL_NUM,DATE_OBSERVATION,POINT_ID,POINT_NAME,CONVERTER_ID,CONVERTER_NAME,PLACE_ZERO,
      DIRECTION_MOVE,VALUE,DIFFERENCE_MOVE,ERROR_MARK,VALUE_AVERAGE,OBJECT_PATHS FROM
TABLE(GET_SOS_JOURNAL_FIELDS(0))

--

/* Фиксация изменений */

COMMIT


