/* Создание просмотра суммирования расхода фильтрации DR1 BEREG */

CREATE OR REPLACE VIEW S_FLT_SUM_EXPENSE_DR1_BEREG
AS 
SELECT   CYCLE_NUM,
         SUM (EXPENSE) EXPENSE_BEREG
    FROM S_FLT_SUM_EXPENSE_DR1
   WHERE COORDINATE_Z NOT IN (131, 153)
GROUP BY CYCLE_NUM
ORDER BY CYCLE_NUM

--

/* Фиксация изменений */

COMMIT


